### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#100]
Discussion around whether or not the repo should leverage TypeScript - https://www.typescriptlang.org

**Comment by asfordmatt** [comment]
I think that would be difficult without Carbon providing typings

https://github.com/carbon-design-system/carbon/issues/5873

**Comment by lee-chase** [comment]
I have no objection to typescript in principle, but I do wonder if it would put an extra hurdle between in the way of contributions.

**Comment by andrea-gm** [comment]
@SimonFinney was this resolved offline? Can we close the issue?
