### ISSUE TITLE
ExpressiveCard is not exported

### ISSUE THREAD

**Issue by jinzih** [carbon-design-system/ibm-cloud-cognitive#1012]
## What package(s) are you using?

- [X ] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
I see ExpressiveCard is available in the storybook: https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-cards-expressivecard--clickable

But when I try to use it in the code, it shows this error:
error - ./components/Connect/AddDatasourceTearsheet/AddDatasourceTearsheet.tsx
Attempted import error: 'ExpressiveCard' is not exported from '@carbon/ibm-cloud-cognitive'.

@dcwarwick suggested me to open this bug, so this component will be included in the latest release soon.

Thank you!

**Comment by dcwarwick** [comment]
@davidmenendez ExpressiveCard and ProductiveCard are in the package-settings.js as public components, but are not currently exported: they need adding to packages/cloud-cognitive/src/components/index.js and _index.scss so they can be used from our published package.

@jinzih Just to note that ExpressiveCard and ProductiveCard have been started, but not yet reviewed and released, so they are in "Canary" state, which means they need explicitly enabling with the feature flag as we discussed earlier, and they are still subject to changes including breaking changes as we review them technically and with the design team. They are on our priority list for review and release, though, so I hope they will move out of Canary status before too long.
