### ISSUE TITLE
TagSet overflow menu can be shown over the all tags dialog

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1017]
The TagSet presents an overflow menu which contains a "View all tags" link which opens a dialog to show all tags. In some circumstances, the overflow menu continues to show when the all tags dialog is opened. This shouldn't happen -- the overflow menu should close whenever the "View all tags" link is activated.

To reproduce:
 * Open a TagSet story, _e.g._ "Many tags".
 * Shrink the available space until at least eleven tags are not shown, so that both the overflow menu and the all tags dialog will be available.
 * Click on the overflow tag to display the overflow menu.
 * Now click somewhere within the overflow menu so as to remove focus from the "View all tags" link.
 * Click on the "View all tags" link. The all tags dialog opens, but the overflow menu is still showing over it.
![image](https://user-images.githubusercontent.com/6385315/125911246-f102de13-d253-4f9f-b2a7-6001667c194e.png)

**Comment by dcwarwick** [comment]
@lee-chase

**Comment by davidmenendez** [comment]
i took a look at this and this appears to be a problem with carbon. i've created a sandbox just using the carbon components and the buggy interaction continues to persist here https://codesandbox.io/s/cranky-haibt-onxwf?file=/index.js. it looks like when you click inside the tooltip and then click the link it causes an additional trigger of the tooltips `onChange` handler. i don't think this is something that we can bypass in our own components and needs to be handled by carbon.

**Comment by lee-chase** [comment]
Raised an issue https://github.com/carbon-design-system/carbon/issues/10040 having failed to spot David's sandbox until I scrolled down

https://codesandbox.io/s/hardcore-orla-yl9l0?file=/index.js

**Comment by dcwarwick** [comment]
Hopefully, a fix to Carbon carbon-design-system/carbon#10040 will resolve this -- I've removed the v1 tag, but we can keep this issue open to track the issue.

**Comment by lee-chase** [comment]
Carbon has now fixed this, just waiting on a release.

**Comment by lee-chase** [comment]
This was resolved by Carbon
