### ISSUE TITLE
CreateTearsheet close when the submit return

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1060]
## What will this achieve?

Hy guys,
At the last step when I call the submit, the tearsheet immediatly close.
I'd like to have it open and show a loading until the submit function return.

Should be possible to decide when to close it?

My use case:
- when the user succesfully create an item, it will be redirected to the item page.  

thanks

**Comment by matthewgallo** [comment]
Hey @ninjasun, this is currently possible (it could be that we have not documented how to do this well enough, so I'll try to add some specific docs around how to do this).

For example:
```jsx
<CreateTearsheet
  onRequestSubmit={() =>
    new Promise((resolve) => {
        // Make some API request here, if the request is successful then you can resolve this promise, which will close the tearsheet.
        // If the request fails, then you can reject the promise and the component will remain open and the "Create" button will no longer be in a loading state.
        resolve();
      })
    }
>
...
...
</CreateTearsheet>
```

For another example of this, see [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/CreateTearsheet/preview-components/MultiStepTearsheet.js#L66)

**Comment by matthewgallo** [comment]
![image](https://user-images.githubusercontent.com/10215203/127163785-a1177808-c9ab-42df-aa21-d393bd2f0c0a.png)
From CreateTearsheet storybook docs

**Comment by matthewgallo** [comment]
Feel free to reopen if you have further questions!
