### ISSUE TITLE
open CreateTearsheet on a custom Step index 

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1076]
Hey guys,
I'm implementing a resume create process and with that prop should be straightforward and I can keep the logic outside this component.

cheers

**Comment by andrea-gm** [comment]
@matthewgallo I think this is fine, design wise, to provide that flexibility for edge cases. Prior to adding the prop, the pattern documentation should be updated with a mention of this in the wide tearsheet section (probably under [Behaviors](https://www.carbondesignsystem.com/community/patterns/create-flows#behaviors)). Nothing fancy, just a mention so designers know what is possible.

If one of you can create a PR for the documentation in Carbon, I can help get it looked at/approved.

**Comment by matthewgallo** [comment]
Hey @ninjasun, this functionality has been added to the CreateTearsheet component now. You can use the new `initialStep` prop and pass in the step you want the component to display when it opens. If the value of the `initialStep` prop is invalid, ie it's greater than the total number of steps you have the component will simply render the first step as it normally would and you'll get a console warning indicating that you have provided an invalid value for the `initialStep` component.

See version `@carbon/ibm-cloud-cognitive@0.73.0` or greater.

For example...

```jsx
<CreateTearsheet
  initialStep={2}
  {...otherProps}
>
  <CreateTearsheetStep title="Step 1 title">
    ...
  </CreateTearsheetStep>
  <CreateTearsheetStep title="Step 2 title">
    ...
  </CreateTearsheetStep>
</CreateTearsheet>
```

Let us know if you have any more questions around this new behavior!
