### ISSUE TITLE
CreateTearsheet: design review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1085]
Preliminary design review to prep component for release.

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern maintainer
- [ ] The component’s motion matches the specifications set by the pattern maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can be used
- [x] Changing props in the Storybook updates the component

**Comment by matthewgallo** [comment]
https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-createtearsheet--multi-step-tearsheet

**Comment by andrea-gm** [comment]
- [ ] The form validation should work like in the[ CreateModal example](https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-released-createmodal--with-form-validation). We use (optional) for optional fields and all other fields are assumed required. (This may change down the road, but [that is the carbon guidance today](https://www.carbondesignsystem.com/patterns/forms-pattern/#labels))
- [ ] The published design doesn't show a label in the header area. The line "This is the label of the multi step tearsheet"
- [ ] Not sure if this is possible, but I noticed if my cursor is in the progress indicator area and I scroll down, the body content (form) doesn't scroll down. I totally get why that is, I just thought it might be nice if it did.
- [ ] Toggling on/off is pretty flickery. It looks like the larger cancel button (toggled off) turns active for a second before going back to disabled.
- [ ] We should look into adding some nice motion to the toggle transition. The progress indicator exiting and the side nav coming in. The Cancel button moving, the back button exiting/coming back. It's very jarring compared to how nicely the tearsheet opens/closes and the animated content after clicking Next and Back. Definitely raise this to Andrew.
- [ ] Clicking on the side navigation does not auto scroll to the right section

**Comment by andrea-gm** [comment]
I probably just don't get it, but I tried setting these strings and nothing happened. 
<img width="1321" alt="Screen Shot 2021-07-28 at 7 16 54 PM" src="https://user-images.githubusercontent.com/14081333/127421208-e4578c5e-46a9-40ec-8b7a-440f13b912c2.png">

**Comment by matthewgallo** [comment]
Thanks for the review @andrea-gm! The first two items are addressed in this [PR](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1091). And the last item, regarding the scrolling behavior, was fixed in a PR that got merged yesterday

**Comment by andrea-gm** [comment]
Regarding the 4th item, I edited with this comment:

UPDATE: Looking at the pattern, the "Back" button should disappear and the "Cancel" button should stay where it is. So that would solve the flickering.

**Comment by andrea-gm** [comment]
Also here's some toggle motion from Ruben 

https://user-images.githubusercontent.com/14081333/127541362-f3473e44-2829-4f70-9cb9-7b646b103acf.mp4

**Comment by matthewgallo** [comment]
The cancel/back button item is addressed in https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1091 as well.

**Comment by dcwarwick** [comment]
I opened issue #1097 re storybook

**Comment by matthewgallo** [comment]
@andrea-gm I've added in the microinteraction from Ruben, see https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1104

**Comment by matthewgallo** [comment]
In regards to the second item on the list, because of the positioning of the influencer section of the tearsheet I don't think that scrolling behavior is possible right now. If this is something desired in the future, I think the change would be required in `TearsheetShell.js`.

**Comment by matthewgallo** [comment]
Also the storybook issues are fixed now @andrea-gm. You should be able to change/edit those fields using the storybook controls now.

**Comment by andrea-gm** [comment]
looks good to me! thanks Matt!
