### ISSUE TITLE
Side panel visual tweaks

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#1109]
## What will this achieve?

cuter look

## How will success be measured?

both items addressed, design review

## Additional information

- [x] The scrollbar goes out of view under the footer. Take a look at CreateTearsheet's body scroll for comparison.

- [x] On entry the scrollbar appears last and squeezes the content, making the form fields resize.

**Comment by matthewgallo** [comment]
Fixed in https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1141

**Comment by matthewgallo** [comment]
Complete
