### ISSUE TITLE
CreateFullPage design review

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#1114]
### Standards

- [x] All pattern updates/changes/iterations have been discussed with the component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern maintainer
- [x] The component’s motion matches the specifications set by the pattern maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can be used
- [x] Changing props in the Storybook updates the component

**Comment by sydrosa** [comment]
- [ ] Add `Tooltip` to the simulated error toggle so that users know when the inline notification will appear
- [ ] Use low contrast for the inline notification
- [ ] Add documentation for using our classnames for styling
- [ ] Remove 'custom' in radio buttons

**Comment by andrea-gm** [comment]
- [ ] there's double scrollbars in the second story
- [ ] the bottom should have some spacing that is equal/similar to spacing above the "Core configuration" title
- [ ] For the "with Section" stories of Create Full page and Tearsheet, implementation of forms is inconsistent, like the html
- [ ] The spacings above/below the forms look inconsistent in Create tearsheet and full page. Confirm this is intentional?

**Comment by andrea-gm** [comment]
the double scrollbars seem to appear only at wider screen sizes? not sure what's going on there

**Comment by andrea-gm** [comment]
Looks good to me. 

Only comment is the fact that we don't have proper guidance for form fields on the grid, so a follow up is needed there to ensure we are displaying best design standards.
