### ISSUE TITLE
Create playground with multiple animated components

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#1115]
Something similar to Ruben's video

**Comment by andrea-gm** [comment]
https://user-images.githubusercontent.com/14081333/128216341-647817d4-6bef-4edb-8f17-4507f93f6405.mov

**Comment by lee-chase** [comment]
Completed and available here

https://carbon-for-ibm-products.netlify.app/?path=/story/overview-examples--playground
