### ISSUE TITLE
HTTPOtherError component of the React version does not show text in dark mode

### ISSUE THREAD

**Issue by Mikadv** [carbon-design-system/ibm-cloud-cognitive#1150]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

We want to utilize the `HTTPErrorOther` react component of `@carbon/ibm-cloud-cognitive`. It works great in gray 10 or any other light theme. But once a user switches to a dark theme like gray100 only the title is readable and got the correct color, whereas the subtitle and the description has not color assigned and renders as black text on black background:

![image](https://user-images.githubusercontent.com/49228392/129338082-2ac2b2e5-7b8d-4b7d-953e-7cbf5ce3a231.png)

![image](https://user-images.githubusercontent.com/49228392/129338116-f70c279f-d439-41f0-b114-715a4f8ab10d.png)

> What version of the @carbon/ibm-cloud-cognitive packge are you using?

"@carbon/ibm-cloud-cognitive": "^0.69.5"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Cloud Pak for Data ->WKC Workflow

## Steps to reproduce the issue

1. Step one - Include the component and set a title, subtitle and description
2. Step two - Apply the gray_100 carbon theme.
3. Step three - See the result.

When looking into the developer console it looks like that the title got a color with the correct tokens set, but the other text areas not. Hence, only the title gets correctly styled.

**Comment by matthewgallo** [comment]
Hey @Mikadv! This should be fixed now in `@carbon/ibm-cloud-cognitive@0.69.7`. Feel free to reopen if you still see this issue after upgrading.
