### ISSUE TITLE
Setting a custom prefix does not work

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1154]
## What package(s) are you using?

- [X] Cloud & Cognitive

## Detailed description

> Describe in detail the issue you're having.

In code sandbox, we should be able to set a custom prefix in the config.js file. The prefix does get added to all of the class names, however, none of the styles get added when the custom prefix is set.
> Is this issue related to a specific component?

Configuration
> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected all of the styles to still work when using a custom prefix
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-cloud-cognitive packge are you using?

Latest
## Steps to reproduce the issue

1. Create a code sandbox
2. In the `config.js` file, add this to set the custom prefix `pkg.prefix = "my-custom-prefix";`
3. Now you should be able to see that the styles are broken/do not get applied in the way you would expect

**Comment by lee-chase** [comment]
@matthewgallo did you change the CSS prefix and load the SCSS styles.

https://codesandbox.io/s/examplecomponent-prefix-test-3ss0i?file=/src/_ibm-cloud-and-cognitive.scss

**Comment by dcwarwick** [comment]
setting prefix in code and scss does now work, and we changed the prefix as part of the v1 release.
