### ISSUE TITLE
[SidePanel]: Scrolling can cause title to get stuck between normal and condensed size

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#1156]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When the panel height is just large enough to need scrolling, but too short to allow the full scrolling effect of condensing the title size, the title will appear in an in-between state when scrolled to the bottom.

Should the title be able to stay in this state?

## Steps to reproduce the issue

1. In Storybook SidePanel, adjust the height of your browser window until just a little scrolling is required. This is easiest for the story "Panel with Second Step"
2. Observe the title size not being fully condensed

## Additional information

https://user-images.githubusercontent.com/3118961/129398764-3f1b4b12-d4e4-4f87-8d82-b54e75bec14c.mov

**Comment by matthewgallo** [comment]
Hey @lily-peng, this has been addressed in #1222 and has been released in `@carbon/ibm-cloud-cognitive@0.79.1`
