### ISSUE TITLE
CreateTearsheet Influencer enhancement - 320px

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#1157]
There is a new variation of the Create Tearsheet Wide component where the left side influencer is 320px wide as opposed to the current 256px width. 

This will affect the `CreateInfluencer` component. Perhaps we can add an `influencerSize` or `size` prop that defaults to "sm" but has the ability for "lg" (320px)

**Comment by sydrosa** [comment]
Adding you @matthewgallo in case you're already working on this component. Otherwise, I can get to it in a bit!

**Comment by matthewgallo** [comment]
These changes won't need to touch `<CreateInfluencer />` at all since we can just pass the `influencerWidth` prop to the main create components (either CreateFullPage or CreateTearsheet).

**Comment by matthewgallo** [comment]
Since the `influencerWidth` prop can just be passed to the `Tearsheet` component. It will have to be handled slightly differently in CreateFullPage, but you could use the same prop type for that prop

```jsx
influencerWidth: PropTypes.oneOf(['narrow', 'wide']),
```

then in CreateFullPage add a class that sets the corresponding width to the element that wraps the influencer.

**Comment by sydrosa** [comment]
As a followup -- this enhancement should only be applied to `CreateTearsheet`.

**Comment by matthewgallo** [comment]
The `influencerWidth` prop will be added to the `CreateTearsheet` component in this [PR](github.com/carbon-design-system/ibm-cloud-cognitive/pull/1159)

**Comment by matthewgallo** [comment]
This is complete now and the `influencerWidth` prop can be toggled in storybook to see the `narrow` or `wide` versions on the CreateTearsheet. We can repoen this if/when CreateFullPage has this requirement
