### ISSUE TITLE
ProductiveCard Component overflowActions menu direction issue

### ISSUE THREAD

**Issue by Nishi-Chandra1** [carbon-design-system/ibm-cloud-cognitive#1176]
@davidmenendez  The default nature of overflowActions prop in C&CS ProductiveCard component is…
if the actionsPlacement=‘bottom’ , then menu items will open in upwards direction, and if actionsPlacement=“top” menu items will open in downward direction. 
If design requirement is to open menu items in downward  direction with actionsPlacement=‘bottom’. ,
there should be one option to change the menu item direction according to users need. i.e 'top' or 'bottom'

**Comment by davidmenendez** [comment]
hey @Nishi-Chandra1 thanks for opening up this issue. i believe that the original design specs specified that the overflow menus open in these directions when in each respective position. maybe @johanna-koval would like to comment on this further, but i believe this is working as intended.

**Comment by johanna-koval** [comment]
Hi @Nishi-Chandra1 could you provide more information on why the user needs to have the menu opening downwards?
We defined the direction based on products that were already using the bottom placement of the overflow in cards, one of the main reasons is to keep the overflow menu within the card context and avoid having it overlapping on other cards of components in the UI.

**Comment by davidmenendez** [comment]
@Nishi-Chandra1 is this still an issue for you?

**Comment by Nishi-Chandra1** [comment]
@davidmenendez No, we have changed overflowActions to actionIcons. Not required this fix now. Thank you.
