### ISSUE TITLE
[SidePanel]: Add tooltip for toolbar buttons & add className and/or id to buttons

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#1177]
## What will this achieve?

The SOAR team suggests the following enhancements to the SidePanel component to facilitate our designs:

1. Add the ability for tooltips on hover to the buttons in the SidePanel toolbar
2. Add the field(s) `className` and/or `id` to the toolbar buttons

## Additional information

The image below shows our design using the SidePanel. We'd like a tooltip to display upon hovering a toolbar button, and the ability to set a `className` and/or `id` to each button can achieve the red background

![sidepanel-tooltip-bg](https://user-images.githubusercontent.com/3118961/130112017-8af51411-f3ca-4236-825f-f98962ef9971.png)

**Comment by matthewgallo** [comment]
This is now complete @lily-peng, just a heads up that the click handler for the actionToolbarButtons has been renamed to simply `onClick`.
