### ISSUE TITLE
SidePanel header "jumps" downwards briefly at start of exit animation

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1204]
I spotted this remaining tiny glitch while checking out #1193. That mostly looks good, but I can still see a brief jump whwen the side panel is closed. Sorry!

It's an *extremely* brief jump, and you have to watch really closely to see it. I found it easier to see by editing SidePanel.js and setting moderate02 to '4000ms' or similar, but even so the jump is very brief and immediately returns to where it should be. It appears that the whole header area moves down over the subtitle just for one animation frame.

I have managed to catch it on a screen recording:
https://user-images.githubusercontent.com/6385315/130881793-f3485e0f-ab98-4433-b2c8-3050a27927b4.mov

About two-thirds of the way through this video, notice that this frame:
<img width="801" alt="Screenshot 2021-08-26 at 01 36 54" src="https://user-images.githubusercontent.com/6385315/130881889-6db4d42f-7417-4695-bf9b-df9f1192ee3f.png">
is followed by this frame which shows the "jump" in place:
<img width="845" alt="Screenshot 2021-08-26 at 01 38 17" src="https://user-images.githubusercontent.com/6385315/130881963-a26802db-cec0-412b-86f2-962999d07a4b.png">
and then that is followed by this frame which shows the "jump" has happened and the header has returned to its proper place during the rest of the exit motion:
<img width="801" alt="Screenshot 2021-08-26 at 01 38 34" src="https://user-images.githubusercontent.com/6385315/130882004-a7ac8e26-f1b5-4cc2-9611-2c2b9e15bc22.png">

**Comment by matthewgallo** [comment]
Fixed
