### ISSUE TITLE
CreateTearsheet: release review (dev)

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1211]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to main.
- [x] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic)  — @SimonFinney

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [x] The UI produced is:
  - [x] Accessible — @SimonFinney
  - [x] Responsive — @SimonFinney 
  - [x] Translatable
  - [x] Cross-browser
  - [x] Responds to the currently set Carbon theme — @SimonFinney 
- [x] Components are functional components using hooks — @SimonFinney
- [x] Public components which produce DOM structures support className  — @SimonFinney
- [x] Public components support a ref (via React.forwardRef)  — @SimonFinney
- [x] Public component supports a [Devtools attribute](https://github.com/carbon-design-system/ibm-cloud-cognitive/search?l=JavaScript&q=devtools&type=)  — @SimonFinney
- [x] All significant DOM elements have meaningful classes  — @SimonFinney
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes  — @SimonFinney
- [x] No warnings, errors or log messages in the consol  — @SimonFinney
- [x] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js  — @SimonFinney
- [x] Each public component SCSS lists all of the Carbon and C&CS components imported and used by the JavaScript code and explicitly imports the SCSS for each of these component  — @SimonFinney

### Standards

- [x] No linter warnings or errors are produced — @SimonFinney
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise — @SimonFinney
- [x] All components utilizing motion must include reduced-motion queries for accessibility purposes — @SimonFinney
- [x] Code is formatted according to Prettier rules (no use of `prettier-ignore`) — @SimonFinney
- [x] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the appropriate years — @SimonFinney

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output — @SimonFinney

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by SimonFinney** [comment]
> Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes

@matthewgallo Should subcomponents, like `CreateTearsheetDivider` for example, also be supporting. additional `...rest` props?

**Comment by matthewgallo** [comment]
Thanks for the review @SimonFinney! I have a [PR](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1233) to address the items you pointed out.

**Comment by matthewgallo** [comment]
The Section component was not exported intentionally, this was used in a previous version of the component but we have since chose a different design/implementation (but we've kept the component in case we use it again down the road). 

Another thing to note, is that I left out the rest props from `CreateTearsheetStep` intentionally as well, because some of the props are accessed from `CreateTearsheet` as `child.props.disableSubmit` for example. These props that aren't "used" within the CreateTearsheetStep end up getting added as html attributes if I have `{...rest}` on the `CreateTearsheetStep`.

**Comment by matthewgallo** [comment]
@andrea-gm commented [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1085#issuecomment-911927313) giving design approval

**Comment by davidmenendez** [comment]
everything looks good to me. my only small nitpick is that there's a few instances of using `let` for arrays. they should be `const`. you can still use operations like `push` on array constants.

my only other thought is a philosophical one. there's a lot of code here that's being used to determine that the user is properly setting the children and using the correct sub-components. *personally*, i feel like this is a lot of unnecessary effort. not to say it's not well coded or anything, but i don't think we need to be breaking our backs and hand holding the user to such great lengths. as long as the documentation is adequate I don't think it's necessary to add all these checks. but that's just my opinion.

**Comment by matthewgallo** [comment]
Talked with @davidmenendez over slack, I'll submit another PR next week to refactor some of the `let`s.

**Comment by SimonFinney** [comment]
> everything looks good to me. my only small nitpick is that there's a few instances of using `let` for arrays. they should be `const`. you can still use operations like `push` on array constants.
> 
> my only other thought is a philosophical one. there's a lot of code here that's being used to determine that the user is properly setting the children and using the correct sub-components. _personally_, i feel like this is a lot of unnecessary effort. not to say it's not well coded or anything, but i don't think we need to be breaking our backs and hand holding the user to such great lengths. as long as the documentation is adequate I don't think it's necessary to add all these checks. but that's just my opinion.

@davidmenendez Based on your review, can you confirm which tasks from [the list above](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1211#issue-980536459) we can mark as complete?

**Comment by matthewgallo** [comment]
> legend missing for fieldset in 'Meta data' section of 'Create tearsheet with sections' story

Updated [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1233/commits/0b85b1ddc50673306bdaf1c23a0b82f9fe6b1886)

**Comment by matthewgallo** [comment]
Complete
