### ISSUE TITLE
PageHeader tags do not support different tooltip text

### ISSUE THREAD

**Issue by eRadiofan** [carbon-design-system/ibm-cloud-cognitive#1223]
We have a requirement to display a shortened ID in the tag but then display a long ID in the tooltip. The shortened version is not a simple truncation, we have a special function for producing it. PageHeader does not currently support this.

- enhancement

## How will success be measured?

This enhancement will be successful when it is possible to pass in a tooltipText attribute as part of each tag and have it display in the tooltip independently of the tag text

## Additional information

- Designs

**Comment by lee-chase** [comment]
@eRadiofan please share design links if possible.

**Comment by lee-chase** [comment]
@eRadiofan Carbon have asked for designs, without it they will likely close the issue.

**Comment by lee-chase** [comment]
When Carbon implement 9587 then as props are passed through it will be available in page header as a result. Hence closing this issue.
