### ISSUE TITLE
[SidePanel] should not let the background scroll.

### ISSUE THREAD

**Issue by dkaushik95** [carbon-design-system/ibm-cloud-cognitive#1239]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
When you have a SidePanel with a background which is scrollable, the scrolling isn't disabled when `includeOverlay` prop is true.

> Is this issue related to a specific component?
SidePanel

> What did you expect to happen? What happened instead? What would you like to
> see changed?
With `includeOverlay` I would like to disable background scrolling just like in a `Modal` component. 

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-cloud-cognitive packge are you using?
`^0.81.1`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
`WAIOps 3.2`. Not a stop ship but a quick fix would be ideal. 

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/brave-boyd-9zybp?file=/src/App.js

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
This issue should be fixed in release `@carbon/ibm-cloud-cognitive@0.82.1`

Resolved via https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1238
