### ISSUE TITLE
Need enhancement in primaryButtonText prop of ProductiveCard component

### ISSUE THREAD

**Issue by Nishi-Chandra1** [carbon-design-system/ibm-cloud-cognitive#1243]
@davidmenendez , johanna.koval@ibm.com. 
My design requirement is to give a checkmark next to the primaryButtonText string. But when i am using Checkmark16 inside primaryButtonText prop. Its giving me warning , "Failed prop type: Invalid prop `primaryButtonText` of type `object` supplied to `Card`, expected `string`."  since this prop accepts only strings not objects. There should a provision of accepting any icons along with the Ghost Button inside primaryButtonText prop.
Here is the code snippet i am using 

const App = () => {
  const defaultProps = {
    title: "Title",
    children: (
      <>
        <div className="graph" />
        <p>Productive content text 1</p>
        <p>Productive content text 2</p>
      </>
    ),
    actionIcons: [],
    primaryButtonText: (
      <div>
        <span>Activate Profile</span>
        <span>
          <Checkmark16 />
        </span>
      </div>
    )
  };
  return (
    <div className="App">
      <ProductiveCard {...defaultProps} />
    </div>
  );
};
export default App;

**Comment by davidmenendez** [comment]
This would be a very easy feature to add. here it is on my local environment

<img width="358" alt="Screen Shot 2021-09-07 at 1 49 10 PM" src="https://user-images.githubusercontent.com/6370760/132403226-6a9168f3-cedd-4f2d-8ebf-9c3fd04b03f0.png">

I just need design approval to implement

**Comment by Nishi-Chandra1** [comment]
Here is the screenshot of error which i am getting when trying to implement custom DOM element inside primaryButtonText prop of ProductiveCard
<img width="1790" alt="Screenshot 2021-09-30 at 9 25 03 PM" src="https://user-images.githubusercontent.com/80027651/135490148-e7119929-c70d-4369-88a2-22aa49d307f5.png">
:
here is the code :  primaryButtonText={ <div><span>Activate Profile</span><span><Checkmark16 /></span></div> }

**Comment by Nishi-Chandra1** [comment]
similar issue is there if i am trying to add a plus icon along with pageHeader actionItems.

**Comment by davidmenendez** [comment]
sorry for the late response.

tagging @johanna-koval for design approval

**Comment by johanna-koval** [comment]
Looks good to me!

**Comment by davidmenendez** [comment]
@Nishi-Chandra1 apologies for how long this took, but the change is now merged in and in the latest version of the library 👍
