### ISSUE TITLE
Specify sideEffects in package.json required for correct tree shaking with Webpack

### ISSUE THREAD

**Issue by szaflarskim** [carbon-design-system/ibm-cloud-cognitive#1250]
## What will this achieve?
Correct tree shaking when importing components as `import { SidePanel } from '@carbon/ibm-cloud-cognitive'`.

Currently tree shaking does not work with Webpack because sideEffects are not defined in package.json and import of a component bundles carbon-components-react. 
Workaround is to import each component in a form `import { SidePanel } from '@carbon/ibm-cloud-cognitive/es/components/SidePanel';`

**Comment by szaflarskim** [comment]
Verified correct tree shaking with `@carbon/ibm-cloud-cognitive@0.85.1`.

**Comment by dcwarwick** [comment]
Excellent! Thanks @szaflarskim
