### ISSUE TITLE
Investigation: DataTable - Cloud PAL Datatable, WKC Data Grid, and C&CS Datatable extensions

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#1261]
## What will this achieve?

The goal is to have a datatable that has all the functionality outlined in C&CS datatable extensions pattern.

- [ ] Let's determine if we can leverage Cloud PAL's datatable implementation, which is in theory (Andrea was told) modular and extensions can easily be plugged in.

- [ ] Evaluate WKC Data Grid

Would also be good to try to size the full effort.

- [ ] Should this be built as one massive component or separate components? Considering extensions may change in the future.
- [ ] Can we create a prioritized list of the extensions from most to least feasible?
- [ ] Will this component be contributed to Carbon? Will Carbon's data table still exist?
- [ ] Do we need to build this based on the carbon component or create our own?
- [ ] Will Carbon continue to support the base data table?
- [ ] ...

## How will success be measured?

We will have a clear picture of our options and formulate a plan that will be presented to DSIT.

## Additional information

https://pages.github.ibm.com/ibmcloud/pal/components/data-table/code

https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview

**Comment by JoannaJanusz** [comment]
As per discussion today with @andrea-gm et al, adding information about one more potential data grid component which could be of use: https://pages.github.ibm.com/wdp-gov/wkc-shared-ui/?path=/story/datagrid--basic-usage
Relevant code can be found in the internal repo https://github.ibm.com/wdp-gov/wkc-shared-ui/tree/master/src/components/datagrid
