### ISSUE TITLE
Shadow appearing in the about modal in safari

### ISSUE THREAD

**Issue by clairek20** [carbon-design-system/ibm-cloud-cognitive#1265]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Shadow appearing in the about modal in safari 

> Is this issue related to a specific component?

About modal

> What browser are you working in?
Safari

> What version of the @carbon/ibm-cloud-cognitive packge are you using?
0.42.2

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1265

**Comment by davidmenendez** [comment]
the fade was removed several months ago by @dcwarwick (https://github.com/carbon-design-system/ibm-cloud-cognitive/commit/267d30799c32fab32cbe3ef948884c197689bdf7#diff-8ecc83c17019408803e25dc6f72fd1017b8b8ab58e72642be39a361203ce2dcbL100) so if you update to the latest version of @carbon/ibm-cloud-cognitive the shadow should be gone entirely.

**Comment by davidmenendez** [comment]
@clairek20 can you please verify if this issue has been resolved? if so would you mind closing the issue? thanks!

**Comment by clairek20** [comment]
@davidmenendez it is resolved now, thanks very much for the help!
