### ISSUE TITLE
[SidePanel]: Allow toolbar buttons to be disabled

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#1268]
## What will this achieve?

An enhancement we'd like to see for the SidePanel is a prop for `actionToolbarButtons` to set the button as enabled or disabled. This should also not allow the user to click on the button, but should allow showing a tooltip in this state.

## Additional information

Our design is for a toolbar button to be disabled. It should appear disabled, without the button pointer cursor, disable clicking the button, and still be able to show a tooltip on hover.

**Comment by matthewgallo** [comment]
Hey @lily-peng, this is something that can currently be done. The prop `actionToolbarButtons` is an array of objects (that get turned into buttons), simply add `disabled: true` to the button you want to disable. For example:

```jsx
actionToolbarButtons={[
      {
        leading: true,
        label: 'Copy',
        icon: Copy20,
        onClick: action('Toolbar button clicked: Copy'),
        kind: 'primary',
        disabled: true
      },
      {
        label: 'Settings',
        icon: Settings20,
        onClick: action('Toolbar button clicked: Settings'),
      },
      {
        label: 'Delete',
        icon: Delete20,
        onClick: action('Toolbar button clicked: Delete'),
      },
    ]
}
```
