### ISSUE TITLE
Loosening PageHeader restrictions proposal

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#1283]
## What will this achieve?

The PageHeader restricts content by only allowing the user to pass properties or arrays of properties in for some parts:
- actionBarItems
- breadcrumbs
- pageActions
- tags

Note that `navigation` is open expecting `PropTypes.element`

The current implementation of the restricted items is:
- actionBarItems is an array of shapes passed to ActionBar which renders more than one element per item for resizing. ActionBar reports width change.
- breadcrumbs are passed to BreadcrumbWithOverflow which renders more than one element per item for resizing.
- pageActions are used twice in the page header (breadcrumb row and title row), both passed to ActionBar which renders more than one element per item for resizing.
- tags are passed to a TagSet which renders more than one element for resizing, use in an overflow and modal show all. A text version is needed for the overflow, Carbon sometimes uses a method called `itemToString` which defaults to `label`

In each case the overflow menu renders a slightly different format in the overflow menu.

## Loosening options

Instead of the current array of strict shape e.g. [ { currentShape }, ... ]

### Shape or element

1. [ PropTypes.oneOfType( [{ currentShape }, PropTypes.element ] ), ... ]

PropTypes.node is not suggested here as the resizing components will need to create clones for resizing.

This is scenario problematic for overflow where a separate overflow format is needed. In the case of the TagSet this could be fixed by requiring the element to implement or support an `itemToString` method. 

### Shape or multiple elements

2. [ PropTypes.oneOfType( [{ currentShape }, { element, overflowElement, ... } ]

Allowing separate elements to be passed for the various use cases e.g. overflow, small, smallOverflow could work and saves the user the need to monitor resize events. This may also negate the need for a `itemToString` method.

### Shape or element and onResize

3. [ PropTypes.oneOfType( [{ currentShape }, { element, onResize } ]

This would require a `itemToString` method or similar. In addition the user must handle onResize and update element accordingly.

### Whole thing as element

Instead of replacing individual shapes, allow the whole set/array to be replaced. The following PropTypes declarations map to the options above with similar requirements.

4. PropTypes.oneOfType( [ [{ currentShape }, ...], PropTypes.element ] )
5. PropTypes.oneOfType( [ [{ currentShape }, ...], { element, overflowElement, ...} ] )
6. PropTypes.oneOfType( [ [{ currentShape }, ...], { element, onResize} ] )

### Use render functions

Render functions could be used instead of PropTypes.element. This would be like the Carbon implemention of button icon.  

7. PropTypes.oneOfType( [ [{ currentShape }, ...], PropTypes.func ] )
8. PropTypes.oneOfType( [ [{ currentShape }, ...], { func, overflowFunc, ...} ] )
9. PropTypes.oneOfType( [ [{ currentShape }, ...], { func, onResize} ] )

## How will success be measured?

- The queries raised in #1062 will have been addressed.
- Updates to the PageHeader design planned by @cameroncalder are taken into account

## Additional information

- Designs - pending update https://pages.github.ibm.com/cdai-design/pal/components/page-header/usage

**Comment by sydrosa** [comment]
Can we add title to this so that title accepts a node instead of string?

**Comment by lee-chase** [comment]
#1355 also impacts on this

**Comment by lee-chase** [comment]
Started this work. Followed the pattern of current shape plus new shape with node and additional fields needed to support responsive/scroll behaviour.
