### ISSUE TITLE
PageHeader: Title doesn't append to top in smaller screen sizes

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#1304]
## PageHeader: Title doesn't append to top in smaller screen sizes

- [x] Cloud & Cognitive

## Detailed description

> At smaller screens, the PageHeader title does not append to the bar, so you're unable to see it when scrolling.

> Is this issue related to a specific component?
PageHeader

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expected to see the title in Pageheader to the right of the breadcrumb when scrolling

> What browser are you working in?
Firefox

> What version of the @carbon/ibm-cloud-cognitive packge are you using?
`"@carbon/ibm-cloud-cognitive": "^0.83.1",`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Cloud Pak for Data, not super urgent just yet.

## Steps to reproduce the issue

1. Go to the code sandbox
2. Set your screen width to less than 850
3. Scroll down and check out the pageheader title. It's gone

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/pageheaderexample-rs5ie

![pageheader](https://user-images.githubusercontent.com/47571589/135508359-01961f01-697d-43a2-ba17-abda55a787f2.gif)

**Comment by lee-chase** [comment]
This has been resolved.
