### ISSUE TITLE
[SidePanel]: Initial title size does not change when props update

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#1328]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Since the latest update to 0.91.4, our previous scrolling issue is resolved but a new one is occurring. We have a SidePanel with the props changing depending on user input. When we update props, the title size will change to accommodate for smaller/larger titles. But after scrolling the panel first, the size of the title now stays the same, which clips large titles and/or adds space to short titles. It can even cause scrolling to bug out for a bit.

## Steps to reproduce the issue

**Reduced test case in CodeSandbox:**
> https://codesandbox.io/s/ibm-cloud-cognitive-sidepanel-forked-3stnt?file=/src/App.tsx

1. Open SidePanel 1, scroll the panel down, then back to the top
2. Open SidePanel 2 , observe the additional empty space, and when you try to scroll, the behavior is bugged

Refresh, and try:

1. Open SidePanel 2, scroll the panel down, then back to the top
2. Open SidePanel 1, observe the title is clipped, and when scrolling down and back to the top, the title section is squashed together

- Observe that the bugs do not occur if you don't scroll the panel first
- The bugs occur with and without subtitles (going from a short title to long title may cause the subtitle to get clipped out of the long title)

## Additional information

https://user-images.githubusercontent.com/3118961/137021578-24419d3c-3b56-4584-9daf-249344b91a5f.mov

https://user-images.githubusercontent.com/3118961/137021805-04ae2545-2d40-42f2-87f4-116102bea6cb.mov

https://user-images.githubusercontent.com/3118961/137021713-52a679dd-fa82-4ce4-bb05-84f9c334caba.mov

**Comment by matthewgallo** [comment]
Hey @lily-peng, this issue should be resolved now in `@carbon/ibm-cloud-cognitive@0.97.2`. I made sure to reset the necessary custom css properties and scroll the panel to the top if the `size` prop changed while the panel is open. Let me know if you still see issues with this after picking up the latest version!
