### ISSUE TITLE
[SidePanel] We need to pass data-testid (and other custom props) to actionToolbarButtons

### ISSUE THREAD

**Issue by deandra-smith** [carbon-design-system/ibm-cloud-cognitive#1358]
## What will this achieve?
this is will make unit test easier to write for props and/or custom props for side panel.

## Additional information

- Designs
- Existing code
- etc

**Comment by matthewgallo** [comment]
Hey @deandra-smith, this capability has been added to the latest relase (`@carbon/ibm-cloud-cognitive@0.97.0`). Let us know if you have any issues.
