### ISSUE TITLE
Enhancement: Component to follow the add pattern

### ISSUE THREAD

**Issue by tomleah** [carbon-design-system/ibm-cloud-cognitive#1359]
## What will this achieve?

The idea would be to have a modal that standardises the "add" pattern similar to what has been created for the "create" pattern.

[Carbon guidance](https://www.carbondesignsystem.com/community/patterns/create-flows/#add) mentions that add is similar to the create pattern, however the create modal is limited to the small modal variant. When using it for adding there is not enough space to view the content so a wider modal is required. 

Our original thought would be to expand the capabilities of CreateModal to allow for larger sizes, but the component should follow a defined "Add" pattern rather than assuming it would be the same as Create.

## How will success be measured?

Be able to use a component that follows the guidelines for "add" out of the box. The developer ideally would only supply the data to be used in the component.

## Additional information

- Designs
- Existing code
- etc

**Comment by davidmenendez** [comment]
@tomleah are there designs to support this? i checked that link you provided and it's nothing more than a few bullet points.

**Comment by davidmenendez** [comment]
sounds like we're still waiting on design to finalize the pattern @andrea-gm

**Comment by lee-chase** [comment]
@tomleah closing this issue pending design update, feel free to re-open.
