### ISSUE TITLE
Custom CreateTearsheetSteps not working with hooks and props

### ISSUE THREAD

**Issue by juanc-flores** [carbon-design-system/ibm-cloud-cognitive#1364]
## What will this achieve?
Last [release](https://github.com/carbon-design-system/ibm-cloud-cognitive/releases/tag/%40carbon%2Fibm-cloud-cognitive%400.97.0) has enabled the ability to create custom tearsheet steps to separate logic among steps. But when using this new feat by creating a flow where depending what a user selected in a previous step or the pre-create pattern, the next steps change dynamically. This works fine but some things started to come up:

1. When hooks are inside the custom steps it breaks (image 1). This is more a react related issue but it would be helpful if there were a workaround to deal with it. The way that this could be done is if there were a prop to enable o disable steps so that they are always there and the hooks order won't change.
2. Custom steps are not able to receive custom props throwing an error about `_ref.MyProp` is not defined (image 2).
3. Lastly, even if the scenario doesn't use dynamic rendered steps or pass down props the custom components are still not able to use hooks, it warns me that they're breaking the rules of hooks.

## Additional information
image 1

![image](https://user-images.githubusercontent.com/88340007/139941103-4bfebde8-a88b-4e8f-9ad2-10116d65dbe1.png)

image 2
![image](https://user-images.githubusercontent.com/88340007/139966057-4a129673-8227-495e-a461-e167207eca2e.png)

**Comment by ninjasun** [comment]
plucker here
[https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1512](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1512)

**Comment by ninjasun** [comment]
pluck here [https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1511](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1511)

**Comment by matthewgallo** [comment]
#1524 has been merged and the fix for this issue will be included in our next release. Reopen if you have any further issues!
