### ISSUE TITLE
How should we make shallow wrappers?

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#138]
Some of our components either are shallow wrappers around Carbon React components or make use of shallow wrappers. 

There are a number of ways to create a shallow wrapper in Rect which involve more or less lines of code depending on how many of the wrapped components properties you want to explicitly support.

One minimalist approach is as follows but is this the best way or sub-optimal? 

Create your preferred pattern using this [CodeSandbox](https://codesandbox.io/s/wrapped-buttons-qk17v)

```js
import React from 'react';
import cx from 'classnames';
import { Button } from 'carbon-components-react';
import { expPrefix } from '../../global/js/settings';
const blockClass = `${expPrefix}-page-action-item`;
export const PageActionItem = ({ children, ...props }) => {
  const className = cx([blockClass, props.className]);
  return (
    <Button
      {...{
        ...props,
        className,
        size: 'field',
        type: 'button',
      }}>
      {children}
    </Button>
  );
};
// Props the user cannot change
const reservedProps = ['size', 'type'];
// Base props on Carbon Button
const propTypes = { ...Button.propTypes };
const defaultProps = { ...Button.defaultProps };
// Remove reserved props
reservedProps.forEach((prop) => {
  delete propTypes[prop];
  delete defaultProps[prop];
});
PageActionItem.propTypes = { ...propTypes };
PageActionItem.defaultProps = { ...defaultProps };
```

**Comment by dbrugger** [comment]
@lee-chase i like the approach taken here to be inclusive of the base props minus some few that are explicitly defined. one thought on the mechanism: instead of a for loop that deletes the unneeded props, could try not to include them when making a deep copy with the spread: `const { notNeeded1, notNeeded2, ...propTypes } = { ...Button.propTypes };`

**Comment by lee-chase** [comment]
> @lee-chase i like the approach taken here to be inclusive of the base props minus some few that are explicitly defined. one thought on the mechanism: instead of a for loop that deletes the unneeded props, could try not to include them when making a deep copy with the spread: `const { notNeeded1, notNeeded2, ...propTypes } = { ...Button.propTypes };`

Yes, that works but means having to disable eslint e.g.  // eslint-disable-next-line no-unused-vars

**Comment by SimonFinney** [comment]
This pattern makes sense to me, although I'm curious as to how the Storybook output will look like for this? Further down the line, I suspect we can also pull this into a `global` helper should the need arise for a pattern like this again.

**Comment by lee-chase** [comment]
> This pattern makes sense to me, although I'm curious as to how the Storybook output will look like for this? Further down the line, I suspect we can also pull this into a `global` helper should the need arise for a pattern like this again.

Storybook does not currently help when using this pattern. We have to declare prop-types and defaults, but only for the values we want to use in a storybook. The documentation can point at carbon for other properties.

**Comment by SimonFinney** [comment]
Great! It sounds like the model could be something like the following:

1. Remove Carbon properties being explicitly set in the shallow wrapper from `propTypes`, and `defaultProps`
2. Define unique properties for documentation in `propTypes` and `defaultProps` declarations
3. Point to parent Carbon documentation for a full list of 'inherited' properties
4. Indicate in the documentation that explicitly-set properties from Carbon are not available as part of the API

What else should be considered?
