### ISSUE TITLE
Ensure all references to Carbon prefix use appropriate variables

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1387]
We currently use `.bx--` extensively to refer to Carbon classes. All these references should be updated to use the Carbon prefix variables, as currently we will not work alongside Carbon when the default Carbon prefix is changed.

This change should be made ASAP, but is not essential for V1 since it won't actually change any output.

**Comment by lee-chase** [comment]
I believe this to be resolved.
