### ISSUE TITLE
Update package name and descriptions to ibm-products from ibm-cloud(-and)-cognitive

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1422]
- [x] Publish @carbon/ibm-cloud-cognitive as @carbon/ibm-products, with identical content and matching versions. Later, we can deprecate @carbon/ibm-cloud-cognitive, and eventually remove it when nobody is using it any more.
- [x] Change documentation and titles to refer to the library as Carbon for IBM Products and remove mention of Cloud & Cognitive etc.

**Comment by davidmenendez** [comment]
@dcwarwick is this complete?

**Comment by dcwarwick** [comment]
I've created ongoing issues to rename the repo and the package directory. Other than that, this is complete.
