### ISSUE TITLE
Clean the input field when close the RemoveModal

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1426]
## What package(s) are you using?

- [ x] Cloud & Cognitive 0.97
- [ ] Legacy/CDAI
- [ ] Legacy/Security

How to access the input?
In case of cancel (but even on submit) the input field stays populated and looks like there is not a prop I can set.

https://codesandbox.io/s/remove-modal-3wcmu?file=/src/components/TestComponent.js

Thanks for support

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1433

**Comment by ninjasun** [comment]
@matthewgallo this is working, however, will be possible to clean the input field after the modal is closed?

Now is being instantly clean during the closing animation. Does not seem nice to me.
What is your opinion?
