### ISSUE TITLE
Inline Edit Component

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#1492]
# Inline Edit

## Brief description

Adds an inline/in-place edit

## Details

https://pages.github.ibm.com/cdai-design/pal/patterns/edit#inline-edit
![image](https://user-images.githubusercontent.com/15086604/144872604-cf179a5b-db8f-4be5-b074-cef0e8b67b72.png)

## Design Maintainer(s)

- @vikkipaterson 

## Tasks

Before starting work on this epic, please review and complete the following.

- [x] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [x] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [x] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [x] Did you use the CLI to scaffold your new component?

**Comment by lee-chase** [comment]
While this component is titled `Inline edit` it should be thought of as `In-place edit` to avoid confusion with both the DOM display term 'inline' and the Carbon TextInput option 'inline'.

Carbon Search uses an aria-label for the 'Clear search input' button. 
https://carbon-components-react.netlify.app/?path=/story/components-search--default

The design uses tooltips for 'Cancel/Revert' and 'Save'

The Carbon TextInput has 'inline', 'invalidText' and 'invalid' options. However it is not possible to see the `invalidText` when using the inline option. Carbon does not add the invalid message at all into the HTML.

![image](https://user-images.githubusercontent.com/15086604/144876874-2817591f-05bb-4181-8a0f-eaf1bfde1eab.png)
![image](https://user-images.githubusercontent.com/15086604/144877130-20da426d-69fb-48f9-b4f9-c4fda46d33f6.png)

As can be seen above, Carbon does allow the help text. Assuming this is also permitted for this design.

@vikkipaterson perhaps you can assist or suggest someone to assist with the following questions

1. Should we change the name to 'In-Place edit'?
2. How should we resolve the discrepancy with Carbon Search? [Do as Carbon does, suggest a change to Carbon, note in the design but disregard discrepancy]
3. How should we resolve the discrepancy with Carbon TextInput with inline and error message [Do as Carbon does, suggest a change to Carbon, note in the design but disregard discrepancy]
4. Should we support all TextInput properties such as helperText, hideLabel, light etc?

**Comment by lee-chase** [comment]
#1310 requires inline edit

Blocked, cannot be released until we understand how the above questions are resolved.

**Comment by lee-chase** [comment]
See 
- (search button tooltip) https://github.com/carbon-design-system/carbon/issues/10233
- (invalidMessage query) https://github.com/carbon-design-system/carbon/issues/10234

**Comment by sdignum** [comment]
Hi @lee-chase the label in the image example is not meant to be part of the component. As discussed, a label will be good to keep with the component in the code, but it will be up to the designer to decide if and how a label is associated with the value for the inline (or in place) edit scenario.

**Comment by lee-chase** [comment]
Thanks, @sdignum. How did the review of other issues go?

**Comment by lee-chase** [comment]
With regards to component state.

When not changed there is nothing to revert. I believe it would provide a better interaction to have the 'Save' button enabled, perhaps with an updated label and the 'Revert' button disabled.

**Comment by lee-chase** [comment]
@sdignum An edit button as suggested here https://pages.github.ibm.com/cdai-design/pal/patterns/edit/#inline-edit which is only discovered on tab or hover is not accessible.

**Comment by lee-chase** [comment]
@sdignum 
There are two types of validation possible for an edited field:
- Synchronous: e.g. format check, not empty, local validation.
- Asynchronous: e.g. back end call needed to check name clashes for instance.

In the synchronous case, it is likely we can wait for the validation.

In the asynchronous case:
- What should the UI do while waiting for validation?
  a. Show edit style disabled
  b. Show edit style enabled but with save/revert disabled
  c. Show non-edit style with edit button disabled
  d. Show non-edit style with edit button enabled
  e. Show any processing indicator?
  f. Other?
- When the validation returns invalid what should happen?
 a. Re-enable the edit state
 b. Move the users focus to the item in error?

**Comment by sdignum** [comment]
> With regards to component state.
> 
> When not changed there is nothing to revert. I believe it would provide a better interaction to have the 'Save' button enabled, perhaps with an updated label and the 'Revert' button disabled.

We're actually also thinking maybe it should be an "x" to cancel instead. That seems to be a common behavior elsewhere as well.

**Comment by sdignum** [comment]
> 

@lee-chase I don't think inline edit variation should be used for an asynchronous edit (they should use modal edit in that case instead). I will add that to the documentation. Unless you can think of a reason why we should allow for it on inline edit??

**Comment by sdignum** [comment]
@lee-chase  I will update the documentation, but please change the revert icon to the "x" and the tooltip to say "Cancel"...I don't think anything else about the behavior should change

**Comment by lee-chase** [comment]
@lee-chase  the edit icon and the edit disabled icon are not pleasing to switch between.  This is mostly because the pencils are different sizes and it looks like the icon jumps.

What do you think of this? https://codepen.io/lee-chase/pen/qBVNZog/5c1d3b69e235a38dfc6a500329ae9e44

It needs a bit of a rework of the icon, might even be worth asking Carbon to update the icon to enable use to do this.

**Comment by lee-chase** [comment]
Unblocking following 2px down adjustment to PageHeader to cope with the title being InlineEdit in but having no action bar.
