### ISSUE TITLE
AboutModal with scrolling content doesn't have the scroll fade-out

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1494]
See https://carbon-for-ibm-products.netlify.app/?path=/story/carbon-for-ibm-products-patterns-about-modal-aboutmodal--fully-loaded

![image](https://user-images.githubusercontent.com/6385315/145693778-bc23fbde-199d-434d-acea-4be5b4296cb3.png)

**Comment by davidmenendez** [comment]
i spent some time looking into this and i'm not 100% what to make of it. this is the css in question that's being used-

```
background-image: linear-gradient(to bottom, rgba(var(--cds-ui-01, #f4f4f4), 0), var(--cds-ui-01, #f4f4f4));
```

compared to the css that's being used on a standard carbon modal that I took from sandbox

```
background-image: linear-gradient(to bottom, rgba(244,244,244,0), #f4f4f4);
```

based on this [stackoverflow](https://stackoverflow.com/questions/59906693/why-cant-i-use-rgba-in-css-variable) it would appear that functions can't be passed to `rgba`. so i'm guessing that this is build problem on our end where the variables aren't just being evaluated to their normal values and it's causing issues with `rgba`.

thoughts?
