### ISSUE TITLE
Pass down props in customStep with CreateTearsheetStep

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1511]
Hello,

Creating a custom step that encapsulates the CreateTearsheetStep, it seems props get lost.

[https://codesandbox.io/s/stupefied-galileo-jhcvi?file=/src/MultiStepExample.js](https://codesandbox.io/s/stupefied-galileo-jhcvi?file=/src/MultiStepExample.js)

I'm running v 1.2.2 locally.

I'm expecting to be able to pass down any props.. or I miss some things.

thanks
Davide

**Comment by matthewgallo** [comment]
Hey @ninjasun, this issue will be resolved in our next release when https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1524 gets merged. We refactored how the CreateTearsheet/CreateFullPage track their steps which allows the custom steps to work as expected.

**Comment by matthewgallo** [comment]
This is now fixed with #1524 and will be included in the next release.
