### ISSUE TITLE
Issue with hooks on CreateTearsheetStep

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1512]
Hi,
I'm trying to use hook inside a custom step but it generates an error:
"Invalid hook call. Hooks can only be called inside of the body of a function component."

[codesandbox](https://codesandbox.io/s/unruffled-elgamal-2gdei?file=/src/MultiStepExample.js)

I think we should be able to use hooks inside a custom step, or I do not get how can I move some logic from CreateTearsheet to the step.
Can you help with that, please?

Thanks
Davide

**Comment by matthewgallo** [comment]
Hey @ninjasun, this issue (similar to #1511) will be resolved in our next release when #1524 gets merged. We refactored how the CreateTearsheet/CreateFullPage track their steps which allows the custom steps to work as expected.
