### ISSUE TITLE
Create Getting Started Layout

### ISSUE THREAD

**Issue by skamath2000** [carbon-design-system/ibm-cloud-cognitive#1515]
# GettingStartedModule

## Brief description

Design for IBM Security has shown an interest in creating a consistent Getting Started page layout design using Layout Modules. 

## Details

[Link to Design](https://ibm.invisionapp.com/share/UVO1C8FK5WE)

### Links to other materials

![image](https://user-images.githubusercontent.com/45520982/148309636-38ee08c0-3c3d-4d77-821e-230de78573c6.png)
![image](https://user-images.githubusercontent.com/45520982/148309658-db56befc-261f-4be8-9de9-89274ebac43f.png)

## Design Maintainer(s)

- Sarah Pedregon
- Cameron Calder

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by lee-chase** [comment]
Assuming this is for the Security package. If intended for IBM Products then please follow guidance here https://pages.github.ibm.com/cdai-design/pal/

**Comment by skamath2000** [comment]
@lee-chase Yes, this was for the security package.
