### ISSUE TITLE
Open prop to be added to OptionsTile

### ISSUE THREAD

**Issue by seonyukim** [carbon-design-system/ibm-cloud-cognitive#1521]
## What will this achieve?

- enhancement: 
   - To sets the (initial) state of the openable/closable part
   - To enable the tile to be shown as open by default, or to open it in response to a user interaction elsewhere on the page if necessary.

## How will success be measured?
To check prop is added.

## Additional information

- Designs
- Existing code
- etc

**Comment by janhassel** [comment]
@dcwarwick  We might wanna standardize this concept across components with something like [Carbon's `useControllableState` hook](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/internal/useControllableState.js).

**Comment by elycheea** [comment]
@janhassel Opened a new issue for your suggestion. Feel free to add more detail or contribute/submit a PR.
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1540

**Comment by elycheea** [comment]
Forgot to close this. Included in 1.4.0 release.
