### ISSUE TITLE
Remove padding from Side Panel component

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#1522]
If the inner padding is removed from the side panel, the autofocus selection around items will align left to right of the content. Right now the autofocus cannot extend to the left-right beyond the margins. 

Please see this issue for more details: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51265

Navleen Johal walked through a potential solution once the padding is removed.
password: Gcw6HbmM
https://ibm.webex.com/recordingservice/sites/ibm/recording/9d5f3c3a554a103abf330050568ffafd/playback

**Comment by matthewgallo** [comment]
Hey @carrenelloyd, this would cause visual changes to all other users of the side panel. I was looking at the issue you included and you can achieve this with some small changes on your end.

Tell Navleen that all you need to do is give your accordion component a class. Then add the following css

```css
.accordion--container {
  margin: 0 -1rem;
  width: calc(100% + 2rem)
}
```
![Screen Shot 2022-01-19 at 11 09 03 AM](https://user-images.githubusercontent.com/10215203/150169775-ceadb20a-a073-415b-a0d5-3d831323e73b.png)

**Comment by matthewgallo** [comment]
If you or anyone on your team has more questions feel free to reopen!
