### ISSUE TITLE
Update and verify the code links to our storybook etc from the web site

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1532]
eg https://pages.github.ibm.com/syd/pal-1/components/page-header/code contains a link with an old URL (cloud-cognitive) and an old story name which no longer exists.

**Comment by lee-chase** [comment]
The first columns of the tables listing out the assets contain a mix of; links to design assets on the site, [CarbonDesignSystem.com](http://carbondesignsystem.com/) and links to coded assets in storybook. Not sure what they should be.

**Comment by lee-chase** [comment]
Addressed in https://github.ibm.com/CDAI-design/pal/pull/881
