### ISSUE TITLE
Add dynamic step into CreateTearsheet component

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1538]
Hi guys,

as @matthewgallo suggested, I'm opening a feature request for this as with the new implementation not sure about the way to get it.

we have a tearsheet with 4 steps and in the third step, the user can add custom fields. If so we need to show another step where those custom fields get configured.

Some points to note:
-  the new last step will have the 'submit' button
-  user should be able to 'go back' and remove any custom fields. This will remove the extra added step.

With the new imp[lementation/refactoring I should be able to use a state variable in the CreateTearsheet and pass it down to both my steps. Then simply doing `{ hasExtraStep && <MyExtraCustomStep fields={myExtraFields}} /> }` should work.

The thing I'm not sure about is the next button that will become a submit.

Gonna add a sandbox ASAP.
meanwhile very thanks.

**Comment by matthewgallo** [comment]
Hey @ninjasun, this is now available in [`@carbon/ibm-products@1.5.0`](https://github.com/carbon-design-system/ibm-cloud-cognitive/releases/tag/%40carbon%2Fibm-products%401.5.0). See the [new section](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-create-flows-createtearsheet--multi-step-tearsheet#using-dynamic-steps) in the create tearsheet storybook docs for usage examples
