### ISSUE TITLE
TearsheetShell console type error

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#1550]
Hi there,

this is just a console issue, I have seen it before and I believe we solved updating packages, now it appears again after another update to 1.2.

I can provide more info if required

![tearsheetShell-png](https://user-images.githubusercontent.com/7422984/150532438-6ae9ce01-47b5-4d05-8517-4d8f1941ff74.png)
d.

**Comment by lee-chase** [comment]
@ninjasun unable to reproduce in storybook. Assuming resolved in the current version. If not please additional information including steps to reproduce and reopen.
