### ISSUE TITLE
PageHeader with action bar items but no breadcrumb loses title on scroll

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1566]
There's an odd behavior with the title of the PageHeader in the case where there are action bar items (so there is a breadcrumb row) but *no* breadcrumbs and the page starts to scroll.

When there are breadcrumbs, the title starts to scroll with the page and then fades out to appear at the end of the breadcrumbs. When there is no breadcrumb row at all, the title just scrolls off with the page. But when there are action bar items but no breadcrumbs, the title starts to scroll with the page and then fades out, but doesn't appear anywhere. This looks a bit odd, and is probably not the intended behavior.

Title scrolling when there is no breadcrumb row -- this works OK:
![no-a-and-no-b-ok](https://user-images.githubusercontent.com/6385315/150998496-d609233c-9da0-496e-abf6-349de85e0da4.gif)

Title scrolling when there are action bar items and breadcrumbs:
![a-and-b-ok](https://user-images.githubusercontent.com/6385315/150998158-5d205209-f00c-4744-a902-3377501c06b2.gif)

Title scrolling when there are action bar items but *no* breadcrumbs -- the title vanishes after it starts scrolling, but does NOT appear in the breadcrumb row:
![a-and-no-b-wrong](https://user-images.githubusercontent.com/6385315/150998787-42d1bdc8-9ef4-4abf-81ef-e7aa2bfec4f4.gif)

I think that in this case, when there is a breadcrumb row (because of there being action bar items) but there happen to be no breadcrumbs, the title should fade when it starts to scroll and appear in the breadcrumb row exactly as if there is a set of zero breadcrumbs at the start of the row. This would seem more consistent with the other configurations, and with the design as described.

**Comment by dcwarwick** [comment]
@lee-chase opened PR #1562, then made the following comment:

Hi, @cameroncalder a query was raised about a specific use case in which the title fades but is not replaced in the breadcrumb row.

E.g. As per the following link with no breadcrumbs.
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--demo&args=breadcrumbs:0

This PR changes the behaviour (link below) but does not feel satisfactory. I'm tempted to suggest the line between breadcrumb row and title should not be there in this scenario and the title not be breadcrumb sized.

Updated version
https://deploy-preview-1562--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--demo&args=breadcrumbs:0

Could you take a look at this and advise.

_Originally posted by @lee-chase in https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1562#issuecomment-1021099965_

**Comment by dcwarwick** [comment]
@lee-chase @cameroncalder The above links do not work for me. Here are instructions to reproduce the problem case and the fixed case:

### To reproduce the problem case reported above:

- Go to https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--demo
- In the tabs page on the bottom right, select "Controls", scroll down to find "breadcrumbs", and select "No breadcrumb" (replacing the previous choice of "Demo breadcrumbs").
- Scroll the preview pane above and notice how the title vanishes.

### To reproduce the problem case reported above:

- Go to https://deploy-preview-1562--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--demo
- In the tabs page on the bottom right, select "Controls", scroll down to find "breadcrumbs", and select "No breadcrumb" (replacing the previous choice of "Demo breadcrumbs").
- Scroll the preview pane above and notice how the title neatly pops into the breadcrumb row, exactly as it currently does when there are breadcrumbs there.

Here's a capture of the fixed behavior:
https://user-images.githubusercontent.com/6385315/150996483-d8b8415e-0a47-4cca-a8f1-4023f8417817.mov

@lee-chase This fix looks fine to me. What makes you think it does not feel satisfactory? What exactly would you like @cameroncalder to check out and comment on?

**Comment by lee-chase** [comment]
@dcwarwick going to make the PR non-draft. While it would be great to get a review from @cameroncalder I think we can safely conclude the "fix" is an improvement.
