### ISSUE TITLE
Allow danger buttons in modal-like patterns (Tearsheet, Side Panel, etc)

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#1568]
A question was raised by @lily-peng concerning buttons in modal-like patterns (e.g. Tearsheets, Side Panels). The designs for these show/describe the navigation buttons as being primary, secondary or ghost. However, in “danger” situations, the primary button can often be replaced by a danger button. We should be supporting the use of a danger button in place of a primary button for those “danger” situations, as confirmed by Mitchell Bernstein: "Yes we should be supporting the replacement of primary blue with danger red and same for outline and ghost replacements in any scenario".

The prop-types for the affected components should accept danger buttons, and we should also update the ordering logic in ActionSet if necessary so that danger buttons appear in the right place.

**Comment by matthewgallo** [comment]
I think we can close this one now 🎉
