### ISSUE TITLE
Unable to render <Tearsheet> from @carbon/ibm-products

### ISSUE THREAD

**Issue by stevenCloud20** [carbon-design-system/ibm-cloud-cognitive#1577]
## What will this achieve?

implementing a feature /ui dialog

## How will success be measured?

it's not a bug rather it's an improper usage. thanks mdgallo@us.ibm.com
who helped me with it and it's solved now.

## Additional information

- Designs
- Existing code
- etc

**Comment by matthewgallo** [comment]
Turns out this was just a typo during implementation, ie `<TearSheet />` instead of `<Tearsheet />`.
