### ISSUE TITLE
Data table extensions: expandable rows

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1610]
# Data table extensions: expandable rows

## Brief description

This issue will focus on the expandable rows data table extension.

## Details

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/expandable-rows)

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Johanna Koval
- Nina Shahriaree

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by elycheea** [comment]
Replaced by #1922
