### ISSUE TITLE
Tearsheet heading border being cut by margin-right

### ISSUE THREAD

**Issue by davidebibm** [carbon-design-system/ibm-cloud-cognitive#1682]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

> Describe in detail the issue you're having.
Tearsheet heading border being cut by margin-right

> Is this issue related to a specific component?
Tearsheet

> What did you expect to happen? What happened instead? What would you like to
> see changed?
border not begin cut

> What browser are you working in?
chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
v1.7.0

> What offering/product do you work on? 
https://github.ibm.com/automation-base-pak/pm-wui-react

## Steps to reproduce the issue

1. just open Tearsheet on https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--fully-loaded

## Additional information

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--fully-loaded
![image](https://user-images.githubusercontent.com/98974352/155150436-12bd3e19-b790-4577-bc6e-1015a4770ec3.png)

**Comment by elycheea** [comment]
Released in [@carbon/ibm-products@1.9.0](https://github.com/carbon-design-system/ibm-cloud-cognitive/releases/tag/%40carbon%2Fibm-products%401.9.0).
Thanks again for both opening this issue and contributing the fix!
