### ISSUE TITLE
onNext function for TearSheet not working in version 1.15

### ISSUE THREAD

**Issue by petergramenides** [carbon-design-system/ibm-cloud-cognitive#1686]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The TearSheet onNext function always rejects our promise in 1.15. This did not happen in 0.98 - we did not change any code, we only updated Carbon versions. I tried print debugging by adding print statements inside the onNext function but the print statements did not show up, it just always rejected.

> Is this issue related to a specific component?

Yes the TearSheet component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

We expected the TearSheet to allow us to print inside onNext and also for it not to always reject the promise.

> What browser are you working in?

The latest version of Google Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Version 1.15

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This is for Cloud Pak for Watson AIOps. We have an upcoming deadline within the next week. We are currently using an older version in the meantime.

## Steps to reproduce the issue

1. Return a new promise inside the onNext prop for the Create TearSheet component with resolve and reject as input variables
2. Inside the promise, check if a React state external to the component is true. If it is not, then reject.
3. It will always reject regardless and if you try to print debug it will not print your statements.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

- Shared code with @matthewgallo

**Comment by tomleah** [comment]
Hi 👋 

We are also having problems with `onNext`. 
Here is my sandbox - https://codesandbox.io/s/createtearsheet-onnext-bvljgf?file=/src/App.js

In the first step you can enter a string and when you click next it should `console.log` that string. However, it logs `undefined` and then the if you go back and then click next again, it prints logs correctly.

This is stopping us from upgrading from 1.3.0 -> 1.5.0+

**Comment by matthewgallo** [comment]
Hey @tomleah, I've created https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1823 which I tested against how you had your code sandbox component structured and it works with this change. @petergramenides I suspect that this may fix the issue you were running into as well.

**Comment by tomleah** [comment]
Great! Thanks @matthewgallo 🎉

**Comment by matthewgallo** [comment]
This should be fixed in [v1.11.2](https://github.com/carbon-design-system/ibm-cloud-cognitive/releases/tag/%40carbon%2Fibm-products%401.11.2). As always feel free to reopen if you are still experiencing any issues! Thanks for your patience with this one @tomleah and @petergramenides

**Comment by petergramenides** [comment]
Thank you @matthewgallo! Also thank you @tomleah for reproducing.
