### ISSUE TITLE
add select multi select overflow and filtering

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-cloud-cognitive#1713]
when using multi select with a hierarchy the item columns need to support overflow and individual filtering. invision design for reference-

![Screenshot 2022-03-01 at 10-33-16 Add select Pattern Preview Mode - InVision](https://user-images.githubusercontent.com/6370760/156209528-5b788e62-8212-4511-8128-11e4a54c7ad3.png)

**Comment by elycheea** [comment]
@davidmenendez Can we close this issue?
