### ISSUE TITLE
SidePanel (enhancement): Footer Buttons have incorrect alignment

### ISSUE THREAD

**Issue by jagathgj** [carbon-design-system/ibm-cloud-cognitive#1746]
## What will this achieve?

The footer buttons in edit SidePanel should be aligned to bottom and fit the side panel. Currently one existing style for margin bottom is affecting it. And also the buttons are overflowed to the right.

## Additional information

<img width="518" alt="image" src="https://user-images.githubusercontent.com/29351394/157009891-f3cf4cc8-c93d-4fcd-a091-d28127ea12b8.png">

**Comment by matthewgallo** [comment]
Thanks @jagathgj 🎉
