### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by zoyun** [carbon-design-system/ibm-cloud-cognitive#1766]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
I upgrade to @carbon/ibm-products@1.10.0
```npm run dev```
then got below issue
/Users/yunzhenou/Documents/workspaceWKC/wkc-data-quality-ui/node_modules/@carbon/ibm-products/lib/components/TagSet/TagSet.js:60
  allTagsModalTarget: document.body,
ReferenceError: document is not defined

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
 @carbon/ibm-products@1.10.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
https://github.ibm.com/wdp-gov/wkc-data-quality-ui

## Additional information

- Screenshots or code
- Notes

**Comment by lee-chase** [comment]
@zoyun can you provide some context. When do you see this error, how can we reproduce it?

**Comment by lee-chase** [comment]
Believed to be fixed in the latest version
