### ISSUE TITLE
Datagrid component - storybook stories

### ISSUE THREAD

**Issue by holmansze** [carbon-design-system/ibm-cloud-cognitive#1783]
Epic: [1607](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1607)

I've ported existing stories. Here's what is left:
- `StickyActionsColumn` has a problem and is temporarily commented out
- Add / improve stories

**Comment by kai-liu** [comment]
Problem has been described and resolved in this PR:
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2055
