### ISSUE TITLE
Datagrid component - css prefixing

### ISSUE THREAD

**Issue by holmansze** [carbon-design-system/ibm-cloud-cognitive#1784]
Epic: [1607](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1607)

I've scoped the styles under a parent class:

```
const blockClass = `${pkg.prefix}--datagrid`;
```

Needs to investigate if this is good enough, or if we need to also prefix all css class names used by datagrid.

**Comment by matthewgallo** [comment]
https://github.com/holmansze/ibm-cloud-cognitive/pull/2

**Comment by holmansze** [comment]
Thanks @matthewgallo ! Approved and merged.
