### ISSUE TITLE
HTTP errors responsive behaviour

### ISSUE THREAD

**Issue by Laura-Marshall** [carbon-design-system/ibm-cloud-cognitive#1796]
## What package(s) are you using?
Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description
The code for HTTP errors seems to be broken at smaller breakpoints (notably 672px and 320px)

## URL/Link of Page
Link here: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-http-errors-httperror404--with-all-props-set

## Current storybook behaviour
<img width="344" alt="image" src="https://media.github.ibm.com/user/240785/files/e909d180-a92d-11ec-9fbc-a5ee3cc0d682">

## Desired behavior
![image](https://media.github.ibm.com/user/240785/files/ff179200-a92d-11ec-9c5e-8ea810668ba2)

## Design spec
https://www.figma.com/file/Yz74b1hPqqYWwEtmcPqojq/branch/0o1SzPAXFCVSlCPiOiWYEa/Carbon-for-IBM-Products-Design-Kit?node-id=1%3A1328

### Design files
For the purpose of the figma file, we also created new crops of the images here, although these might not be required if the crop of the existing SVGs can be cropped to fit the breakpoint to match the spec. 
https://ibm.box.com/s/gb6w2zm98v0oxcx9iok51w90ugctv2hh

**Comment by elycheea** [comment]
@Ratheeshrajan Can we close this issue since it’s been merged?

**Comment by Ratheeshrajan** [comment]
@elycheea Please close.
