### ISSUE TITLE
SCSS Source maps invalid for index-full-carbon maybe others

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#1864]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When loading SCSS from index-full-carbon.css the source maps the source maps have an invalid path to the source files.

Numerous error reports like the following are shown. It appears to be targeting `node_modules/node_modules/`.

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/15086604/161227401-b23963ea-2b29-4114-827c-27f0e6c1a732.png">

## Steps to reproduce the issue

1. Copy an example from the examples/carbon-for-ibm-products folder.
2. npm run install
3. npm run start

**Comment by lee-chase** [comment]
This appears to be due to our build picking up SCSS files from outside the package being built.

In this case `@carbon/carbon/layout/scss/_breakpoint.scss` we reacy out of the package up to the top level.

**Comment by lee-chase** [comment]
Raised https://github.com/sass/sass/issues/3281

**Comment by elycheea** [comment]
@matthewgallo Let’s look into whether this is still an issue for v11 and figure out how to prioritize from here.

**Comment by matthewgallo** [comment]
This is now fixed in `1.34.1`, confirmed with an app using react-scripts by running `react-scripts build` and no longer see source map errors
