### ISSUE TITLE
Inline Edit Release Review

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#1897]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to main.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account and does not impair, remaining and anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [x] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [x] Public component supports a [Devtools attribute](https://github.com/carbon-design-system/ibm-cloud-cognitive/search?l=JavaScript&q=devtools&type=)
- [x] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.
- [x] Each public component SCSS lists all of the Carbon and C&CS components imported and used by the JavaScript code and explicitly imports the SCSS for each of these components.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [x] All components utilizing motion must include reduced-motion queries for accessibility purposes - [read more here](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
- [x] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md).
- [x] Copyright header in every source file (js, CSS, SCSS etc.) with the appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by elycheea** [comment]
Going to have David and Drew on this one, although Drew still needs to complete his training + user mapping before we can actually assign him.

**Comment by davidmenendez** [comment]
@lee-chase i'd like to set up some time to go over the code. Drew and I started this yesterday, but we had some questions about the code and we'd like you to walk us through it. Aside from that a few things we wanted to point out upon the initial review-

* can you point out designer approval?
* code coverage is not 100%

**Comment by elycheea** [comment]
@davidmenendez Since Lee is wrapped up in other projects for the moment, we should see if @jagathgj can help with outstanding items.

I see #1649 and #1737 for inline edit design reviews with https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1649#issuecomment-1059076387 as approval.

**Comment by lee-chase** [comment]
@davidmenendez if you can find an hour in my calendar it should be OK. 

Once reviewed @jagathgj is more than welcome to book some time with me. My mornings are a little less full.

**Comment by davidmenendez** [comment]
since there's only a small amount of coverage testing left to do i'm going to approve this and make an issue to tackle the remaining testing
