### ISSUE TITLE
Security: add `Legacy` tags in storybook

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1935]
## What will this achieve?

Request to add a `Legacy` tag to some security components. See screenshot for example:

![image (85)](https://user-images.githubusercontent.com/10215203/164291815-acf28c0a-7604-44cb-8bf2-037a767fa46c.png)

## Additional information

Additional details to follow.

- Designs
- Existing code
- etc

**Comment by elycheea** [comment]
Looks like this has already been released. FYI @amtoussam
