### ISSUE TITLE
SyntaxError: Unexpected token 'export' after react-dnd upgrade 

### ISSUE THREAD

**Issue by jainshravan123** [carbon-design-system/ibm-cloud-cognitive#1949]
## Jest test cases are failing 

react-dnd was upgraded from 15 to 16. And it caused following error..
> SyntaxError: Unexpected token 'export'

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- NA -  Legacy/CDAI
- NA - Legacy/Security

## Detailed description

```
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/personal/Documents/Git/my-react-app/node_modules/@carbon/ibm-products/node_modules/react-dnd/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './core/index.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js:18:17)

```

> Is this issue related to a specific component?

Importing of @carbon/ibm-products is causing this error.

> What did you expect to happen? What happened instead? What would you like to

This should not throw error. 

> What browser are you working in?

Chrome but this error is coming when we are running test cases. 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

@carbon/ibm-products@1.15.0, failing with @carbon/ibm-products@1.16.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue
 - Import @carbon/ibm-products and it will start coming. 

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1950 will revert the `react-dnd` version. We were looking to support node 18 with the new version of `react-dnd` but will look at that at a later point in time. Sorry for the inconvenience.

**Comment by jainshravan123** [comment]
@matthewgallo Is there any update on this issue? As of now we pinned `@carbon/ibm-products` to `1.15.0`. Can we unpin `@carbon/ibm-products`  library in our project?

**Comment by matthewgallo** [comment]
Yes you can. This has been reverted to the previous behavior for now until a dependency used in `eslint-config-carbon` is upgraded.
