### ISSUE TITLE
Empty state incorrect spacing

### ISSUE THREAD

**Issue by Laura-Marshall** [carbon-design-system/ibm-cloud-cognitive#1957]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Empty state component seems to be using incorrect spacing / width

This file outlines the intended spacing for both large and small, use the inspect panel to see text styles and spacing measurements (shown in px)
https://www.figma.com/file/Yz74b1hPqqYWwEtmcPqojq/Gray-10---IBM-Products?node-id=1%3A1311

Also, by default we would want to be showing the small sized tertiary button, rather than the default/large size as currently shown in code.

**Comment by punnoosewilson** [comment]
Hi @Laura-Marshall 
Updated the spacing and font-styles according with the [Figma-file](https://www.figma.com/file/Yz74b1hPqqYWwEtmcPqojq/Gray-10---IBM-Products?node-id=1%3A1311) - for both large and small empty-states, also updated the button size to small.

You can check and close the issue.

**Comment by Laura-Marshall** [comment]
Hi @punnoosewilson, this looks great, thank you!

Issue complete and closed.
