### ISSUE TITLE
ICA: Disabled truncation readability

### ISSUE THREAD

**Issue by CassidyJensen** [carbon-design-system/ibm-cloud-cognitive#1974]
## What will this achieve?

If there is a long number that is not truncated on an ICA, it may be beneficial to have the display add commas or periods (depending upon the locale) to make long numbers easier to read. For example: 100,000,160 instead of 100000160.

## How will success be measured?

- Add support to make long numbers easier to read when truncation is disabled for ICA.
- Add or update tests as needed
- May need design review / approval

## Additional information

The function toLocaleString seems to insert the appropriate punctuation. However, I cannot pass this value into ICA and have it work, it seems to override back into a number and ignore the punctuation. 
 `value.toLocaleString(<insert locale string>);`

**Comment by elycheea** [comment]
@CassidyJensen Can you clarify what component/pattern and package this refers to?
