### ISSUE TITLE
Data table: Align scrolling to PAL pattern

### ISSUE THREAD

**Issue by jjennings7** [carbon-design-system/ibm-cloud-cognitive#1977]
# Data table extension: Scrolling

## Brief description

WKC data table does not include several elements from Carbon for IBM Products PAL for horizontal scrolling:

- #2173  
- #2174

## **Responsive behavior**

WKC table maintains table actions in the same place at all breakpoints:
![Screen Shot 2022-05-09 at 5 01 32 PM](https://user-images.githubusercontent.com/48838320/167518505-1c961cdb-f284-4bfa-91cb-0e60b495aab6.png)
![Screen Shot 2022-05-09 at 5 03 18 PM](https://user-images.githubusercontent.com/48838320/167518526-da0562fe-a672-4cb7-8984-b06f90b36f1c.png)

PAL guidance:

> Frozen last columns can continue to be frozen Toolbar icons and buttons move under a single “combo” button and search is collapsed to right Toolbar interactions such as filters and settings appear in a mobile modal dialogue Frozen identifier columns are unfrozen for viewports below 672px

> Items like filter and settings takeover screen

<img width="321" alt="Screen Shot 2022-05-09 at 5 19 26 PM" src="https://user-images.githubusercontent.com/48838320/167518708-c82aeae0-0c5a-4e6e-8418-dd64ddc67bbb.png">

<img width="348" alt="Screen Shot 2022-05-09 at 5 19 36 PM" src="https://user-images.githubusercontent.com/48838320/167518712-e6d10533-243e-469d-aa41-13192da40bf3.png">

## Details
See Carbon for IBM Products PAL site guidance for scrolling here:
https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage/

## Design Maintainer(s)

- Marion Brülls
- Johanna Koval

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by elycheea** [comment]
FYI @matthewgallo responsiveness is kept in this ticket. Scrollbars and trunction/text handling are split into new tickets.
