### ISSUE TITLE
Inconsistency narrow tearsheet design guidance and storybook component 

### ISSUE THREAD

**Issue by marion-bruells** [carbon-design-system/ibm-cloud-cognitive#2001]
## Inconsistencies PAL guidance and storybook component narrow tearsheet
The narrow tearsheet title block shows a line and different spacings in the guidance than it is in the storybook.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
The narrow tearsheet title block shows a line and different spacings in the guidance than it is in the storybook.

PAL guidance website and Sketch/Figma Kit:
https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/style
<img width="465" alt="image" src="https://user-images.githubusercontent.com/51152537/169545152-f4bbb089-dda0-4352-8719-5a0af1872c08.png">

Coded implementation, storybook:
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheetnarrow--tearsheet-narrow
<img width="506" alt="image" src="https://user-images.githubusercontent.com/51152537/169545104-d86642a0-6d1a-478a-92f3-a5aa4dfa061c.png">

> Is this issue related to a specific component?
Narrow tearsheet
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheetnarrow--tearsheet-narrow

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Adjust spacings, add line below title block to align with PAL guidelines.
https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/style

> What browser are you working in?
Firefox, Safari

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson Knowledge Catalog

**Comment by elycheea** [comment]
@marion-bruells Wanted to check the spacings that needs to be adjusted.
I noticed when checking Figma that our spacing between the title and description is a bit taller than it should be.

Storybook | Figma
-----------|-------
![image](https://user-images.githubusercontent.com/1717398/173086711-29eb3869-42bf-4b5e-bcfe-d002feb7c626.png) | ![image](https://user-images.githubusercontent.com/1717398/173086777-2cd7f5cd-3ebb-476f-948e-cf52800436e4.png)
16px / `$spacing-05` | 8px / `$spacing-03`

While comparing the implementation in Storybook, Sketch, and Figma, I also noticed that the header spacing is different in Sketch and Figma. In Storybook, we are using `16px`. This seems to be consistent with what was shown in Sketch as well as the screenshot you shared above. Figma, however, shows `24px / 32px` padding in the header areas.

**Sketch**
![image](https://user-images.githubusercontent.com/1717398/173085841-db2cce2c-2dba-4e8d-98ea-2f059b45df96.png)
(Not sure why the fonts are missing)

**Figma**
![image](https://user-images.githubusercontent.com/1717398/173087535-e87794b0-667c-4a93-b8e4-2230fdc6605c.png)

**Comment by marion-bruells** [comment]
Maybe it’s something we need to update in Figma. We should check with @Laura Marshall, she leads the Figma effort. I’ll ping her since I can’t tag her here

**Comment by Laura-Marshall** [comment]
Issue is being tracked here https://github.ibm.com/CDAI-design/pal/issues/954, and should be updated in the next Figma kit update (planned end of next week)

**Comment by elycheea** [comment]
Thank you @Laura-Marshall and @marion-bruells. I’ve also added the `16px` v. `24px / 32px` to the comments of the PAL issue.

We’ll keep with 16px for now in Storybook, but let us know if we end up keeping the Figma spacing and need to update this on our end as well.

**Comment by jagathgj** [comment]
@elycheea Currently it is 16px gap. Do we need to change it? Or else you can close this issue.

**Comment by marion-bruells** [comment]
thanks 16px is perfect. I’ll close the issue

**Comment by Laura-Marshall** [comment]
I'm not sure if its ready to close, as code is still missing the rule under the tearsheet header?

**Comment by elycheea** [comment]
@Laura-Marshall @marion-bruells We can close this issue once the border and the spacing are merged — should be soon since part of this is already in a PR. 🙂
