### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by wood-doug** [carbon-design-system/ibm-cloud-cognitive#2004]
### Summary

Tear Sheet:  I need to be able to abort the close from the button on the top right.  I'm using the tear sheet for a wizard that does significant work including network uploads.  I need to insert an "Are your sure" popup into the close sequence.

### Required functionality

returning false from onClose should abort closing the tear sheet.

### Specific timeline issues / requests

Project DCUT is in 12 weeks.  Need it before that

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by matthewgallo** [comment]
Hi @wood-doug! 👋 Sorry for the late response! Here is an [example](https://stackblitz.com/edit/github-k1spvy?file=package.json,src%2Findex.scss,src%2FTearsheetExample.jsx) of what you're describing. You can, as you mentioned, return false in the tearsheet `onClose` function to prevent it from closing. Let us know if you have any further questions!
