### ISSUE TITLE
Remove Pattern Enhancement

### ISSUE THREAD

**Issue by ashanew22** [carbon-design-system/ibm-cloud-cognitive#2034]
## Description

Several teams reached out to Cloud PAL in need of guidance for a friction delete modal. We conducted an audit and presented the findings at the Cloud PAL Design Guild. We found that many teams are using different deletion modals (that currently do not comply with the [Removal Guidance located in Carbon](https://www.carbondesignsystem.com/community/patterns/remove-pattern/)). Cloud PAL determined creating a set of guidance for the three main use cases would create a more cohesive experience across the platform.

We started working on a new set of guidance called Friction Delete that built upon the [Remove pattern](https://www.carbondesignsystem.com/community/patterns/remove-pattern/). But we believe that creating a new set of guidance might cause confusion and feel too similar to the Remove pattern.

We have presented at DSAG + DSIT and have gotten approval to add it to the CFIP docsite ✅

## Details

[Current remove pattern guidance](https://pages.github.ibm.com/cdai-design/pal/patterns/removing/usage/)
- Add friction deletion under Remove patterns

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Owner/main maintainer(s)
- Second/backup maintainer(s)

## Design Maintainer(s)

- Asha Newsom
- Cloud PAL Team

**Comment by elycheea** [comment]
Closing this since changes may be captured in #2190.
