### ISSUE TITLE
Data table extension: Filtering

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2069]
# Data table extension: Filtering

## Brief description

This issue will deliver the data table extension for filtering.

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters)

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Marion Brülls
- Johanna Koval

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by sdignum** [comment]
[Link to Sketch file](https://ibm.box.com/s/18xqg821iuat3t8gr25ygmajxb3kq8yn) with curated screens for dev to reference
