### ISSUE TITLE
Data table extension: Actions dropdown

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2070]
# Data table extension: Actions dropdown

## Brief description

This issue covers the actions dropdown extension for data tables. The actions dropdown is a dropdown in the primary button location.

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons)

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Marion Brülls
- Johanna Koval

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by matthewgallo** [comment]
Includes incorporating the ButtonMenu for primary action
