### ISSUE TITLE
Carbon v11: update component tests

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#2071]
## What will this achieve?

With v11 some of the DOM elements, class names, and props have changed and have broken some of the tests for our components. 

When updating a component's API to use Carbon v11 make sure to check all of the imported Carbon components within the component file itself, as well as any Carbon components used in the stories.

- [x] APIKeyModal
- [x] APIKeyDownloader
- [x] AddSelect
- [x] AddSelectBreadcrumbs
- [x] AddSelectSort
- [x] AddSelectMetaPanel
- [x] AboutModal (has a11y violations all other tests pass)
- [x] ActionBar
- [x] ActionBarItem
- [x] ActionSet
- [x] BreadcrumbWithOverflow
- [x] ButtonMenu
- [x] ButtonSetWithOverflow
- [x] Card
- [x] CardHeader
- [x] CardFooter
- [x] Cascade
- [x] ComboButton
- [x] CreateFullPage
- [x] CreateInfluencer
- [x] CreateModal
- [x] CreateSidePanel
- [x] CreateTearsheet
- [x] CreateTearsheetNarrow
- [x] DataSpreadsheet
- [x] Datagrid (in progress @matthewgallo)
- [x] EditSidePanel
- [x] EmptyStates
- [x] ExampleComponent
- [x] ExportModal
- [x] ExpressiveCard
- [x] HTTPErrors
- [x] ImportModal
- [x] InlineEdit
- [ ] ModifiedTabs (has no tests)
- [x] MultiAddSelect
- [x] NotificationsPanel
- [x] OptionsTile
- [x] PageHeader
- [x] ProductiveCard
- [x] RemoveModal (@elycheea)
- [x] Saving
- [x] SidePanel
- [x] SingleAddSelect
- [x] StatusIcon
- [x] TagSet (@elycheea)
- [x] Tearsheet
- [x] Toolbar 
- [x] UserProfileImage 
- [x] WebTerminal
- [x] Wrap
- [x] `src/__tests__/styles.test.js` (will be complete when https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2121 is reviewed/merged)
- [x] `src/__tests__/scss.test.js`

## How will success be measured?'

In your terminal run `yarn run jest /[Component folder name]/` and all tests should pass.

**Comment by AlexanderMelox** [comment]
(July 6) Went through all the components and they are updated to reflect the tests that have passed and failed

**Comment by matthewgallo** [comment]
A handful of tests are failing now because of a Carbon issue (any component using tearsheet), there is a [PR open](https://github.com/carbon-design-system/carbon/pull/11866) to fix this and should be included in the next `@carbon/react` release.
