### ISSUE TITLE
InlineEdit bug, placeholder text not loading properly

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/ibm-cloud-cognitive#2107]
I'm seeing a bug with InlineEdit, where the placeholder text doesn't load properly. I think it has something to do with render not executing or animation isn't executed.. (i noticed a little bit animation for the placeholder text to fade in?)
Generally, if I use a condition to load `InlineEdit`, for example if we're loading/processing the values in the first few react cycles, and we're going to show the Skeleton loader while waiting.. it doesnt work.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Generally, if I use a condition to load `InlineEdit`, for example if we're loading/processing the values in the first few react cycles, and we're going to show the Skeleton loader while waiting.. it doesnt work.

> Is this issue related to a specific component?
InlineEdit

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected the placeholder text to load

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
`1.23.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud

## Steps to reproduce the issue

1st screenshot: The placeholder text is missing from the InlineEdit
<img width="416" alt="Screen Shot 2022-07-18 at 3 10 33 PM" src="https://user-images.githubusercontent.com/37594705/179596050-47b8ea76-e4bd-4f9d-8091-2f019a08ac47.png">

2nd screenshot: I clicked (activated) on the InlineEdit, the placeholder text fades in
<img width="437" alt="Screen Shot 2022-07-18 at 3 11 23 PM" src="https://user-images.githubusercontent.com/37594705/179597147-79f80186-2b83-4453-9f86-b467a99afadd.png">

3rd screenshot: Without entering text, I removed focus from the InlineEdit (click somewhere else on the page). Placeholder text is visible (as it should on component load)
<img width="434" alt="Screen Shot 2022-07-18 at 3 12 00 PM" src="https://user-images.githubusercontent.com/37594705/179597996-725b2e1a-6dd1-48f9-a1df-f59782ea3c94.png">

Here is a code snippet to reproduce the issue:
```
const MyComponent = () => {
  const [input, setInput] = useState(null);

  useEffect(() => {
    setInput("");
  }, []);

  return (
    <div>
      <div>
        {input !== null ? (
          <InlineEdit
            size="lg"
            buttonTooltipAlignment="end"
            buttonTooltipPosition="left"
            editDescription="edit"
            saveDescription="save"
            cancelDescription="cancel"
            placeholder="my placeholder"
            value={input}
            onSave={setInput}
          />
        ) : (
          <TextInputSkeleton />
        )}
      </div>
    </div>
  );
```
Simpliest reproduction.. sometimes we're loading values and it takes a few react cycles before it's ready, so in the above case, `input` is `null` and not ready yet, so we're going to show the loading Skeleton while we wait.
Once it's ready, then we load the `InlineEdit` component.
In this scenario, placeholder doesn't load properly.

note that if `input` is ready since the very FIRST react cycle (set `useState("");` instead of `null`) and remove the `useEffect()`, then placeholder text appears fine.

**Comment by elycheea** [comment]
@Ratheeshrajan Please see David’s comments in #1924 — hoping we can look into it while you’re already on Datagrid Inline Editing, but we can also address this in a separate PR to keep your current changes small if needed.

**Comment by Ratheeshrajan** [comment]
@Elysia I hope this is specific to inlineEdit component and I think it would be good if we address it separately.
