### ISSUE TITLE
InlineEdit bug, onChange doesnt seem to work as expected

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/ibm-cloud-cognitive#2112]
Using the `InlineEdit` component, it offers a few different event handlers. `onSave`, `onCancel`, and `onChange`. When using `onChange`, I expected it to work like the other carbon-components where we could save the value in our local state (instead of inside the InlineEdit component).. But once I set the value in my local state and pass it back through the `value` parameter, the cursor jumps to the beginning of the input.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Created a simple InlineEdit component like this:
![image](https://user-images.githubusercontent.com/37594705/179824477-98aa4095-f634-414f-8ed8-3c4a1c87c37a.png)

And as i type in `a`, `b`, `c`, it becomes `cba` because the cursor jumps to beginning, like this:
![image](https://user-images.githubusercontent.com/37594705/179824603-1c3d6693-41c2-4a67-b601-66cd5274ed30.png)

> Is this issue related to a specific component?
InlineEdit

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected to be able to store the typed value externally from InlineEdit, so incase I would like to check/detect certain things in it.. like maybe do real time validation on the input. 
If i do NOT use `onChange()`, and only use `onSave()`, `onCancel()` and `value` parameters, it works fine. I know the InlineEdit component stores a cache of the new changes, so that the user is able to click cancel to undo the diff and etc.. and I know that `onSave()` and `onCancel()` returns the actual/final value too, so was hoping to accomplish the same functionality but while storing the changing value outside for other operations/validations/etc. 
I don't remember now, but i think `onCancel()` might not work properly if i'm using `onChange` to store outside.. since a new value is being passed in on every new character, i think that resets the initial value so cancel function doesnt operate as expected, and `onCancel()` is not returning the proper initial value

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
`1.23.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM cloud

## Steps to reproduce the issue
Code snippet provided in screenshot above

**Comment by davidmenendez** [comment]
after doing some investigation on the implementation of this component i've come to the following conclusion- i agree that the text input should behave the same way as the carbon input. unfortunately, due to it's current implementation, it's utilizing `contentEditable` which has several downsides and accommodating this change would require making the current implementation much more complicated and in my opinion much more unnecessary.

so i'm going to leave this issue open, but i'm going to open a separate issue to refactor `InlineEdit` to use a regular text input instead of a div with `contentEditable`.

**Comment by matthewgallo** [comment]
This is part of a larger issue and will be included in the new `InlineEditV2` component which uses an actual Carbon text input during edit mode.

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-edit-and-update-inlineeditv2-canary--default
