### ISSUE TITLE
MultiAddSelect onSubmit exception

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/ibm-cloud-cognitive#2123]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
- className prop is not displayed in the component;
- onSubmit cause an exception when clicking the primary button;

> Is this issue related to a specific component?
Yes: MultiAddSelect

> What did you expect to happen? What happened instead? What would you like to
> see changed?
- className should be added to the widget;
- onSubmit Function should returns a selection

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
1.23.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
No

## Steps to reproduce the issue

1. Open the MultiAddSelect 
2. Select one of the items from the list
3. Click Add

Exception:
```
TypeError
Cannot read properties of null (reading 'length')
    at Array.submitHandler (https://gz3o6u.csb.app/node_modules/
carbon/ibm-products/es/components/AddSelect/AddSelectBody.js:61:35
eval
https://gz3o6u.csb.app/node_modules/carbon-components-react/es/tools/events.js:16:16
```

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/recursing-ptolemy-gz3o6u?file=/src/index.js

Code from https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-add-select-multiaddselect-canary--default

## Additional information

- Screenshots or code
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/20518828/180474383-5f3d2d75-4151-4d41-a504-42a028b6275f.png">

- Notes

**Comment by davidmenendez** [comment]
@kimbaz thanks for opening this issue. i opened up your codepen and i haven't been able to reproduce this error. i see that in your `package.json` that the library is set to latest `"@carbon/ibm-products": "latest"` so i think it might have been resolved in a recent commit. can you please take another look and confirm if you're still experiencing this issue?

**Comment by kimbaz** [comment]
@davidmenendez I just tested it on 1.24.0 and it looks fixed. Thank a lot!
