### ISSUE TITLE
ImportModal: invalid file type returned when importing from URL with accept = []

### ISSUE THREAD

**Issue by jillyj** [carbon-design-system/ibm-cloud-cognitive#2126]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Unable to upload the file with extension `.jpynb` from URL. The accept prop is set to `accept: []`. The error `Invalid file type` occurs.

> Is this issue related to a specific component?

Yes, Import Modal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- Should be able to upload all file types from URL when accept is []. 

> What browser are you working in?

Chrome, Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

@carbon/ibm-products 1.15.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4S Data Explorer, release target date: 9/30.

## Steps to reproduce the issue
1. In URL field, input `https://raw.githubusercontent.com/opencybersecurityalliance/kestrel-huntbook/main/huntbooks/log4shell%20Detection.ipynb`. 
2. Click Add file.

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/confident-resonance-o9be76?file=/src/Example/Example.js

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/47232763/180696833-eaabc031-ec38-4e0a-9564-88e0ba013a4c.png)

**Comment by jillyj** [comment]
It would be appreciated if you could take https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1933 into consideration.

**Comment by jillyj** [comment]
Can anyone look at this bug? I can't find a way to make drag&drop and url fetching works with accept=[]. I am thinking maybe we need to use separate props for drag&drop and url fetching?

**Comment by elycheea** [comment]
@jillyj We’re investigating and will report back. Thanks for reporting this.

**Comment by AlexanderMelox** [comment]
@jillyj Currently a PR up for this #2218

**Comment by AlexanderMelox** [comment]
Resolved in PR #2218

**Comment by jillyj** [comment]
@AlexanderMelox I tested on this codesandbox https://codesandbox.io/s/confident-resonance-o9be76?file=/src/Example/Example.js, but I still can see the error when importing from URL (ex: https://raw.githubusercontent.com/opencybersecurityalliance/kestrel-huntbook/main/huntbooks/Windows%20Scheduled%20Tasks%20Hunting.ipynb).
Could you look at this issue again or did I miss anything to make it work?

And the other problem is when I set accept to `accept: ["*.ipynb", "*.txt"]`, when I open the file explorer, it allows all extensions including `.csv`. Not sure how the accept works for file explorer and URL....
![image](https://user-images.githubusercontent.com/47232763/186303924-d350c931-75ab-49f7-980f-86a135bd9093.png)

**Comment by AlexanderMelox** [comment]
@jillyj Yeah, because the changes are on the latest version which is 2.13.2, is it possible to update the versioning?

**Comment by AlexanderMelox** [comment]
Interesting because on the live storybook if you set `accept= []` or `accept= [".ipynb", ".txt"]` it works 🤔

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-import-and-upload-importmodal--standard

<img width="2229" alt="Screen Shot 2022-08-24 at 10 36 34 AM" src="https://user-images.githubusercontent.com/12755042/186446601-a8188ed3-5b6f-4071-b6e2-9ae39ea6e01a.png">

@jillyj Can you try to do it on the live storybook and see if it works for you?

**Comment by AlexanderMelox** [comment]
<img width="732" alt="Screen Shot 2022-08-24 at 10 41 32 AM" src="https://user-images.githubusercontent.com/12755042/186447819-ba62b441-109e-4c4a-a035-1d7514644816.png">

@jillyj You'll have to wait for the package to update next tuesday 😄

**Comment by AlexanderMelox** [comment]
In terms of it opening a CSV, It also happens to me, I think a CSV is considered a TXT or `text/plain` file so maybe that's why

**Comment by AlexanderMelox** [comment]
Here's a helpful key to know what to pass for what file extension 
https://stackoverflow.com/questions/11832930/html-input-file-accept-attribute-file-type-csv

**Comment by jillyj** [comment]
@AlexanderMelox，Thanks for the information! I'll test it out in the next release.
