### ISSUE TITLE
Broken Storybook examples

### ISSUE THREAD

**Issue by barlock** [carbon-design-system/ibm-cloud-cognitive#213]
## Detailed description

Some storybook examples seem to be broken. 

Mostly giving an error that looks like:

`TypeError: Cannot read property 'fonts' of undefined`

## Steps to reproduce the issue

1. Visit https://ibm-cloud-cognitive.netlify.app/?path=/story/docs-description--text
2. Error!

## Additional information

![image](https://user-images.githubusercontent.com/5770007/99086671-d643f780-2597-11eb-827b-5288e378097d.png)

**Comment by SimonFinney** [comment]
Strange - These look like Storybook example stories and likely shouldn't be included as part of the build

**Comment by barlock** [comment]
_Interesting_ I'm quite interested in everything under `docs`. 

Parts of this project are clearly stubs, are these implemented?
