### ISSUE TITLE
MultiAddSelect components allows duplicate item selection

### ISSUE THREAD

**Issue by mohammed-mian** [carbon-design-system/ibm-cloud-cognitive#2131]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Depending on the sequence of user selections, it is possible to have duplicate items in the selection list. In the example below, `folder 1` appears twice in the selection list.

![Screen Shot 2022-07-25 at 5 02 33 PM](https://user-images.githubusercontent.com/36860898/180873545-9002c957-e06d-4408-8c6e-34ce36eebf3e.png)

> Is this issue related to a specific component?

This issue is specific to the `MultiAddSelect` component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect the component to ignore an item with a duplicated id when updating the state for selected items.

> What browser are you working in?

Google Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Carbon for IBM Products v1.23.1

## Steps to reproduce the issue

1. Go to https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-select-multiaddselect-canary--with-hierarchy and launch the `AddSelect` component modal. 
2. Select an item within the `Business terms` list (i.e. `folder 1`).
3. Then use the checkbox at the top of the list (i.e. the checkbox next to `Business terms`) to select all the items under `Business terms`
4. Observe that `folder 1` now appears in the selected items twice.

**Comment by mohammed-mian** [comment]
@davidmenendez

**Comment by davidmenendez** [comment]
@mohammed-mian this should be resolved. please pull latest and let me know if you're still experiencing this issue.

**Comment by mohammed-mian** [comment]
Verified that the issue is fixed, thanks.
