### ISSUE TITLE
Add workflow for merging main to carbon-v11 branch

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2134]
## What will this achieve?

Ensures that Carbon 11 branch regularly merges from `main`.

## How will success be measured?

Should create a PR to merge `main` to `carbon-v11` branch on a weekly basis

## Additional information

- Designs
- Existing code
- etc

**Comment by matthewgallo** [comment]
I _think_ the workflow file may need to be added to the `main` branch in order for github actions to pick up on it

**Comment by elycheea** [comment]
@matthewgallo Oooh. Gah, I’ll open another PR for it. Thanks for checking! How did I not notice? 🙃
