### ISSUE TITLE
ProductiveCard: Allow Ghost buttons in the Action Bar

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#2155]
## According to the [Productive Card design docs](https://pages.github.ibm.com/cdai-design/pal/components/card/productive/usage), ghost buttons can be added in the top action bar next to the title:

![image](https://user-images.githubusercontent.com/3118961/183160240-c3bc6d1e-7793-41a9-8e6a-28b9362f9e82.png)
![image](https://user-images.githubusercontent.com/3118961/183160251-831c08ad-9f65-4b77-bffb-36765084a791.png)

Currently however, the ProductiveCard component has the prop `actionIcons` which only support icon buttons.

We'd like the functionality to add ghost buttons in the action bar as well.

## How will success be measured?

Once the props are updated to allow users to specify the presence of ghost button(s) in the action bar. Users should be able to name the button, add onClick functionality, and provide an optional supporting icon to the button. Ghost button(s) should be able to coexist on the same line as the title and the action icons at the top of the card.

## Additional information

As a front-end dev on the XDR Connect Threat Investigator team, I've been working with our design team on the following design for Productive Cards:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/3118961/183160708-c8deafe6-da27-4930-bafd-e8ed1b13bc43.png">

This mockup includes a ghost button with 3 icons in the top-right bar.

**Comment by punnoosewilson** [comment]
@lily-peng 
The ghost button feature is included. You can review and close this issue.

For more details please refer the PR: https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2253
