### ISSUE TITLE
Data table: Scrolling scrollbar styles

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2174]
# Data table extension: Scrolling

## Brief description

This issue covers the scrollbar styling and behavior in the data table. This issue is broken out from #1977

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage/#styling)

Our implementation most likely would follow the browser default scrollbar although WKC does use a custom scrollbar in the [Infinite Scroll](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--infinite-scroll) and [Ten Thousand Entries](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--ten-thousand-entries) stories.

> ### **Scroll bar**
> 
> WKC scrollbar is always present when horizontal scroll is enabled and styling is strange - the bars cut off the content that they normally float above:
> ![Screen Shot 2022-05-09 at 5 11 38 PM](https://user-images.githubusercontent.com/48838320/167518308-63386035-98e6-4bf1-b33c-2dc394434a18.png)
> _Note: Example is from Chrome_
> 
> PAL scrollbar appears on hover, and floats above the content without cutting it off (standard browser behavior):
> <img width="796" alt="Screen Shot 2022-05-09 at 5 15 38 PM" src="https://user-images.githubusercontent.com/48838320/167518446-6033607f-da18-44ef-b3ee-ec6b60531f52.png">

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Marion Brülls
- Johanna Koval

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by elycheea** [comment]
Also note that the Infinite Scroll and Ten Thousand Entries stories include an empty Table Toolbar.

![image](https://user-images.githubusercontent.com/1717398/184241724-6c229997-bb60-4f4a-bf16-8e658f01d60f.png)

We should fix the stories as a part of this issue as well.

**Comment by matthewgallo** [comment]
That seems to have been caused by the batch actions PR, I’ve made a follow up to fix it 
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2171
