### ISSUE TITLE
fix: customization Column Modal Search Error

### ISSUE THREAD

**Issue by ghost** [carbon-design-system/ibm-cloud-cognitive#2181]
As discovered by @kai-liu, while searching in the column customization modal/tearsheet, the search loses focus and the cursor disappears.

- [x] Focus should remain on the search box until user moves to another element
- [x] While searching, the [matching term should be highlighted](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage#search) in the results
- [x] x icon is misaligned

![image](https://user-images.githubusercontent.com/1717398/207423824-3145f114-4c74-45fc-a644-08056fc881df.png)

**Comment by kai-liu** [comment]
Issue: Cursor disappears while typing in the Customization Column Modal searchbox.

**Comment by elycheea** [comment]
@kai-liu are we still able to work on this or do we need to reassign this?

**Comment by kai-liu** [comment]
@elycheea Per Holman's direction, please reassign this to someone else. Thank you.

**Comment by kai-liu** [comment]
Please let me know if clarification or demonstration of the bug is needed.

**Comment by elycheea** [comment]
FYI @Ratheeshrajan found another bug related to the X icon during the design review with @Ashley-Bock
