### ISSUE TITLE
Multi Add Select design review

### ISSUE THREAD

**Issue by OliverKauselmann** [carbon-design-system/ibm-cloud-cognitive#2184]
## Design review

Component epic #

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by OliverKauselmann** [comment]
Hi @davidmenendez, here is a list of findings reviewing the implementation:

**1. Spacing left**
Please adjust the 32px indentation from the left, with 16px of searchfield and lines
Compared to the layout

**2. Searchfield**
Use large component and remove label on searchfield 
(use searchfield component)

**3. RHS Panel general**
Do not scale the RHS sidepanel when resizing the window. Keep fixed width of 360 px.
Empty state should have a spacing of 48px to the top
Please adjust typo tokens and shorten line length

**4. Table row spacing and interactions** 
Please correct row spacing from border, checkbox to label
Row separator lines missing when selected
Please implement all interactive table row states (see also [single select comments](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2014#issuecomment-1155246087))

Carbon guidance on clickable data table row items
https://pages.github.ibm.com/cdai-design/pal/components/data-table/clickable-row-items/usage/#style

**5. RHS Selection items**
Please compare spacing and adjust where needed
If items are collapsed arrows point to the right
Add a remove icon and functionality on hover
Horizontal title line doubles to 2px line when selection is done (overlays empty state?)

**6. RHS Info panel**
Trigger panel with click on eye and also in parallel by click on complete row
The eye-icon should only be visible on hover
Show blue line indicator in the row that refers to the info panel content

In general a lot of the findings (especially Table row interactions, RHS Indicator, Row spacing, RHS behaviour without resizing etc.) are already implemented here in a add select version by the project team. maybe it helps as orientation and you can reuse existing code (?) https://pages.github.ibm.com/wdp-gov/wkc-shared-ui/?path=/story/tearsheets--preselected-list-tearsheet

<img width="2574" alt="image" src="https://user-images.githubusercontent.com/71088955/184905679-3b8eea51-2c47-4884-b83a-43b10369282e.png">
<img width="2574" alt="image" src="https://user-images.githubusercontent.com/71088955/184906092-80e8528e-053e-4c78-aad3-cfff7b9f5314.png">
<img width="2574" alt="image" src="https://user-images.githubusercontent.com/71088955/184905732-4d79e466-4c62-44df-a031-df0ce539ec0d.png">

**Comment by davidmenendez** [comment]
3- i can make the empty state more narrow, but as far as the font goes it's already using the standard [empty state pattern](http://localhost:3000/?path=/story/ibm-products-patterns-empty-state-emptystate--with-custom-illustration).

5- the remove icon can't be added for technical reasons. the accordion is already a button, so we can't add a button within a button. it also causes issues when there are click zones within click zones

i'll update this as i make progress

**Comment by marion-bruells** [comment]
@elycheea what's the status on this? 

@davidmenendez Where you able to address some of the fixes outlined by Oliver? 
For 5 – can you use the expandable table row instead of the accordion? 
For 3 – can you adjust the width of this component. Text shouldn’t take full width for better legibility.

**Comment by elycheea** [comment]
@davidmenendez and @OliverKauselmann have been following up. David was recently caught up in some of the v10-v11 maintenance, but think we should be able to wrap up the fixes soon.

For 3, it sounds like we are okay with keeping default empty state if we apply a maximum width for the empty state? Want to ensure we’re on the same page on the change we will make. While we can adjust the typography, we need to ensure there’s good justification when we break from the pattern so we can identify the need another empty state variant or at least limit inconsistencies in our empty states.

For 5, I think accordion makes the most sense semantically based on the content and usage. Not sure if David and Oliver have discussed this one further with some possible alternatives.
