### ISSUE TITLE
Delete / remove pattern small inconsistencies

### ISSUE THREAD

**Issue by Laura-Marshall** [carbon-design-system/ibm-cloud-cognitive#2190]
### Guidance
![image](https://user-images.githubusercontent.com/53219208/185178150-44706343-aef7-4d47-81bd-699635ea10d0.png)

### Code
![image](https://user-images.githubusercontent.com/53219208/185177705-437d365a-e544-4dc7-a61b-62475180e9bb.png)

### Bug
Code is missing the x icon on all instances. Also, design shows "Cancel" as the secondary CTA, whereas code shows "Close". Makes sense to show the default as the same as the design guidance.

**Comment by elycheea** [comment]
Looks like some of this was updated in the friction deletion changes. Thanks for pulling out the necessary changes!

**Comment by glapadre** [comment]
@Laura-Marshall should the secondary button color be darker (#161616) seen in the guidance vs the gray (#393939) seen in the code? I know this changes depending on the carbon theme but it's not matching between the guidance vs code?

**Comment by Laura-Marshall** [comment]
@glapadre Thats a great question! I think the secondary button should be whatever colour the usual secondary button in modals is, this shouldn't be overriding anything. I believe that it should be interactive-02.

**Comment by glapadre** [comment]
@Laura-Marshall okay great I'll keep it as is, I'll look into why there's a discrepancy with the PAL site.
