### ISSUE TITLE
Data table extension: Filtering > Flyout

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2251]
# Data table extension: Filtering

## Brief description

Part of #2069

## Details

[Link to design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters/#filter-flyout)

- Filter button should open flyout
  - Leverage `DatagridActions`
- Include title for filter (prop) to ensure translatability
- Should accept an array or node that handles the filtering
  - Consumer to provide their content/body and we provider the structure
- Action buttons — `ActionSet`

### Links to other materials

e.g. sketch files, icons, images, prototypes

## Design Maintainer(s)

- Virginia Nicholson
- Ashley Bock

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by AlexanderMelox** [comment]
Having major blockers with the way the Datagrid component receives components into the state. This is making the component re-render and resetting it's state.
