### ISSUE TITLE
Make the PageHeader an accessible page header

### ISSUE THREAD

**Issue by alexandria-lewis** [carbon-design-system/ibm-cloud-cognitive#2257]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?
Can you change the PageHeader component to use <header> and an option to use an h1 tag around the title?
I used this component with a screen reader and it just recognizes the PageHeader as text. Even single page applications need a page header for accessibility. It's a WCAG bare minimum requirement.

## Relevant information
[https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--with-title](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--with-title)

[https://www.w3.org/WAI/WCAG21/quickref/#page-titled](https://www.w3.org/WAI/WCAG21/quickref/#page-titled)

**Comment by Dhruv1107** [comment]
Hi @elycheea  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by elycheea** [comment]
Hi @Dhruv1107, this is currently assigned to @glapadre!
