### ISSUE TITLE
@carbon/ibm-products not being published to npmjs

### ISSUE THREAD

**Issue by kimbaz** [carbon-design-system/ibm-cloud-cognitive#2261]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?
Why @carbon/ibm-products is not being published to the npmjs registry anymore? I see new versions being released but we can't use them in our app because they are not available on npmjs

**Comment by matthewgallo** [comment]
See @elycheea's comment [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2215#issuecomment-1239800570).

**Comment by kimbaz** [comment]
Thank you
