### ISSUE TITLE
Page header button alignment bug

### ISSUE THREAD

**Issue by Laura-Marshall** [carbon-design-system/ibm-cloud-cognitive#2262]
Storybook shows buttons always aligning right, even at 672px and 320px breakpoints: 

![image](https://user-images.githubusercontent.com/53219208/189077698-0d6111f9-de19-44ff-a4d6-3f0d958eb8e2.png)

However, guidance shows the buttons aligning left below 672px.

![image](https://user-images.githubusercontent.com/53219208/189077761-cf5561f6-6fdc-4d61-a9fe-d9114a767d79.png)

**Comment by sejalmishra** [comment]
hey if no on is already working on this can i work on this?
