### ISSUE TITLE
Datagrid stories: improve controls

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2270]
## What will this achieve?

Allow users to have more control over datagrid settings. Currently, the controls only use the `datagridState` but it provides no way view use cases and examples that the datagrid hooks provide.

## How will success be measured?

For each story, users should be able to view scenarios matching those described in the in [design specs](https://pages.github.ibm.com/cdai-design/pal/components/data-table/overview/).

## Additional information

- Designs
- Existing code
- etc

**Comment by elycheea** [comment]
This is a list of scenarios we should demonstrate in our stories but some of these may not require a separate story (e.g. alignment, truncation)

### Header
- [x] Default header w/ or w/o sublines
- [ ] Dense header w/ or w/o sublines
- Example with accordion headers??

For `PageHeader` or `Tabs` as table header, should double check accessibility.

### Settings
AKA Row height settings
- [ ] Rename to `Row height settings` or `Row size settings`
  - Overflow menu should align right
  - v11 should use Popover instead

### Row action buttons
- [ ] Overflow menu with more than 2 actions (including destructive action) -> `Sticky action column`
- [ ] Hover on row (with overflow or actions) -> `Is Hover on Row` uses text as example
- [x] Action buttons with 1-2 buttons
- [ ] Action buttons + batch actions (to show disabled in batch mode)

### Batch actions
- [x] Batch actions with more than 4 actions

Select all across all pages in the toolbar not implemented at this time (Carbon). More does not use caret yet due to limitations in ButtonMenu.

### Expandable rows
- [ ] Rename to `Expandable row`
  - Fix spacing shown with content
  - Border should be below expanded area — not above

### Nested rows
- [ ] Default rows
  - Expansion indicator is missing (should display on hover of parent row; hover on child should not show indicator)
  - Chevrons should be right/down not down/up
- [ ] Selectable rows
- [x] Multilevel nesting
- [ ] Selectable multilevel nesting
--
- Simple pagination — no option to select items on page
  - May not need an actual story, but should verify this works as expected

- [ ] Remove `Nested table` story

### Resizable columns
- Resizable columns
  - Individual column ✅ 
  - Double click to resize to fit — what about keyboard??
  - Multiple columns (visible only)
  - _Column header should wrap to two lines before truncating when header is long_
    - _compact data tables should keep to one line for truncation_
  - Should include label and icons (min-width shows icon only)
  - Column min-width of `1ch`?

Keyboard navigation may overlap with that of inline editing.

### Column customization
To be defined.

### Column alignment
- [x] Right aligned columns
- [x] Center aligned columns

Can either use the default basic table story or one alignment story
- [ ] Right aligned content should use numerical data in example
- [ ] Centered should use status icons or multi-part data (16:9, 4:3)

### Inline editing
To be defined.

### Clickable row items
- [ ] Clickable links (blue on hover, navigates to new page)
   - Should rewatch video from Marion, Michael G
- [x] Clickable rows (preview in page)
-  _Another story to allow side panel to open from row actions / overflow??_
- _Tooltips, tags, secondary links?? Tagset??)_

### Empty state
- [x] Empty state

### Scrolling
- [x] Two-line text wrapping (doesn’t need to be its own story)
- ~Truncation (with tooltips)~
- [-] Frozen columns; last (default), first column
  - Frozen first column should unfreeze below 672px

### Filtering
To be defined.

_Ability to handle thousands of entries._

**Comment by matthewgallo** [comment]
Adding a shortened list of extensions we need to add with it's own extension directory in storybook
- [X] Header
- [X] Settings (Row height settings)
- [X] Row action buttons
- [ ] Batch actions
- [X] Expandable rows
- [X] Nested rows
- [ ] Resizable columns
- [ ] Column customization
- [X] Column alignment
- [ ] Inline editing
- [ ] Clickable row items
- [ ] Empty state
- [ ] Scrolling
- [ ] Filtering

**Comment by elycheea** [comment]
@AlexanderMelox Most of these are covered in the design reviews, but keeping us on the hook to ensure we don’t miss anything.
