### ISSUE TITLE
CreateTearsheet initialStep not honored when mounted with open=true

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/ibm-cloud-cognitive#2287]
CreateTearsheet does not open to the initialStep when the component is mounted with open=true

Our application rehydrates state and needs to mount an open tearsheet that returns the user to a specific step.

## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Is this issue related to a specific component?

CreateTearsheet

> What did you expect to happen? What happened instead? What would you like to
> see changed?

CreateTearsheet should open to the step identified by initialStep. I believe it need to initialize its currentStep state value to `initialStep || 0`.

> What browser are you working in?

Chrome 105

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.7.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM System z Hardware Management Console

## Steps to reproduce the issue

1. Mount a CreateTearsheet with open=true and initialStep > 1

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

https://codesandbox.io/s/createtearsheet-initialstep-when-mounted-open-n9jjhm

Tearsheet is mounted with open=true and initialStep=4. On mount the tearsheet is open but the step is 1. If you close the tearsheet and click the "Open Tearsheet" button to re-open it, the tearsheet opens to step 4.

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-602c6543cd8ba2001cb5ed88/issues/carbon-design-system/ibm-cloud-cognitive/2287?planning-poker) with Zenhub @davidmenendez @matthewgallo @AlexanderMelox
