### ISSUE TITLE
Data table extension: Column customization should use Tearsheet

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2290]
## Data table extension: Column customization

Currently, column customization uses a modal (see [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--customizing-columns)). In the updated guidelines, column customization should occur through a narrow tearsheet[^1].

Some styling changes may also be addressed during this change:
- [x] Instructions need padding on right and should use _most likely_ `$text-05` / `$text-helper` (v11) — verify with designers
- [x] Fix search icon alignment in search bar; should be 16px from left edge
- [x] Fix clear icon in search bar — sizing and styles[^2]
- [x] Spacing after drag and drop icon looks like it should be larger
- [x] During search, drag and drop is disabled but visibly still looks active; `$disabled-02` / `$icon-disabled` (v11)?
- [x] Header row (Column name) should be bold and fix on scroll

Reach out to design maintainers with any questions.

### Design maintainers
- Ashley Bock
- Johanna Koval

[^1]: https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage#anatomy
[^2]: https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage#search

**Comment by matthewgallo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-602c6543cd8ba2001cb5ed88/issues/carbon-design-system/ibm-cloud-cognitive/2290?planning-poker) with Zenhub @AlexanderMelox @davidmenendez @elycheea
