### ISSUE TITLE
Data table extension: Nested rows fixes

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2291]
## Data table extension: Nested rows

- [x] Fix last border of in a set of nested children
- [x] Add expansion indicator for child rows that are also parent rows (only on hover — should verify with design maintainers)

From #2279, last border of nested row should reach all the way left on the data table.

> Also think the last border of the nested rows (or the top border of the next row) should reach all the way left on the data table based on the guidance. We can also check with the designers on the `$active-ui` color since that’s in the guidance, but the screenshot uses more of `$ui-03` (or `$border-subtle-01`).
>
> Current | Guidance
> --------|-----------
> ![image](https://user-images.githubusercontent.com/1717398/190686168-e7eff5c2-1ac0-4f4b-bbf6-5afa32e0f564.png) | ![image](https://user-images.githubusercontent.com/1717398/190686433-a09af1c6-72be-4247-a2ea-522a83dba7e6.png)

We may also need to check with design maintainers if expansion indicator should show for all parents (even if they are also children) for multiple levels of nesting. (e.g. should hovering the chevron of a child row that is also a parent show an indicator?)

## Design maintainers
- Ashley Bock
- Johanna Koval

**Comment by matthewgallo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-602c6543cd8ba2001cb5ed88/issues/carbon-design-system/ibm-cloud-cognitive/2291?planning-poker) with Zenhub @AlexanderMelox @davidmenendez @elycheea
