### ISSUE TITLE
SidePanel animation stuck on FireFox

### ISSUE THREAD

**Issue by benjambo13** [carbon-design-system/ibm-cloud-cognitive#2304]
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-side-panel-sidepanel--slide-over

When opening and the closing the side panel sometimes the panel will get stuck halfway and not open fully. It also consistently has this 'double animation' where it appears to slide out twice. I have observed this on FireFox v105.0.

![image](https://user-images.githubusercontent.com/47751764/191545890-2150a999-369d-4edd-8786-40a4b8f256c6.png)

**Comment by matthewgallo** [comment]
Thanks for opening this issue @benjambo13, I'll take a look and report back here with updates as I work on this.
