### ISSUE TITLE
InlineEdit refactor

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-cloud-cognitive#2310]
after investigating issue #2112 i've come to the conclusion that the only way to really fix the bug is to refactor the component. it's currently implemented using `<div contentEditable />` which doesn't behave well with react. the main problem being that any time the state updates the cursor moves to the start of the input. it's possible to keep this kind of implementation, but i don't think this is the best way to do it. using refs and ranges adds unnecessary complexity. switching to just using a text input will solve most of these problems and make maintaining this component a lot easier.

after doing some research it seems like `contentEditable` is really only suited for things like building text editors. and while the same problems that i mentioned above still exist, the main benefit is that using `contentEditable` is better suited for doing things like formatting text and styling it similarly to the way a text editor behaves. see [draft.js](https://draftjs.org/) for example

**Comment by lee-chase** [comment]
One reason to use `contenteditable` was to allow other tags e.g. h2 (as per comments in code). Not sure if this feature is used.

**Comment by elycheea** [comment]
Caught this on the v11 version of InlineEdit. You’ll probably see it when you’re working on the v2 PR anyway, but wanted to drop this here anyway.
<img width="363" alt="image" src="https://user-images.githubusercontent.com/1717398/193141653-5021f25b-79b0-4107-a0f5-aa8d453f6eef.png">
