### ISSUE TITLE
DataGrid Infinite Scroll is not invoking the function call to load more data on scroll

### ISSUE THREAD

**Issue by prudhvi2519** [carbon-design-system/ibm-cloud-cognitive#2355]
##  DataGrid with Infinite Scroll Component is not invoking the function call to load more data on scroll. 
Component Link : https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--infinite-scroll

-->

## What package(s) are you using?

- [ ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

As per the story book description, the implementation looks like below. The Function **fetchData** is not being invoked as expected on scroll to the bottom. This component does not work in the canvas aswell

```
const columns = React.useMemo(() => defaultHeader, []);
 const [data, setData] = useState(makeData(0));
 const [isFetching, setIsFetching] = useState(false);
  const fetchData = () =>
    new Promise((resolve) => {
      setIsFetching(true);
      setTimeout(() => {
        setData(data.concat(makeData(30, 5, 2)));
        setIsFetching(false);
        resolve();
      }, 1000);
    });
  useEffect(() => {
    fetchData();
  }, []);

  const datagridState = useDatagrid(
    {
      columns,
      data,
      isFetching,
      fetchMoreData: fetchData,
    },
    useInfiniteScroll
  );

  return (
    <Wrapper>
      <Datagrid datagridState={{ ...datagridState }} />
    </Wrapper>
);
```

> Is this issue related to a specific component?
 yes, https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--infinite-scroll

> What browser are you working in?
Chrome Version 105.0.5195.125

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive) :  "@carbon/ibm-products": "1.31.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

i work as a part of IBM Maas360. we are 2 and half weeks away from release and would like to have this component implemented in our workflow

## Steps to reproduce the issue

1. Try the story book link provided above, scroll to the end of the dataGrid. Notice that the component does not load additional data.
2. Implement a basic dataGrid with open source API's for testing. The results will be the same as above

**Comment by matthewgallo** [comment]
Complete
