### ISSUE TITLE
Single add select release review

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2366]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a
      useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been
      delivered and merged to main.
- [ ] Design maintainer has approved the implementation for those scenarios (via
      a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion
      and documented in release notes. Ideally deprecation notices in the prior
      major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and
      anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with
      Carbon-defined conventions and are consistent internally. Where there
      isn't an existing convention to apply, ensure robust precedents are being
      established.
- [x] The UI produced is accessible, responsive, translatable, cross-browser,
      and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [x] Public component supports a Devtools attribute
- [x] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title,
      aria-\*, etc) are passed through to an appropriate DOM node of the
      component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each
      public component SCSS is included in /src/components/\_index.scss, and
      each public component has a flag in package-settings.js.
- [x] Each public component SCSS lists all of the Carbon and C&CS components
      imported and used by the JavaScript code and explicitly imports the SCSS
      for each of these components.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies
      otherwise.
- [x] All components utilizing motion must include reduced-motion queries for
      accessibility purposes - read more here.
- [x] Code is formatted according to prettier rules (no use of
      //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the
      code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the
      appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate
      outputs.
- [x] The tests validate the behaviors and interactions defined in the design
      where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate
      and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for
      all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant
      props and actions, and additional usage documentation and code samples are
      available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox
      for the components.

**Comment by davidmenendez** [comment]
awaiting @AlexanderMelox notes

**Comment by AlexanderMelox** [comment]
Here are some issues I found

- [ ] Tabbing in safari and selecting doesn't seem to work
- [ ] When selecting with enter key and tab to the next one you cannot re select
- [ ] Don't see dev tools props [for example](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/471c46eaeb078df04372bf94b470e68ba9732293/packages/cloud-cognitive/src/components/WebTerminal/WebTerminal.js#L26)

**Comment by davidmenendez** [comment]
thanks @AlexanderMelox for going through the review process. here are some responses to your notes

> Tabbing in safari and selecting doesn't seem to work

lol you're right and apparently this is a know issue in safari. the fix is to select a special accessibility option in the safari settings https://github.com/adobe/react-spectrum/issues/2128#issuecomment-883017320

> When selecting with enter key and tab to the next one you cannot re select

i think this is the intended behavior for radio buttons. if you highlight the initial option you can switch between the options with the arrow keys.

> don't see devtool props

it's here https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/9555e779cb105e891135503c6b2c1b52b8607d44/packages/cloud-cognitive/src/components/SingleAddSelect/SingleAddSelect.js#L11

> Typo in tests

this is an issue on carbon's side. i will revisit it in the future.

> Seems SingleAddSelect only has 1 test, which is it renders. Don't know if this is correct?

yes most of the testing occurs in `AddSelect.test.js` the tests for the named exports for single and multi add select are just testing that they render when used. the nitty gritty happens in regular add select. this is actually something i've been thinking about and trying to figure out the best way to do testing for components like this. i may want to revisit this in the future.

> When the description is long, should this be truncated and have a title prop so the user can hover and read the text

noted! will fix

>  itemsLabel on storybook doesn't update the UI
> globalSearchLabel on storybook doesn't update the UI

strange. will investigate.

> No Docs or CodeSample on docs page

noted! will fix

**Comment by davidmenendez** [comment]
both of the sandbox links are ready. i know there's still some uncertainty about the sandboxes at the moment, so i just have them in my account.

https://codesandbox.io/s/multiaddselect-0jlbmr

https://codesandbox.io/s/singleaddselect-lky48h

**Comment by davidmenendez** [comment]
@AlexanderMelox the examples were added and all the other items should have been addressed. please review.

**Comment by AlexanderMelox** [comment]
Nothing crazy but the codesandbox got errors
https://codesandbox.io/s/singleaddselect-lky48h?file=/src/Example/Example.js
