### ISSUE TITLE
Multi add select release review

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2367]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a
      useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been
      delivered and merged to main.
- [x] Design maintainer has approved the implementation for those scenarios (via
      a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion
      and documented in release notes. Ideally deprecation notices in the prior
      major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and
      anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with
      Carbon-defined conventions and are consistent internally. Where there
      isn't an existing convention to apply, ensure robust precedents are being
      established.
- [x] The UI produced is accessible, responsive, translatable, cross-browser,
      and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [x] Public component supports a Devtools attribute
- [x] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title,
      aria-\*, etc) are passed through to an appropriate DOM node of the
      component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each
      public component SCSS is included in /src/components/\_index.scss, and
      each public component has a flag in package-settings.js.
- [x] Each public component SCSS lists all of the Carbon and C&CS components
      imported and used by the JavaScript code and explicitly imports the SCSS
      for each of these components.
     - [x] Imports updated accordingly for v11 branch

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies
      otherwise.
- [x] All components utilizing motion must include reduced-motion queries for
      accessibility purposes - read more here.
- [x] Code is formatted according to prettier rules (no use of
      //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the
      code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the
      appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate
      outputs.
- [x] The tests validate the behaviors and interactions defined in the design
      where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate
      and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for
      all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant
      props and actions, and additional usage documentation and code samples are
      available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox
      for the components.

**Comment by elycheea** [comment]
## Readiness
We’ll be expecting this final design approval soon and will update accordingly.

### Engineering review
Some props need descriptions.

**Comment by elycheea** [comment]
## Engineering review (cont.)
- Meaningful classes
   - The only class that I’m unsure about is `__tag-container` (and corresponding `__tag-container-label`. I see this is used both more globally and in the individual columns, but I think they feel a bit more hierarchical to be called only a tag container? Maybe they’re more of category labels?
   - For `-row-selected, -row-meta-selected` in the AddSelectList, I think these should actually be `--modifier`s in BEM? So maybe `-row--selected, -row-meta--selected`?

**Comment by davidmenendez** [comment]
aside from the issue with the accessibility tests failing due to carbon components, everything else has been updated 👍

**Comment by davidmenendez** [comment]
closing as complete. i will revisit the accessibility tests as soon as i have word from carbon. i'll open up a new issue to track that separately.
