### ISSUE TITLE
useInfiniteScroll limits DataGrid height to a fixed value lower than the Basic DataGrid's height

### ISSUE THREAD

**Issue by prudhvi2519** [carbon-design-system/ibm-cloud-cognitive#2371]
useInfiniteScroll limits DataGrid height to a fixed value.

-->

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The current default height is less than that of an ordinary DataGrid. Can we make the default height same across all the DataGrid implementations. Also, if possible can we introduce a parameter or a prop to the control the height of the DataGrid in infinite Scroll.

> Is this issue related to a specific component?

Yes, when using DataGrid with infiniteScroll Hook

> What did you expect to happen? What happened instead? What would you like to

Expecting the height to be same across various flavours of the DataGrid implementation. Better if this can be a controllable prop/ param that can be passed as needed

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM MaaS360, we intend to use DataGrid infinite scroll component in our product and the release is in next 2 weeks

## Steps to reproduce the issue

1. Create a basic DataGrid and observe the height
2. Add UseInfiniteScroll hook to the above created DataGrid and observe the height decreases

**Comment by matthewgallo** [comment]
Hey @prudhvi2519, the `virtualHeight` property has been added to control the height of the Datagrid when using `useInfiniteScroll`. This will be included in the next release.
