### ISSUE TITLE
Datagrid: filtering for an item that doesn't exist throws React error (2.0.0-rc3)

### ISSUE THREAD

**Issue by caleballen** [carbon-design-system/ibm-cloud-cognitive#2383]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [x] Legacy/Security

## Detailed description

Filtering for text that doesn't exist in the Datagrid causes the following React error, crashing the app
```
Unhandled Runtime Error

Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
```
This issue occurs using the Datagrid component in `@carbon/ibm-products@2.0.0-rc.3`

This component is being used for an IBM cloud offering with no imminent release but we wish to ensure that this issue is tracked somewhere.

## Steps to reproduce the issue

1. Load the Datagrid with some information
2. Search for data that doesn't exist in the Datagrid

**Comment by matthewgallo** [comment]
Hey @caleballen, thanks for documenting this issue. Would you be able to provide reproduce this bug in a code sandbox? I haven't seen this yet and have not been able to reproduce it myself. Thanks!

**Comment by caleballen** [comment]
Thanks @matthewgallo! Apologies, I'm unable to reproduce this error in a codesandbox, and have tracked it down locally now to the use of `next-18next` `useTranslation` strings within a custom DatagridPagination component passed into the Datagrid. Strangely this issue did not occur with `@carbon/ibm-products@2.0.0-rc.2` but appeared upon upgrade to `rc.3`.

I'll keep working to see if I can reproduce it in a sandbox but at present it seems like this is not actually a carbon bug!
