### ISSUE TITLE
[SidePanel] Moving the Header down after it's finished the open animation.

### ISSUE THREAD

**Issue by dkaushik95** [carbon-design-system/ibm-cloud-cognitive#2394]
Since this is happening in the storybook too, I'll post the link to the storybook here.

 As you can see from the screenshot. It's moving the title header section down and hiding a lot of data behind it. 
![Screen Shot 2022-10-21 at 10 47 06 AM](https://user-images.githubusercontent.com/8481567/197224095-e18a9b73-c1b9-4b60-96e1-b37985e80cf9.png)

I inspected and removed some elements from the header, this is the content it's hiding.

![Screen Shot 2022-10-21 at 10 49 05 AM](https://user-images.githubusercontent.com/8481567/197224666-a65277a9-bc0f-48dc-819f-ae9be487e04b.png)

For my case, it's hiding our tab window 

![Screen Shot 2022-10-21 at 10 50 41 AM](https://user-images.githubusercontent.com/8481567/197224809-1dd42c65-efd1-496d-8d0e-e8d4bbcb4874.png)

Here's the link to the storybook:
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-side-panel-sidepanel--with-static-title-and-action-toolbar

Workaround: Set `animateTitle={true}`

**Comment by matthewgallo** [comment]
Hey @dkaushik95, this will be fixed in tomorrow's release. As always, feel free to reopen/reach out if you're still experiencing any issues!
