### ISSUE TITLE
[useWindowScroll] Using PageHeader component causes the page to scroll at random times.

### ISSUE THREAD

**Issue by dkaushik95** [carbon-design-system/ibm-cloud-cognitive#2400]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive) `"@carbon/ibm-products": "^1.34.1",`
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
When I move away from a page with a pageheader and come back to the tab, I see something scrolls to top. After that, every time I interact with the UI components in the page, it always scrolls to the top. I investigated all our behaviors where we use the window.scrollTo function but it doesn’t seem to affect it. I looked at global listeners and found that useWindowScroll is causing the scroll to happen. When I remove the listener, my components starts to work fine.

> Is this issue related to a specific component?
`PageHeader` 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The page shouldn't scroll unless specified by a prop.

> What browser are you working in?
Chrome

### Important
On windows, the scroll behavior is even worse where it's scrolling on any user interaction.

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
"^1.34.1"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
CP4Waiops - DCUT November 2

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

- Screenshots or code

![Screen Shot 2022-10-20 at 6 00 25 PM](https://user-images.githubusercontent.com/8481567/197570964-aa040b0b-862f-4849-9c8b-20edbbfc8912.png)

- Notes

**Comment by matthewgallo** [comment]
The fix for this was delivered in `1.35.1`. @dkaushik95 Please feel free to reopen if you're still noticing this behavior after upgrading.
