### ISSUE TITLE
PageHeader: `title` truncation no longer being applied

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#2409]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I noticed that the title truncation in the PageHeader component is no longer being applied. I'm not sure when this stopped working, but when the page title is long enough it should truncate.
> Is this issue related to a specific component?

PageHeader
> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected the title to truncate if long enough.
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A
## Steps to reproduce the issue

1. View page header story with [long values](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--fully-loaded-and-some).

**Comment by elycheea** [comment]
@glapadre Do you think you can look into this?

**Comment by glapadre** [comment]
10-4!
