### ISSUE TITLE
Action bar clear is clearing search bar string

### ISSUE THREAD

**Issue by shankar343** [carbon-design-system/ibm-cloud-cognitive#2417]
Brief description:
Whenever we are selecting any row after filtering table through search bar, then after clicking 'Cancel' btn in action bar, search string is gone, but the table rows are not resetting to default.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Is this issue related to a specific component?
This issue is in DataGrid Component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expectation: Whenever we are clearing search bar string, table rows should come to default

> What browser are you working in?
All browsers

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
v 1.33.0

## Steps to reproduce the issue

Steps to produce:
- Type some filter string in table searchbar
- Select a row, action bar will come
- then click Clear.
- Now search string cleared, but filter Rows remain. Not going to default Rowdata

Can be seen in: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--selectable-row
## Additional information

- Screenshots or code
- Notes
<img width="527" alt="image" src="https://user-images.githubusercontent.com/30149749/199005138-1904dd6b-c0aa-459d-8d72-a8eed80800cd.png">
<img width="737" alt="image" src="https://user-images.githubusercontent.com/30149749/199005259-0ddf0cd1-a591-4a2c-88ed-a018993b9575.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/30149749/199005314-9d40296a-6022-499b-a580-5843e3cf6203.png">

**Comment by matthewgallo** [comment]
Hey @shankar343, this is fixed now and will be included in tomorrow's (Nov. 8) release. Let us know if you are still experiencing any issues after upgrading!
