### ISSUE TITLE
npm ERR! peer @carbon/colors@"^10.37.1" from @carbon/ibm-products@1.35.0

### ISSUE THREAD

**Issue by biapar** [carbon-design-system/ibm-cloud-cognitive#2419]
npm ERR! Could not resolve dependency:
npm ERR! peer @carbon/colors@"^10.37.1" from @carbon/ibm-products@1.35.0
npm ERR! node_modules/@carbon/ibm-products
npm ERR!   @carbon/ibm-products@"*" from the root project

**Comment by matthewgallo** [comment]
Hey @biapar, could you provide us with some more details here. Any chance you're using Carbon v11 and have some v10 packages still included? This could cause some build issues, similar to what you've shared above.

**Comment by biapar** [comment]
Hi, here the list of installed npm:

    "@azure/msal-browser": "^2.24.0",
    "@azure/msal-react": "^1.4.0",
    "@carbon/charts": "^1.6.1",
    "@carbon/charts-react": "^1.6.1",
    "@carbon/colors": "^11.6.0",
    "@carbon/elements": "^11.4.0",
    "@carbon/ibmdotcom-react": "^1.39.0",
    "@carbon/icons": "^11.4.0",
    "@carbon/pictograms-react": "^11.30.0",
    "@carbon/react": "^1.15.0",
    "@carbon/styles": "^1.4.0",
    "@carbon/themes": "^11.7.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.5",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.27.2",
    "carbon-addons-iot-react": "^2.150.0",
    "d3": "^7.6.1",
    "faker": "^6.6.6",
    "formik": "^2.2.9",
    "history": "^5.3.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.34",
    "querystring": "^0.2.1",
    "react": "^17.0.2",
    "react-avatar": "^5.0.3",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "react-use": "^17.4.0",
    "sass": "^1.52.1",
    "superagent": "^8.0.0",
    "web-vitals": "^2.1.4",
    "yuk": "^1.1.1",
    "yup": "^0.32.11"

**Comment by matthewgallo** [comment]
I see, thanks for this information. It looks like you're using Carbon v11, which means you'll need to use v2.x.x of `@carbon/ibm-products`. We have some migration details specific to our library [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/docs/guides/v2.md).

https://www.npmjs.com/package/@carbon/ibm-products/v/2.0.0-rc.5

**Comment by biapar** [comment]
Thanks. I'll try. Will be a one big IBM Carbon package ( and better documentation ) without various packages and various docs? I've install the IBM Cloud cognitive pack only to use the UserProfileImage component.

**Comment by matthewgallo** [comment]
So in Carbon v11, most of the core Carbon packages can all be consumed from `@carbon/react`. You will need to add our package `@carbon/ibm-products` separately however. The Carbon team has detailed a lot of these details on both their [migration site](https://carbondesignsystem.com/migrating/guide/develop) and the [v11 migration docs](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md).

**Comment by matthewgallo** [comment]
Feel free to reopen this issue if you are still experiencing any problems after using `@carbon/ibm-products: 2.x.x-rc.x`.
