### ISSUE TITLE
CreateFullPage component: impossible to Cancel after closing the confirmation modal by clicking outside of it

### ISSUE THREAD

**Issue by ashpc** [carbon-design-system/ibm-cloud-cognitive#2438]
Steps to reproduce
How do we reproduce the error you described above: (ex. below)

In the CreateFullPage component, press Cancel - the confirmation modal will appear.
image

Close the modal by clicking outside of it.

Try to press Cancel again - the confirmation modal won't be displayed.
<img width="1671" alt="Screen Shot 2022-11-03 at 7 47 22 PM" src="https://user-images.githubusercontent.com/1907155/199861482-4b8feeb5-cbf9-4478-9e35-1a639c30ebee.png">

Reproducible here: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createfullpage--create-full-page

**Comment by elycheea** [comment]
@jagathgj if you have bandwidth, do you want to take a look at this? If not, we can reassign to someone else.

**Comment by jagathgj** [comment]
@elycheea, I did a quick look at the issue. Create flows of FullPage(all) and Modals(Create Modal, Create Modal using dark theme) are seen as opened before clicking the open button. It shouldn't be open until the user clicks the open button.
