### ISSUE TITLE
Tooltip truncates for the Sidepanel toolbar buttons

### ISSUE THREAD

**Issue by murtdagi** [carbon-design-system/ibm-cloud-cognitive#2485]
If the tooltip is longer which is the case for some of the non-english languages, the tooltip for the Sidepanel toolbar action buttons are truncated as seen in the attached screenshot.

can we please have this fixed?

![image](https://user-images.githubusercontent.com/7819852/203297078-d86b8dc9-03d3-49ce-8043-c09447462593.png)

**Comment by elycheea** [comment]
@murtdagi We are closing this issue since it is working in our examples, but if you are still seeing this issue, feel free to reopen with a CodeSandbox so we can investigate further.

**Comment by murtdagi** [comment]
@elycheea Just realized that the tooltip truncates when the `animateTitle` is set to `true`.

**Comment by murtdagi** [comment]
@elycheea can you please reopen this issue for further investigation?

**Comment by elycheea** [comment]
@murtdagi Thanks for providing that additional information. We can look into this further.

**Comment by elycheea** [comment]
@murtdagi Wanted to follow up that `tooltipPosition` and `tooltipAlignment` have been exposed and the default alignment has been changed to `start` in the PRs that are linked above. Closing this as completed, but let us know if you still run into issues. 👋

**Comment by murtdagi** [comment]
Thanks @elycheea , will test this out soon and will let you know if i still see any issues.
