### ISSUE TITLE
`react-table` dependency not found using `@carbon/ibm-products`

### ISSUE THREAD

**Issue by olliepotter** [carbon-design-system/ibm-cloud-cognitive#2491]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I've installed `@carbon/ibm-products` into our project. After installing, then running our app I see this:
```
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/DataSpreadsheet/DataSpreadsheet.js 181:18-26
[start:app] export 'useTable' (imported as 'useTable') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/DataSpreadsheet/DataSpreadsheet.js 185:7-21
[start:app] export 'useBlockLayout' (imported as 'useBlockLayout') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/DataSpreadsheet/DataSpreadsheet.js 185:23-37
[start:app] export 'useColumnOrder' (imported as 'useColumnOrder') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/DataSpreadsheet/DataSpreadsheet.js 836:70-78
[start:app] export 'useTable' (imported as 'useTable') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/DataSpreadsheet/DataSpreadsheet.js 838:70-78
[start:app] export 'useTable' (imported as 'useTable') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useColumnOrder.js 9:15-29
[start:app] export 'useColumnOrder' (imported as 'useColumnOrder') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 44:24-37
[start:app] export 'useFlexLayout' (imported as 'useFlexLayout') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 44:70-86
[start:app] export 'useResizeColumns' (imported as 'useResizeColumns') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 44:142-152
[start:app] export 'useFilters' (imported as 'useFilters') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 44:154-169
[start:app] export 'useGlobalFilter' (imported as 'useGlobalFilter') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 44:171-180
[start:app] export 'useSortBy' (imported as 'useSortBy') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 44:182-193
[start:app] export 'useExpanded' (imported as 'useExpanded') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 45:27-40
[start:app] export 'usePagination' (imported as 'usePagination') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 45:42-54
[start:app] export 'useRowSelect' (imported as 'useRowSelect') was not found in 'react-table' (possible exports: __esModule)
[start:app]
[start:app] ERROR in ./node_modules/@carbon/ibm-products/es/components/Datagrid/useDatagrid.js 53:19-33
[start:app] export 'useTable' (imported as 'useTable') was not found in 'react-table' (possible exports: __esModule)
```
As we can see, all the errors are to do with the `react-table` package. 

I actually managed to fix this issue by installing `react-table` at version 6 as a separate dependency of our project too. 

I'm not sure if I've done something wrong here, but I think a dependency maybe wrong out of the box? Initially no `react-table` was installed into `node_modules` at all, but it is referenced in the package code, hence the error.

References to `react-table` can all be found in the error log above. 

> Is this issue related to a specific component?

Seems to be:
- DataSpreadsheet
- DataGrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I'd expect `react-table` (v6) to be installed as a sub-dependency when running `npm i --save @carbon/ibm-products`.

> What browser are you working in?
- Chrome
- Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`    "@carbon/ibm-products": "^1.37.0",`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Working on API Connect Analytics - looking to get this fixed in time for 10.0.5.3 now (not sure of dates currently, soon to release 10.0.5.2) so there is time but would love this fixed ASAP.

## Steps to reproduce the issue

1. Install `@carbon/ibm-products` into node react project.
2. Import any component and use it.
3. Run the app - see the build error.

**Comment by elycheea** [comment]
Do you still see this issue in 1.39.0?

Our latest CodeSandboxes are working.
https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/carbon-for-ibm-products/Datagrid

**Comment by olliepotter** [comment]
I will give version 1.39.0 a try, thanks for the codesandbox example.

**Comment by elycheea** [comment]
Hi @olliepotter! Wanted to followup and see if this issue was resolved.
