### ISSUE TITLE
`Card` component causing failed prop type

### ISSUE THREAD

**Issue by olliepotter** [carbon-design-system/ibm-cloud-cognitive#2492]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Trying to use an `<ExpressiveCard />` but when used I see the following in the console:
```
Warning: Failed prop type: Invalid prop `hasActions` of type `string` supplied to `CardHeader`, expected `boolean`.
CardHeader@http://localhost:3002/static/js/bundle.js:125469:17
./node_modules/@carbon/ibm-products/es/components/Card/Card.js/Card<@http://localhost:3002/static/js/bundle.js:125104:26
div
DashboardCards@http://localhost:3002/static/js/bundle.js:74536:7
div
Dashboards@http://localhost:3002/static/js/bundle.js:81191:80
div
Analytics@http://localhost:3002/static/js/bundle.js:72674:72
div
App@http://localhost:3002/static/js/bundle.js:73115:64
```

> Is this issue related to a specific component?

I'm using `<ExpressiveCard />` but it actually seems to do with `<Card />` which is used by ExpressiveCard?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I don't expect to see a failed prop type.

> What browser are you working in?

- Chrome
- Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`    "@carbon/ibm-products": "^1.37.0",`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

API Connect Analytics - Looking to have fixed for 10.0.5.3 but we're only just releasing 10.0.5.2 (apologies for lack of dates).

## Steps to reproduce the issue

1. Use an `<ExpressiveCard />` in a react app and look at browser console.
2. See the failed prop type.

**Comment by davidmenendez** [comment]
hey @olliepotter thanks for reaching out. i'm unable to replicate this behavior. can you provide a snippet of the code you're using?

**Comment by davidmenendez** [comment]
@olliepotter apologies, i was able to recreate this and i have a fix incoming 👍

**Comment by olliepotter** [comment]
Awesome thank you!

**Comment by olliepotter** [comment]
Can confirm that the issue is all gone :)
