### ISSUE TITLE
Datagrid - React hook error

### ISSUE THREAD

**Issue by holmansze** [carbon-design-system/ibm-cloud-cognitive#2498]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

I recently updated @carbon/ibm-products from `1.22.0` to `1.37.0` and noticed a regression. I saw the following in my local dev env.

![image](https://user-images.githubusercontent.com/30137991/204570735-44c5505a-a313-4f55-952e-199ae274a7e9.png)

We use Datagrid heavily in the Projects UI. Projects will have a beta release in about a week.

## Steps to reproduce the issue

1. Consume Datagrid in a UI
2. Load the UI
3. See the error in the browser console

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

This is one example of how we use Datagrid:

```
  const datagridState = useDatagrid(
    {
      columns,
      data: rows,
      emptyStateTitle: t('...'),
      emptyStateDescription: t('...'),
      emptyStateSize: 'lg',
      illustrationTheme: 'light',
      refresh: () => refetch(...),
      rowActions: [
        {
          id: 'delete',
          itemText: t('...'),
          isDelete: true,
          icon: TrashCan16,
          onClick: onDelete,
          className: '...',
        },
      ],
      isFetching: loading,
      DatagridActions,
      initialState: {
        sortBy: [{ id: '...', desc: false }],
      },
      globalFilter,
    },
    useActionsColumn,
    useStickyColumn,
    useSortableColumns
  );

  <Datagrid datagridState={datagridState} />
```

**Comment by elycheea** [comment]
Might be related to #2345 but we’ll need to investigate if there are additional instances where we need to address this.

**Comment by matthewgallo** [comment]
This will be resolved in the upcoming release
