### ISSUE TITLE
Datagrid design review: Column customization

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2504]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Virginia Nicholson
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization)

---

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern
      maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
Should also discuss this design for #2465

**Comment by elycheea** [comment]
- Issue has already been opened to change modal to Tearsheet #2290.
- Search icon alignment in customize modal/tearsheet
- “Column name” should be bolded
- Spacing after drag icon ~16px; spacing between checkbox and text should be ~12px for better balance between elements
- Modal/tearsheet description width should use 75% max-width
    > ![image](https://user-images.githubusercontent.com/1717398/207423129-2598d246-ee5c-43a9-843f-9c1b86723399.png)

**Comment by Ashley-Bock** [comment]
- While dragging item back to original location, icons sometimes become stacked: 
<img width="414" alt="Screenshot 2022-12-13 at 1 08 04 PM" src="https://user-images.githubusercontent.com/120116973/207423437-51f20b52-5a5c-403c-80c0-52ccea28847c.png">
