### ISSUE TITLE
Datagrid design review: Actions dropdown

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2508]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Virginia Nicholson, Ashley Bock, Laura Marshall (@Laura-Marshall)
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--datagrid-actions-toolbar) (actually in several of the stories)

---

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by Ashley-Bock** [comment]
1. Button doesn't work on first click, but works as expected on second click

**Comment by Ashley-Bock** [comment]
2. Button should use chevron in storybook to be clear.

**Comment by Ashley-Bock** [comment]
3. Drop-down row height should be the same height as the button.

**Comment by Ashley-Bock** [comment]
4. Menu option background should use the ui-02 background to match other opening sections (filters, settings)

**Comment by Ashley-Bock** [comment]
5. Rename label in storybook to Actions Drop-down to be easier to find (all naming needs to be revisited)
