### ISSUE TITLE
Color Dependency: Cannot use 'in' operator to search for '0' in rgb

### ISSUE THREAD

**Issue by akhandsi** [carbon-design-system/ibm-cloud-cognitive#2512]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
While building a hybrid application with both AngularJs and React using webpack 5,  `"@carbon/ibm-products": "2.0.0-rc.8"` causes an issue with transpiling colors/index.js as shown in the screenshot.

![Screen Shot 2022-11-29 at 3 39 46 PM](https://user-images.githubusercontent.com/8444514/204885527-c331bc23-1d1d-4e94-bd24-a2891830f7f5.png)

The issue seems to be related to how this library handles esm resolution.  https://github.com/Qix-/color/issues?q=.

> Is this issue related to a specific component?
Stack trace shows PageHeader.js to originate this issue.

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
2.0.0-rc.8

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
This is blocking the upgrade to Carbon V11 for the Turbonomic IBM Product.

- Notes
This may be related to how we are bundling and possibly not easy to reproduce on other systems.  If that is the case, please let me know and we can get on a call to show our build configurations.

**Comment by akhandsi** [comment]
@matthewgallo unfortunately the slackblitz that I created did not work. It's mostly how we are bundling our application as commonJS module that could be causing this issue.

Interestingly I did notice that @carbon/themes use color as `"color": "^4.0.0"` instead of locking to a specific version. 

After researching it seems like downgrading colors from 4.2.3 to 4.2.1, fixes this issue. I found this helpful while I researched https://github.com/Esri/calcite-components/issues/4481.

Do you see any problem with downgrading?

**Comment by akhandsi** [comment]
The Turbonomic UI team downgraded Color to 4.2.1 and this error has gone. 

`"resolutions": {
      "color": "4.2.1"
  },`
  
  Feel free to close this issue.

**Comment by matthewgallo** [comment]
Ok, that seems like a reasonable solution. I'm noticing now this is stemming from the `@carbon/themes` package as indicated in your comment from last week, I would open an issue in the main Carbon [repo](https://github.com/carbon-design-system/carbon/issues/new/choose) for any further investigation.
