### ISSUE TITLE
Update on v11 timeframe / eta?

### ISSUE THREAD

**Issue by tlawrie** [carbon-design-system/ibm-cloud-cognitive#2515]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

Is there any update on when v11 of IBM Products for Carbon React will be released that also doesn't use the carbon-components-react import?

**Comment by tlawrie** [comment]
any chance we could get a `next` tag of the component library?

**Comment by matthewgallo** [comment]
Hey @tlawrie, following up from our slack thread.

We have a release candidate version of [v2.x.x](https://www.npmjs.com/package/@carbon/ibm-products/v/2.0.0-rc.8) which includes support for Carbon v11 that is currently available to use. This also means that component imports are coming from `@carbon/react`, which sounds like what you're describing above.

Our v1 and v2 receive releases weekly ([04:30 UTC](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/.github/workflows/release.yml#L6)) and our team is working towards a 2023 1H stable release of v2. If you have additional questions feel free to reach out!

**Comment by tlawrie** [comment]
Thanks @matthewgallo - we are using Remix with Carbon v11 and planning to use the CreateFullPage from that IBM-Products v2. Will let you know if we hit any roadblocks.

FYI @M-Verhoosel-EY @fahadahmed
