### ISSUE TITLE
Datagrid: inline edit extension with `isFetching` property causes error

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#2545]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

When using inline edit Datagrid with the `isFetching` property, an error is thrown because `value.text` is undefined at that point. Adding an optional chain (ie `value?.text`) should easily fix this issue.
> Is this issue related to a specific component?

Datagrid (inline edit)
> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected no errors using inline edit with the `isFetching` property.
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A

**Comment by georgespano** [comment]
As part of this work, one other small suggestion that would help with our modelling structure is to have the inline edit drop down able to support items defined simply by an array of strings: items: ["item1", "item2", "item3"]. The drop down component supports this already, but a small change would still be required to remove the assumption that each item has a text field in it. In InlineEditCell file the method renderDropdownItem can be changed in these areas:

```
const renderDropdownItem = (item) => {
    const includesIcon = !!item?.icon;
    return includesIcon ? (
      <>
        {React.createElement(item.icon)}
        <span className={cx(`${blockClass}__inline-edit--select-item`)}>
          **{item?.text}**
        </span>
      </>
    ) : (
      **item?.text**
    );
  };
```

Also the label parameter for the InlineEditButton would need a small change:

```
label={
            type === 'selection'
              ? **value.text**
              : type === 'date'
              ? buildDate(value)
              : value
          }
```

**Comment by matthewgallo** [comment]
Complete, will be included in next release
