### ISSUE TITLE
Runtime erro IdeSlideOverPanel

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#257]
I see this on storybook load

![image](https://user-images.githubusercontent.com/15086604/101165079-f5312900-362d-11eb-8346-2cc8b32269f0.png)

and this when I display an IdeSlideOverPanel story

![image](https://user-images.githubusercontent.com/15086604/101165309-578a2980-362e-11eb-8277-bcb0058eaa94.png)

**Comment by andrea-gm** [comment]
Are there plans to fix this bug?

**Comment by andrea-gm** [comment]
@asfordmatt @vladbalanescu if no plan to fix, can we close this issue?
