### ISSUE TITLE
Datagrid Inline edit: date option only accepts Date object

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#2577]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The Carbon `DatePicker` component also accepts strings and is able to render the date. The Datagrid inline edit component only works with Date objects and should be updated to accept strings as well.
> Is this issue related to a specific component?

Datagrid, specifically the `InlineEditCell.js` component, change would need to be made [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js#L400-L414).
> What did you expect to happen? What happened instead? What would you like to
> see changed?

If my data set includes dates as strings, they should be able to work just the same as Date objects.
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A
## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
Linking to this comment to make sure I don’t accidentally close this issue before we review if we can refactor some things to support entering dates as strings. 😅 

https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2592#pullrequestreview-1238293689
