### ISSUE TITLE
I see this on loading IdeButton in storybook

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#258]
I see this when viewing an IdeButton story. 

![image](https://user-images.githubusercontent.com/15086604/101165402-80122380-362e-11eb-951c-bcbd01b5bb49.png)

Suggest fixing by
- Adding and documenting prop size
- Passing size as a prop as follows 
```
size={size ? size : small ? 'size="sm"' : null}
```

**Comment by andrea-gm** [comment]
Any update on this bug?

**Comment by andrea-gm** [comment]
@asfordmatt @vladbalanescu any plans to fix? if not, can I close this issue?
