### ISSUE TITLE
DatagridContent element type is invalid

### ISSUE THREAD

**Issue by Billzg13** [carbon-design-system/ibm-cloud-cognitive#2610]
## What package(s) are you using?

```
"@carbon/charts": "1.6.1",
"@carbon/charts-react": "1.6.1",
"@carbon/ibm-products": "2.0.0-rc.10",
"@carbon/react": "1.19.0",
```

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Trying to use a Datagrid component in my app and it breaks on runtime.

I created a fresh react app with these dependencies:
```
"dependencies": {
    "@carbon/charts": "1.6.1",
    "@carbon/ibm-products": "2.0.0-rc.10",
    "@carbon/react": "1.19.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "5.0.1",
}
```
that builds with `react-scripts` and Datagrid also fails there with the same error.

I would expect `Datagrid` to work with the default webpack configuration, like the rest of  `ibm-product` components. Is there a special configuration required in order to make this work?

> Is this issue related to a specific component?

Yes **Datagrid**

> What did you expect to happen? What happened instead? What would you like to
> see changed?

We were able to find what causes the issue, it is the way DataTable is imported.
For example, at DatagridContent.js file this is how DataTable is de-structured:

```
import { DataTable} from '@carbon/react';

const { TableContainer, Table } = DataTable; <--- TableContainer and Table are undefined
```

Making this change at all the places where DataTable is imported solves the issue.

```
import { TableContainer, Table} from '@carbon/react';
```

> What browser are you working in?

Google chrome

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

I am working on `Turbonomic ux-app` project

## Steps to reproduce the issue

1. Try to use a Datagrid component with any configuration with  `react-scripts`

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

### Console errors

![Screenshot from 2023-01-05 16-30-56](https://user-images.githubusercontent.com/36958390/212064069-21c53716-5a04-4020-a063-453ed0ca416d.png)
![Screenshot from 2023-01-05 16-31-14](https://user-images.githubusercontent.com/36958390/212064072-0a80278f-2721-48e7-b63e-98fc3b890fd3.png)
![Screenshot from 2023-01-05 16-31-27](https://user-images.githubusercontent.com/36958390/212064077-3f3b5f93-1b99-42f0-9e03-1a839b9ab7f9.png)

### Code example

> Not the actual code but this code also throws the same error

![Screenshot from 2023-01-09 17-59-16](https://user-images.githubusercontent.com/36958390/212063926-35cf5675-c9f4-41b2-b9bc-4074586bf6f6.png)

### Possible fix

> Cloned the repo and replaced all the places where Datagrid is imported like this

![image (1)](https://user-images.githubusercontent.com/36958390/212063876-529865c2-d512-422d-879d-29a4175903f1.png)

**Comment by rakeshmusturi** [comment]
Can anyone please take this at priority and give us a fix

**Comment by vnikiten01** [comment]
Any target version of due date of when this might be fixed.  Currently my team is having to build a custom carbon-ibm-product library with proposed fix in order to be able to work with datagrid.

**Comment by AlexanderMelox** [comment]
@vnikiten01 We are looking into a fix now.

**Comment by AlexanderMelox** [comment]
@vnikiten01 @Billzg13 @rakeshmusturi 
Upgrade your Carbon form IBM Products to ` "@carbon/ibm-products": "^2.0.0-rc.17",`.
I'm seeing the fixes on my end 🙂
