### ISSUE TITLE
HTTP Error components not as per design?

### ISSUE THREAD

**Issue by chrisdudley** [carbon-design-system/ibm-cloud-cognitive#262]
Apologies if I'm missing something, but should the HTTPError components (https://ibm-cloud-cognitive.netlify.app/?path=/story/cd-ai-idehttperrors--default) look like the design here (https://pages.github.ibm.com/cdai-design/pal/patterns/http-errors/usage/ ) ?

Are they a WIP ? Or am I looking at an old design site?

**Comment by andrea-gm** [comment]
No, you are right, the illustrations are different in the design. I believe it was updated sometime after the implementation was done.

**Comment by andrea-gm** [comment]
@matthewgallo if this is low hanging fruit, do you think you could prioritize it to be done in the next week or so?

**Comment by andrea-gm** [comment]
Wait...... this looks done in the storybook??? did we forget to close this issue lol

**Comment by matthewgallo** [comment]
Yes, just finished adding the two other versions (404 and other). All three should be in the storybook now, I forgot to link my PR to this issue!
