### ISSUE TITLE
Unable to open Button Menu upwards

### ISSUE THREAD

**Issue by murtdagi** [carbon-design-system/ibm-cloud-cognitive#2635]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
Yes, `ButtonMenu`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expect the ButtonMenu to open upwards when its being used a the bottom of the page

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
CP4WAIOps

## Steps to reproduce the issue

1. Use the ButtonMenu at the bottom of the page and you will see the issue

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
You should be able to pass in `direction="top"` to achieve this.

```jsx
<ButtonMenu
  label="Primary button"
  renderIcon={ChevronUp16}
  direction="top"
>
  ...
</ButtonMenu>
```

Hope this helps!

**Comment by murtdagi** [comment]
Yes that works, thanks a lot @elycheea
