### ISSUE TITLE
Datagrid: Unable to import FilterFlyout

### ISSUE THREAD

**Issue by K-Markopoulos** [carbon-design-system/ibm-cloud-cognitive#2636]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I cannot import [FilterFlyout](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/FilterFlyout.js) component in my DatagridActions custom component, like in the DatagridActions [example](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js)

> Is this issue related to a specific component?

Yes, Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

This component seems like the indented way to use filters in datagrid, so I would expect it to available for use
- either through import, like it is used in the DatagridActions [example](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/Datagrid/utils/DatagridActions.js)
- or through the datagridState, like `CustomizeColumnsButton` is used.

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

```
"@carbon/charts": "1.6.1",
"@carbon/charts-react": "1.6.1",
"@carbon/elements": "11.17.0",
"@carbon/ibm-products": "2.0.0-rc.10",,
"@carbon/react": "1.19.0",
```

## Additional information

NA

**Comment by AlexanderMelox** [comment]
Solved in #2639 , #2638 🚀
