### ISSUE TITLE
Tearsheet: Description text wraps mid-word without hyphens

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-cloud-cognitive#2637]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The description text passed to a `Tearsheet` will automatically be wrapped by component mid-word and without hyphens leading to wrong breaks.

> Is this issue related to a specific component?

`Tearsheet`

> What browser are you working in?

Chrome 109

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`@carbon/ibm-products@1.41.3`

## Steps to reproduce the issue

Open storybook, resize window if necessary so that the description text wraps.
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--tearsheet

## Additional information
<img width="773" alt="Screenshot 2023-01-31 at 12 19 40" src="https://user-images.githubusercontent.com/28265588/215747146-a0e6a4e7-f3b4-4310-95e6-743d18c8bceb.png">

**Comment by elycheea** [comment]
I noticed this too when I was working on #2504. I have a fix in the branch but probably better to fix this in isolataion.
