### ISSUE TITLE
[Datagrid] FilterPanel enhancements

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#2651]
These are some enhancements that were delegated after the initial PR of `FilterLeftPanel`.

- [ ] [ Accordion tag count](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2627)
- [x] When scrolling the filter panel, a 1px divider line should show where the sticky part is. 
- [ ] Checkbox view all button.
  <img width="327" alt="Screenshot 2023-02-03 at 11 20 01 AM" src="https://user-images.githubusercontent.com/12755042/216653645-b0e10d69-acb7-4381-9322-087136949792.png">
  <img width="741" alt="Screenshot 2023-02-03 at 11 22 49 AM" src="https://user-images.githubusercontent.com/12755042/216654315-095876dc-fb11-4030-b2ab-cd3fbd9ede89.png">

- [ ] Filter search. [Link to design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters/#search)

**Comment by elycheea** [comment]
In refinement call on Feb 16, we agreed we should break this one down into more granular issues for sizing.

**Comment by AlexanderMelox** [comment]
Opened separate issues for all the tasks.
