### ISSUE TITLE
[Bug]: Codesandbox ModuleNotFound 'react-dnd'

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#2655]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When opening codesandbox to view a C4P component we are greeted with this error.
```
ModuleNotFoundError
Could not find module in path: 'react-dnd' relative to '/node_modules/@carbon/ibm-products/es/components/Datagrid/Datagrid/addons/CustomizeColumns/Columns.js'
▶ 43 stack frames were collapsed.
$csb$eval
/src/index.js:3
  1 | import React from "react";
  2 | import { render } from "react-dom";
> 3 | import { pkg } from "@carbon/ibm-products";
  4 | 
  5 | // This example uses this CSS build to minimize CodeSandBox transpile times
  6 | import "@carbon/ibm-products/css/index-full-carbon.css";
View compiled
▶ 6 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```
> Is this issue related to a specific component?

All components

> What browser are you working in?

Google chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`1.42.1`

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/singleaddselect-lky48h

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
Not seeing this in CodeSandbox now so hopefully this is now resolved.
