### ISSUE TITLE
[SingleAddSelect] Component not rendering with Carbon v11

### ISSUE THREAD

**Issue by nmgokhale** [carbon-design-system/ibm-cloud-cognitive#2663]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

`SingleAddSelect` component doesn't render for Carbon v11. Please refer to this sandbox recreating the issue - https://codesandbox.io/s/sad-wood-tctnom?file=/package.json:83-448
Seeing error in console -
```
React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'current')
 at handleStackChange.checkFocus (TearsheetShell.js:156:80)
    at eval (TearsheetShell.js:172:17)
    at Array.forEach (<anonymous>)
    at notify (TearsheetShell.js:170:24)
    at eval (TearsheetShell.js:185:7)
```
Also seeing a lot of warnings because of conflict in `@carbon/react` and `carbon-components-react` packages.
```
WARNING in ./node_modules/@carbon/ibm-products/es/components/WebTerminal/WebTerminal.js 117:16-20
export 'Help16' (imported as 'Help') was not found in '@carbon/icons-react' (possible exports:

ERROR in ./node_modules/react-dnd/dist/esm/core/DndProvider.mjs 28:0-51
Module not found: Error: Package path ./jsx-runtime.js is not exported from package /node_modules/react (see exports field in /node_modules/react/package.json)

webpack 5.75.0 compiled with 1 error and 124 warnings in 18034 ms
```

> Is this issue related to a specific component?

Yes. SingleAddSelect component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Component should render with Carbon 11. There shouldn't be any conflict in `@carbon/react` dependencies
> What browser are you working in?

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
```
"@carbon/icons-react": "^11.10.0",
    "@carbon/pictograms-react": "^11.37.0",
    "@carbon/react": "1.21.0",
    "@carbon/elements": "11.19.0",
    "@carbon/ibm-products": "^1.42.1",
    "carbon-components": "^10.58.3",
    "carbon-components-react": "^8.22.0",
    "carbon-icons": "7.0.7",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.56.1"
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

We would like to use this component in our project. Customer demo scheduled in upcoming weeks.

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/sad-wood-tctnom?file=/package.json:83-448

**Comment by nmgokhale** [comment]
CC: @davidmenendez

**Comment by davidmenendez** [comment]
hey @nmgokhale i believe the issue is related to the package.json file. take a look at this sandbox i made based on yours. i was able to get everything running by using the carbon v11 scaffolding https://codesandbox.io/s/blue-bush-kn14xw?file=/package.json

**Comment by nmgokhale** [comment]
Thanks @davidmenendez. SingleAddSelect component renders after using `"@carbon/ibm-products": "^2.0.0-rc.4",`.
All the warnings in console are gone after removing `carbon-components` and `carbon-components-react` from package.json.

Closing this issue.
