### ISSUE TITLE
<AVT1>An explicit ARIA 'role' is not valid for <th> element within a ARIA role 'table' per the ARIA in HTML specification

### ISSUE THREAD

**Issue by zhanttbj** [carbon-design-system/ibm-cloud-cognitive#2753]
===== ENVIRONMENT =====
Browser: Version 110.0.1
Test Tool Type: IBM Accessbility Checker

===== DEFECT DESCRIPTION ===== 
An explicit ARIA 'role' is not valid for element within a ARIA role 'table' per the ARIA in HTML specification

=====STEPS TO REPRODUCE =====

Login https://dev.console.test.cloud.ibm.com/projects with with IBM ID & password
Check accessibility

===== EXPECTED RESULT =====
IBM 4.1.2 Name, Role, Value
https://www.ibm.com/able/requirements/requirements/#4_1_2

For all user interface components (including but not limited to: form elements, links, and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.

===== SCREEN CAPTURE =====
<img width="825" alt="image" src="https://user-images.githubusercontent.com/110212663/226540186-202c2b2f-c239-4054-b4ca-4c2be69aca18.png">

**Comment by zhanttbj** [comment]
This is from https://github.ibm.com/ibmcloud/projects-ui/issues/646, pls help to check and fix, thanks

**Comment by elycheea** [comment]
@Ratheeshrajan Can you take a look into this issue?

**Comment by zhanttbj** [comment]
Hi Team, can we have this issue fixed by end of April? thanks

**Comment by Ratheeshrajan** [comment]
Closing as #2882 and #2883 merged.
