### ISSUE TITLE
Buttons in the Tearsheet are not accessible with tab in Safari 

### ISSUE THREAD

**Issue by mastourehh** [carbon-design-system/ibm-cloud-cognitive#2785]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Safari
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
> https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--tearsheet

> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Hey @mastourehh, I'm not sure if this is something that has changed in Safari recently or not but if you open your Safari preferences, then go to the "Advanced" tab, and check "Press Tab to highlight each item on a webpage", it should allow the buttons to be focusable.
![Screen Shot 2023-04-04 at 4 27 07 PM](https://user-images.githubusercontent.com/10215203/229913112-4ff69eac-624c-426e-8196-d3fe703c2b2d.png)

If this doesn't fix things for you, feel free to reopen!
