### ISSUE TITLE
[DataGrid] Checkbox moving at column customization

### ISSUE THREAD

**Issue by youngjunekoh** [carbon-design-system/ibm-cloud-cognitive#2820]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

> Is this issue related to a specific component? `DataGrid`

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using? `"@carbon/ibm-products": "1.46.2"`

## Steps to reproduce the issue

1. use a DataGrid with check boxes and `useCustomizeColumns`
2. load the page (see the check boxes are aligned to the left as they should be)
![Screen Shot 2023-04-05 at 12 38 08 PM](https://user-images.githubusercontent.com/60585804/230149101-a58e854e-9ebb-4bc8-87bf-ab440db51f54.png)

3. customize the columns and save
![Screen Shot 2023-04-05 at 12 38 21 PM](https://user-images.githubusercontent.com/60585804/230149180-267bca3e-b7d7-4ebd-b9cb-dd92936f4196.png)

4. see that the check boxes have moved to the left
![Screen Shot 2023-04-05 at 12 38 35 PM](https://user-images.githubusercontent.com/60585804/230149292-4076c56a-7be0-464b-864b-2cd00262d9d7.png)

**Comment by matthewgallo** [comment]
Hey @youngjunekoh, the PRs above should fix this issue with the row selection checkboxes after reordering columns. You'll be able to see these changes in the next release.

**Comment by matthewgallo** [comment]
Fixed in `v1.48.0`, feel free to reopen if you still see any related issues!
