### ISSUE TITLE
Datagrid initialState filters does not retain selected values in the filter panel

### ISSUE THREAD

**Issue by joyful-these** [carbon-design-system/ibm-cloud-cognitive#2838]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

With the Datagrid, I want to be able to set initial filters, like so:
```
  const datagridState = useDatagrid({
    initialState: {
      filters: initialFilters
    }
```
With the initialFilters set in the initialState, the filter tags appear as expected in the filter summary. However, the filters do not show as selected in the filter panel.
![Screenshot 2023-04-06 at 1 11 10 PM](https://user-images.githubusercontent.com/108295261/230449018-51dfbca8-99ef-4354-a58f-a86beee287a5.png)

This seems to be caused by the [useFilters hook](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/hooks/useFilters.js), here:
```
  /** State */
  const [filtersState, setFiltersState] = useInitialStateFromFilters(
    filters,
    variation
  );
```
The useInitialStateFromFilters calls [getInitialStateFromFilters](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/Datagrid/Datagrid/addons/Filtering/utils.js), which clears the selected value of the checkbox inputs.

So, instead of automatically clearing the filters values upon loading, it should use the selected values from the initialFilters.

----

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.46.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

For HDM Policy UI content, using the Datagrid for a release in June.

**Comment by AlexanderMelox** [comment]
@elycheea This is a very important aspect to have in filters since some teams have preselected filters from the url and it works nicely with react table.
