### ISSUE TITLE
Improve focus state of user profile image

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2839]
From the [user profile image](https://github.ibm.com/CDAI-design/pal/issues/1154) migration design reviews —

The focus ring around the user profile image is very thing and can be difficult to distinguish on some colors of the `UserProfileImage`.

![image](https://user-images.githubusercontent.com/1717398/230484373-57c22875-5ecc-4dc2-9ad0-30318e8dac94.png)

**Comment by davidmenendez** [comment]
![profile-focus](https://user-images.githubusercontent.com/6370760/232112258-5cf6a064-2710-4b70-91c2-f380a6a32e49.gif)

how's this?

**Comment by davidmenendez** [comment]
visual changes approved by shaun 👍
