### ISSUE TITLE
[DataGrid] custom rendered cells should not act with onRowClick if the cell is rendering an interactive component

### ISSUE THREAD

**Issue by youngjunekoh** [carbon-design-system/ibm-cloud-cognitive#2843]
## What will this achieve?

When we run the `useOnRowClick` hook and `onRowClick` function, we get the row information, but we have some cells which shouldn’t open the side panel as they are interactive. It would be helpful if we can get the event to figure out which element in the row was selected and the side panel open on conditions

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

> Is this issue related to a specific component? `DataGrid`

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using? `"@carbon/ibm-products": "1.46.2"`

Any personal questions feel free to find my username here (my name) from github and search me on w3 (you will find my slack there) :)

**Comment by matthewgallo** [comment]
Hey @youngjunekoh, this has now been added and will be included in the next release.

**Comment by matthewgallo** [comment]
Released in `v1.49.0`.
