### ISSUE TITLE
Inline edit v2: Fix icon size and icon buttons

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2852]
From the [edit and update](https://github.ibm.com/CDAI-design/pal/issues/1156) migration design reviews —

- [ ] Inline edit should use size 16 icons
  - Current icon size look too big
- [ ] Icon button should be square (consistent with icon only buttons)
  - Might be resolved with icon size fixes? 🤞

**Comment by lee-chase** [comment]
Fixed by #2858
