### ISSUE TITLE
`ColumnCustomization` and `RowHeightOptions` tooltip position should be `bottom`

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#2868]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

The tooltips are currently positioned to the left and should be placed to the bottom so it doesn't cover up any other action buttons.
<img src="https://user-images.githubusercontent.com/12755042/231805409-8c1d18be-3463-4111-940a-6b498cc0c1ce.png" />

> Is this issue related to a specific component?
Datagrid, ColumnCustomization and RowHeights

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected the tooltip to be at the bottom

> What browser are you working in?

Chrome

**Comment by matthewgallo** [comment]
It seems like this would be a good scenario to use the `ToggleTip` but you don't get a tooltip on hover.

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2873
