### ISSUE TITLE
DataTable additional capabilities

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#29]

**Comment by lee-chase** [comment]
No UX/Visuals or design maintainer, marking as blocked until provided.

**Comment by andrea-gm** [comment]
@SimonFinney @lee-chase Is this meant to be the DataTable extension pattern being worked on by @pascal-potvin and the data table guild?

**Comment by SimonFinney** [comment]
It was created using a seed list back in July so it could be the same, but the thinking could be out of date - I recommend closing this and creating a new issue when the design is no longer under review.
