### ISSUE TITLE
Tearsheet: add first focusable element

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2923]
In v2, first focusable element in the Tearsheet requires two tabs. In CreateTearsheet, we do allow users to set initial focus. This should be moved to the base Tearsheet.

> i was looking into this issue and it's definitely doable as is, but the problem is with create tearsheet. there's no good way to enable the focus functionality in tearsheet without it impacting the already built in focus functionality in create tearsheet. my recommendation is to **pull out the focus functionality in create tearsheet and create a general focus function in tearsheet**.

_Originally posted by @davidmenendez in https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2783#issuecomment-1520757311_

**Comment by elycheea** [comment]
@davidmenendez let’s verify if `selectorPrimaryFocus` in Tearsheet resolves the issue and also verify if this is the intended behavior.

@matthewgallo suggested Tearsheet follows an opt in approach for first focus.

**Comment by davidmenendez** [comment]
confirmed that passing `selectorPrimaryFocus` will work. i think it just may need to be displayed in the documentation to ensure this functionality is surfaced to the user. i'll open up a PR to include `selectorPrimaryFocus` in the storybook stories.

**Comment by davidmenendez** [comment]
i'd also like to point out this comment in this issue https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2452#issuecomment-1397083681

i think it may still be worthwhile to remove or refactor the specific create tearsheet focus functionality in order to resolve this. additional investigation is required.
