### ISSUE TITLE
Onboard to `@carbon/telemetry`

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#305]
https://www.npmjs.com/package/@carbon/telemetry

**Comment by lee-chase** [comment]
https://github.ibm.com/carbon/ibm/issues/97

**Comment by andrea-gm** [comment]
Is this in progress?

**Comment by SimonFinney** [comment]
Blocked, as I believe the package currently flags a CVE - https://github.com/carbon-design-system/carbon/issues/7751
