### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#31]

**Comment by carrenelloyd** [comment]
[**Link to design**](https://www.carbondesignsystem.com/community/patterns/export-pattern/)

Maintainers: [Vikki Paterson](https://github.com/vikkipaterson) , [Chloe Poulter](https://github.com/chloepoulterdesign)

Catalog number: 8

**Comment by SimonFinney** [comment]
@carrenelloyd Would you know if there's redlines or existing code available for this?

**Comment by SimonFinney** [comment]
Existing code - https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/under-construction-ide-exporting--simple-success-example

**Comment by SimonFinney** [comment]
@matthew-chirgwin Yesterday you mentioned this and #30 would be some of the first candidates for promotion on your end - so we have it documented, what were the sequence of events you outlined that would be required to get these into this repo?

**Comment by matthew-chirgwin** [comment]
@SimonFinney current proposal (pending agreement) is outlined here: https://ibm-cloud.slack.com/archives/CK5MMSYFJ/p1596644086443400

**Comment by lee-chase** [comment]
Does this component only exist because?
1. Safari does not support https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads
2. To select the type of file being downloaded

**Comment by lee-chase** [comment]
Dev review:

This appears to be a lift and shift of

https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/under-construction-ide-exporting--simple-success-example

although this implementation uses an out of date green success indicator (Carbon file upload uses blue).

The notification does not appear to be part of the UI, it would be nice to provide a code example showing this option.

Import has full-page, side panel and modal patterns. It would appear this design does not @vikkipaterson @chloepoulterdesign could you confirm this is not a requirement.

**Comment by chloepoulterdesign** [comment]
I think beyond your accurate point about the indicator @lee-chase I don't see any code changes needed - and as it is right now, the code (the button that says "Export") could be implemented into a full page, side panel or full page, and therefore meets the requirement.

**Comment by davidmenendez** [comment]
@chloepoulterdesign @vikkipaterson export is now ready for design feedback https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-exportmodal--standard

**Comment by chloepoulterdesign** [comment]
Thanks @davidmenendez 

1. It looks like the success/failure modals are missing? They're in the IDE components [here](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/under-construction-ide-exporting--simple-failure-example)
![image](https://user-images.githubusercontent.com/47979346/101193558-a64aba00-3654-11eb-9540-4195e3bcc5f4.png)


As raised above, lots of future work to do on this - happy for it to be raised in a new issue though:
- non modal options
- select a file type radio-buttons
- we need to revisit the extension validation piece - it's very strange UX, can probably be replaced by the radio buttons etc.

**Comment by davidmenendez** [comment]
since they were labeled as optional i wasn't sure if they were required for implementation. apologies. i'll work to add that in 👍

**Comment by davidmenendez** [comment]
@chloepoulterdesign i've pushed an update that includes showing success messaging, error messaging, adjustment to the naming validation, and pre-formatted extensions https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-exportmodal--with-success-message

**Comment by chloepoulterdesign** [comment]
Looks great, thanks @davidmenendez !
Design approved ✅

**Comment by andrea-gm** [comment]
@davidmenendez can we close this issue? or remove any labels?
