### ISSUE TITLE
Prevent publication of sub-components

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#316]
Sub-components that are created while developing other patters should not be published for use by product teams.

At release review, add a step to encourage developers to discuss components that could be broken out.

Any such sub-components should not get their own top-level storybook folder. Perhaps a hidden dev storybook folder or a folder named "Internals" could be used.

Any such sub-component should not be published directly on npm e.g. not in the index.js and/or obscured in some other way.

**Comment by andrea-gm** [comment]
Would it make sense to turn this into an Epic, then we can create separate issues for each task? As is, this does not feel actionable to me and I am not sure who needs to be assigned to fix the bug(s).

**Comment by lee-chase** [comment]
Probably just need to ensure sub-components are not listed as released in experimental/src/components/index.js

SCSS will hopefully be picked up as part of #364

**Comment by lee-chase** [comment]
This has been done with the move to Canary.
