### ISSUE TITLE
Tearsheet: Input elements are not styled correctly in main content area with grey 10 theme

### ISSUE THREAD

**Issue by amilligan** [carbon-design-system/ibm-cloud-cognitive#339]
## What package(s) are you using?
@carbon/ibm-cloud-cognitive-experimental

## Detailed description

> Describe in detail the issue you're having.
We use the grey 10 theme, and are displaying a tearsheet containing a search input element and several text input elements.  With no extra styling, the input elements in the tearsheet main contain area have a grey ($ui-02) background rather than the expected white ($ui-01) background.

This appears to be due to the fact that the tearsheet inherits style and behavior from the modal component; the modal component has anomalous styling, in that it appears with white background and grey input elements in both the white (default) and grey 10 themes.  The tearsheet-specific styling appears to explicitly override the modal styling in the grey 10 theme, but seems to have just missed the input elements.

> Is this issue related to a specific component?
Tearsheet displayed using the grey 10 theme.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expected: Inputs with white background color.
Actual: Inputs with grey background color.

> What browser are you working in?
Chrome and Firefox.

> What version of the Carbon Design System are you using?
carbon-components v10.28.0
carbon-components-react v7.27.0
@carbon/themes v10.26.0
@carbon/ibm-cloud-cognitive-experimental v0.19.11

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/serene-paper-qu2g4?file=/src/index.js

Unfortunately, I'm not sure how to set the theme to grey 10 in the code sandbox.  Here is an example we've created with  a basic layout that would show the problem, were it using the grey 10 theme.

**Comment by sidswamym** [comment]
@dcwarwick can you please let us know the ETA for the fix? We are planning to go live with the tear sheet by end of May.

**Comment by dcwarwick** [comment]
@sidswamym We've been focusing a lot of effort on reviewing and revising the Tearsheet for release, which is now mostly done. It's now at the top of my list! I'll let you know when I have an exact ETA for this, but I would certainly expect it to be fixed within the coming week.
