### ISSUE TITLE
Warning messages when PR is merged

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#342]
## Detailed description

There's a warning message appearing in the workflow summary when a PR is auto-merged by kodiak:
"1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results."

This looks like a reference to the codeQL configuration: https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/e7bd58d5c8f10f7df79b17f7b9e569cd3b569bf8/.github/workflows/codeql.yml#L24.

However I've not suggested a fix because I'm not at all familiar with the CodeQL tasks!

## Steps to reproduce the issue

1. Tag a PR as Ready to Merge and complete all reviews
2. Sit back and watch as kodiak does the automerge
3. Look at Actions and click on the workflow run for kodiak

## Additional information

![image](https://user-images.githubusercontent.com/6385315/108103287-a36f3b00-7081-11eb-9d94-aae9190cd562.png)

**Comment by SimonFinney** [comment]
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/troubleshooting-the-codeql-workflow#warning-git-checkout-head2-is-no-longer-necessary
