### ISSUE TITLE
PageHeader unusable in current build

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#356]
## PageHeader component breaks in latest build
@AlexanderMelox and I are working on a project that uses the PageHeader and we updated to the latest build and our app breaks because of an issue in the `unwrap-if-fragment.js` util that the PageHeader uses.

## What package(s) are you using?
`@carbon/ibm-cloud-cognitive-experimental`
specifically the `<PageHeader />` component
## Detailed description
We updated to the latest build of both `@carbon/ibm-cloud-cognitive` and `@carbon/ibm-cloud-cognitive-experimental` and afterwards our app broke because of something giong on in `unwrap-if-fragment.js`.

> Is this issue related to a specific component?
`<PageHeader />`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expect the `unwrap-if-fragment.js` util to not attempt to iterate over something that isn't iterable.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
carbon-components: 10.27.0
carbon-components-react: 7.27.0

## Steps to reproduce the issue

1. Use latest versions of both `@carbon/ibm-cloud-cognitive` and `@carbon/ibm-cloud-cognitive-experimental`
2. Add PageHeader to your app
3. You'll see the error

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/elegant-paper-7i3r3?file=/package.json

## Additional information

![Screen Shot 2021-02-18 at 12 53 44 PM (1)](https://user-images.githubusercontent.com/10215203/108514379-cbcd8400-7291-11eb-8338-199cabf6641d.png)

**Comment by andrea-gm** [comment]
Is this issue now resolved with the above PR merged? @lee-chase @matthewgallo

**Comment by lee-chase** [comment]
Yes.
