### ISSUE TITLE
Add unit tests for the web terminal component

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#358]
# Web terminal

Contributes to #70

## Brief description

The web terminal component does not have unit tests.

## Details

Details in PR #341 

## Tasks

- [ ] Add WebTerminal.test.js

**Comment by AlexanderMelox** [comment]
@matthewgallo will take over the web terminal tests

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/475
