### ISSUE TITLE
Publish dev canary etc versions of package

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#365]
It would be useful to publish updates for production teams quickly. 

- [ ] Investigate/publish ibm-cloud-cognitive-canary - Includes unreleased components without feature flag requirements
- [ ] Investigate/publish ibm-cloud-cognitive-dev - Includes PRs passing tests and that are mergable

**Comment by andrea-gm** [comment]
@lee-chase still relevant? should we move this into the Backlog?

**Comment by andrea-gm** [comment]
@lee-chase should we keep this one open?
