### ISSUE TITLE
Improve responsive behaviour of page-header

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#368]
The page header has various responsive requirements.

https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/59#issuecomment-701408228

- Care should be taken when dropping page Actions onto a new line so that it does not enter the Breadcrumb/ActionBarItem row too early.
- Tags wrap above the tabs when vsible
- Action bar items currently collapse to a comboButton. The design indicates an overflow, this might clash with ActionBarItems when in Breadcrumb/ActionBarItem row. Check with @cameroncalder 
- Breadcrumb should become back arrow on very narrow screens. Should overflow of breadcrumb be shown at this point? Check with @cameroncalder 
- Should ActionBar and PageActions combine to a single overflow when space is tight? Check with @cameroncalder 

**From epic**

Responsive behavior examples

1312
![1312 breakpoint example](https://user-images.githubusercontent.com/50155706/94694685-b5cb2100-02fa-11eb-9168-abc4433039d6.png)

1056
![1056 breakpoint example](https://user-images.githubusercontent.com/50155706/94694727-bebbf280-02fa-11eb-92cc-bb120e8a2ec6.png)

672
![672 breakpoint example](https://user-images.githubusercontent.com/50155706/94694756-c67b9700-02fa-11eb-9a93-d86b52c9ca09.png)

320
![320 breakpoint example](https://user-images.githubusercontent.com/50155706/94694771-cb404b00-02fa-11eb-9130-ce95ac3a41e5.png)

Follows Carbon breadcrumb overflow guidance (one path at the front and two at the end, space providing)
https://www.carbondesignsystem.com/components/breadcrumb/usage/#overflow-content

_*Note, CP4S use-case: For breadcrumbs requiring overflow, two paths are placed at the front of the breadcrumb and one at the end because of the nature of the application IA in relation to the platform. This provides a quick path back to the root of the current application in addition to the platform homepage)_

**Comment by cameroncalder** [comment]
> * Action bar items currently collapse to a comboButton. The design indicates an overflow, this might clash with ActionBarItems when in Breadcrumb/ActionBarItem row. Check with @cameroncalder

Yup, agree comboButton would be the better example to show

> * Breadcrumb should become back arrow on very narrow screens. Should overflow of breadcrumb be shown at this point? Check with @cameroncalder

For mobile, think we'll be ok with just the back arrow

> * Should ActionBar and PageActions combine to a single overflow when space is tight? Check with @cameroncalder

We should keep this separate since the ActionBar & PageActions will most likely be unrelated. Here's an example of how we could consider handling the ActionBar (3 max icons shown. If more, then overflow)

![320 breakpoint example copy](https://user-images.githubusercontent.com/50155706/111086454-3026e080-84ea-11eb-8467-9d93aec674ce.png)

**Comment by lee-chase** [comment]
This issue requires some overriding of Carbon CSS when implementing the 672 size.  

https://github.com/carbon-design-system/carbon/issues/8264

**Comment by lee-chase** [comment]
Closing with #627 tracking the remaining task.
