### ISSUE TITLE
Pre-collapse feature enhancement

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#370]
The preCollapseTitleRow feature needs some work

For design see https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/59#issuecomment-776653465

- Replace with preCollapse of whole header
- Add expand/collapse button. @cameroncalder open questions copied from here https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/59#issuecomment-776653465
   - Where does the chevron go if there are no tabs/tags?
    - If the user scrolls down partially which way does the chevron point
    - Is the chevron aligned to the right of the page like the action bar?

**Comment by cameroncalder** [comment]
>   * Where does the chevron go if there are no tabs/tags?

The chevron, used within the field size icon button, can still be placed in the same location as the tab/tag version. The background needs to be a prereq for the chevron/manual page header collapse functionality.
_Example without tabs for reference_
![page header 10](https://user-images.githubusercontent.com/50155706/111086076-695e5100-84e8-11eb-93b7-c16e6b4037c8.png)


>   * If the user scrolls down partially which way does the chevron point

The chevron should point up until it reaches the full collapsed state, then it points down.

>   * Is the chevron aligned to the right of the page like the action bar?

yessir
