### ISSUE TITLE
Add test coverage for page-header, action bar items, page actions, tag set and overflow breadcrumbs.

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#375]
Tests for 
- [ ] page-header
- [x] action bar items
- [ ] page actions
- [ ] tag set
- [ ] overflow breadcrumbs.

**Comment by andrea-gm** [comment]
@lee-chase Do we want to associate this issue with any Epics? Move it into the backlog?
