### ISSUE TITLE
Cross-browser testing

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#391]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

What do we do, as developers of components in Cloud & Cognitive, regarding cross-browser compatibility and support? Do we need to test cross-browser? And if so, what browsers should we be testing on and how do we do that testing?

**Comment by andrea-gm** [comment]
Firefox, Chrome, Safari, probably Edge. Definitely not IE.
