### ISSUE TITLE
Updates to the ReadMe

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#394]
Could the ReadMe use an update? I see it still references “Experimental” components.

For a developer coming in for the first time and consuming the components in their product, do we have instructions for installing and examples of importing and using a component? And any other info they may need to get started consuming.

I'm thinking we can follow [carbon-react's ReadMe](https://github.com/carbon-design-system/carbon/tree/master/packages/react#carbon-components-react)

**Comment by AlexanderMelox** [comment]
I think the most important steps should be:

1. How to install the package
2. How to import the styles
3. How to include the config.js file with the feature flags
