### ISSUE TITLE
Return to banner

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#40]

**Comment by SimonFinney** [comment]
Still relevant

**Comment by andrea-gm** [comment]
@SimonFinney Is this a new component or pattern? Can we add some links to designs, WIP, discussions, contacts?

**Comment by SimonFinney** [comment]
This can be closed as it's unnecessary to house this pattern here right now - as I understand it will only be implemented by one team
