### ISSUE TITLE
package-settings-cmn.js fails to work properly

### ISSUE THREAD

**Issue by dkaushik95** [carbon-design-system/ibm-cloud-cognitive#420]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

I am trying to add `PageHeader` component and I get the following error. 
<img width="465" alt="Screen Shot 2021-03-09 at 7 46 45 AM" src="https://user-images.githubusercontent.com/8481567/110488691-eeda9f00-80ab-11eb-9fde-09124b9a5374.png">

> Is this issue related to a specific component? 
I think the issue is somewhere [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/packages/experimental/src/global/js/package-settings.cmn.js)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in? Chrome

> What version of the @carbon/ibm-cloud-cognitive packge are you using?
`0.1.84`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. do npm install
2. Import a component (PageHeader in my case)

**Comment by lee-chase** [comment]
Thanks, @dkaushik95 this should have gone away today now as the cmn.js file has been removed.

**Comment by dkaushik95** [comment]
Thanks! @lee-chase it works now, closing.
