### ISSUE TITLE
Design review with Sam Ting

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#424]

**Comment by sydrosa** [comment]
@thefirstartist you can view the component here:

https://deploy-preview-373--ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-statusicon--default

**Comment by sydrosa** [comment]
@thefirstartist you can view the component here:

https://deploy-preview-373--ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-statusicon--default

You may have to navigate to status icon in the left side navigation.

**Comment by sydrosa** [comment]
@thefirstartist 

> Looking good. Just two things,
> 
>     1. In the Control dropdown for the size, could you add the size to the labels? For example, instead of "Small," could you make it "Small - 16x16"?

The label is actually the name for the prop a user would need to supply to the component, so I wouldn't want to change that. What I can do is add an additional table in the documentation showing the size, and the corresponding pixel height/width. Will that work for you?

>     2. When you select the dark theme, can you also change the background to dark color so we can see the actual result?

I'm not sure there's a way to do this. I'll do some digging and see if I can find a solution -- otherwise this will be the best we can do for now.

**Comment by thefirstartist** [comment]
How about showing two icons in a table at the same time like this? You can remove the control for changing the theme if you can do this.
<img width="304" alt="image" src="https://user-images.githubusercontent.com/40870771/110518715-4a635780-80c1-11eb-9dc2-489dcf0c1560.png">

**Comment by sydrosa** [comment]
I went ahead and added a sizing table in the documents so users are aware of what pixel size correlates to what prop.

<img width="1059" alt="Screen Shot 2021-03-10 at 10 15 02 AM" src="https://user-images.githubusercontent.com/47571589/110660747-7cd88780-8189-11eb-8269-68aa2bd3a0f9.png">


With regards to the other request, it is not possible right now since we want to demonstrate exactly how the props work in a dev's environment.
