### ISSUE TITLE
Sidepanel component does not receive className prop

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#432]
## What will this achieve?

I don't want to wrap the `<SidePanel />` component around a div for a className. Also, it might seem weird because the Side panel is position fixed and simply giving a div a className around it doesn't position it fixed too.

## How will success be measured?

If I can pass a custom `className` prop to the SidePanel component

**Comment by matthewgallo** [comment]
#433 now allows the SidePanel to accept a `className` prop that will add any custom class names.
