### ISSUE TITLE
Styling easy to accidentally override

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#441]
Update documentation and style guide to always take into account a later load of Carbon styles.

Any overrides we make should be at least one class more than Carbon.

Solution A: Wrap all of our component SCSS in at least block + 1 selector class
Solution B: Selector class + carbon class in the case of all overrides. 

A. Works best if we allow 1 level of nesting.
B. Makes it clear that Carbon is being overridden.

**Comment by dcwarwick** [comment]
Resolved by #481
