### ISSUE TITLE
Generate component script error

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#453]
## What package(s) are you using?

- [x] Cloud & Cognitive

## Detailed description

> Describe in detail the issue you're having.
Ran `yarn generate CreateModal` and received error:

```
yarn run v1.22.4
$ lerna run generate --scope "@carbon/ibm-cloud-cognitive-experimental CreateModal
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

> Is this issue related to a specific component?
No.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected 6 new files, got an error.

> What browser are you working in?
Not running a server rn

I have a feeling this error has everything to do with the escaped character on line 25 on `package.json`

**Comment by dcwarwick** [comment]
Fixed by #455
