### ISSUE TITLE
Clean up linter output

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#463]
There are a lot of linter warnings that are emitted, mostly from CDAI components, during the lint runs eg `yarn ci-check`. This is distracting, and makes it hard to pick through CI failure logs. The linter issues should be resolved, or marked to be ignored. Ideally this would be done by maintainers of those components, but we should probably do some/all of it for our own sanity purposes.

**Comment by andrea-gm** [comment]
@dcwarwick I think you already did this, correct?

**Comment by dcwarwick** [comment]
This has been done. Build, lint, test and ci-check consoles are squeaky clean and pristine.
