### ISSUE TITLE
Tracking mechanism for use (or lack of use) of common components

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#464]
Per Arin's request, let's explore alternatives for how we might help leadership in both design and development track use of common solutions across their teams (since people cannot be trusted to talk to each other or do as they're told).

After an initial chat with @dcwarwick and @lee-chase, it sounds like Telemetry is the best solution, which @joshblack had started looking into a while back. Dave and/or Lee to explore further and chat with Josh.

**Comment by joshblack** [comment]
Hey @andrea-gm! 👋 

Definitely happy to chat telemetry to see how we can help out 😄  This definitely aligns with our roadmap as a team and I'd love to sync up and see how we can help out!

**Comment by mattrosno** [comment]
Hi @andilozano - Matt here on the Carbon team with @joshblack. Can you include me in those convos? We'd be happy to show you our alpha telemetry solution that has been collecting data for a few good months now.

https://www.carbondesignsystem.com/help/faq/#telemetry

It sounds like step 1 is onboarding your packages into Carbon's telemetry. We can demo what we have today and where we see that going.

It would help if you could share questions that you'd want telemetry to help answer. Any sort of job stories, outcome statements, etc. to frame what you're after would be great as a starting point. Thanks!

**Comment by andrea-gm** [comment]
Hi @mattrosno ! I am adding you as optional for our meeting tomorrow, unfortunately looks like you have a conflict and I need an overview of telemetry asap. However, we will definitely include you in all future chats!

Regarding what we're after, I think it can be broken down into 2 things. (1) We need a sense of the overall adoption rate for the ibm-cloud-cognitive library and each of the components. (2) We also need a way to track specific teams' adoption status and component use. For example: How many teams have installed the library? How many teams are using the PageHeader component? Is the CPD team using the StatusIcon component? If yes, how many files import the component?

The overall goal is to validate whether or not teams are using common components as a way to support the efforts from the design team to achieve consistency across all Cloud & Cognitive products.

**Comment by mattrosno** [comment]
@andrea-gm sounds great. So we don't lose this information, I also cross-referenced it here: https://github.ibm.com/carbon/ibm/issues/99

Here's another issue that you may want to check out. Less of a focus on specific components, but more how we plan on using telemetry to track KPIs across Carbon. The asset consumption KPI very related here. https://github.ibm.com/carbon/ibm/issues/66

**Comment by lee-chase** [comment]
Added @carbon/telemetry in https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/477

From slack conversation with Josh, Andrea and Dave.
- https://ibm-casdesign.slack.com/archives/C01CE1YPJJ0 #carbon-analytics
- https://github.ibm.com/ibmcloud/pal/blob/master/statistics/adoption/repo-latest.json info collected to date.
- https://ibm-studios.slack.com/archives/C01CE1YPJJ0/p1602255784004700 video of info
- https://files.slack.com/files-pri/T27SFGS2W-F01RZ8LDG65/image.png
![image](https://user-images.githubusercontent.com/15086604/111671068-747aef00-8810-11eb-9bdf-172406982cc9.png)
- https://github.ibm.com/ibmcloud/pal/tree/master/statistics - Cloud Pal script which may work well for a subsection of github enterprise, but is limited to non-private repos. We believe Cloud repos are generally not private.
- https://github.ibm.com/ibmcloud/pal/blob/master/statistics/adoption/repo-latest.json - Cloud PAL output
