### ISSUE TITLE
Saving: design feedback

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-cloud-cognitive#471]
Link to saving storybook https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-saving--auto

**Comment by andrea-gm** [comment]
@davidmenendez For auto-save I noticed the whole thing moved up when the text on the bottom appeared. Might be fine and the developers will know what to do with it, just mentioning what I saw.

For the manual save, the button kind of changes size a lot. Not sure if that was the design intention... and if it was the intention I'd question if it was a good idea... but yeah, besides that looks great!

**Comment by davidmenendez** [comment]
> For auto-save I noticed the whole thing moved up when the text on the bottom appeared. Might be fine and the developers will know what to do with it, just mentioning what I saw.

yeah i wouldn't worry about that. This is one of those instances where you shouldn't get too wrapped up in the storybook implementation haha

> For the manual save, the button kind of changes size a lot. Not sure if that was the design intention... and if it was the intention I'd question if it was a good idea...

based on the design documentation it wasn't exactly clear, but ultimately if you have a button and you have it in two states where one state has a string with fewer characters than the second then the button has to grow to accommodate the text. in a real world implementation the developer would have to make that judgement about the size difference based on their use case and their text, but it's something hey could easily handle with their own styling.

if that's all i'm going to go ahead and close this. when Chloe, Vikki, or someone else on design comes back with feedback i'll open up another issue for design feedback. till then i'll move onto adding tests and documentation.
