### ISSUE TITLE
User profile images: Design feedback

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#484]
## What will this achieve?

Design review

## How will success be measured?

Component matches design

## Additional information

The color blue is out because it is so similar to Cyan. Also, the 80 colors now map to the 30 colors. And the 60 colors map to the 50 colors, because the focus is now on the contrast relative to the background color rather than the intensity of the colors themselves.

**Comment by qbi11y** [comment]
I have rolled the changes into the component. Closing this issue.
