### ISSUE TITLE
EmptyStates: prep for release review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#485]
## What will this achieve?
Going through and ensuring the empty state components follow the new release guidelines.

## How will success be measured?

When all of the release items in the checklist have been satisfied and the components follow all of our new coding standards.

**Comment by matthewgallo** [comment]
Duplicate of #503

**Comment by andrea-gm** [comment]
whoops, forgot this existed
