### ISSUE TITLE
Move Notifications out of Canary

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#507]
## What will this achieve?
Moving the Notifications component closer to release

## How will success be measured?
When all review list items are complete for this component.

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/509

**Comment by lee-chase** [comment]
@matthewgallo notifications adds a console error on test. Please mock the console error as per `packages/cloud-cognitive/src/__tests__/index.test.js`

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/535

**Comment by matthewgallo** [comment]
This is complete
