### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#51]
Catalog # 4

[Link to design ](https://pages.github.ibm.com/cdai-design/pal/components/card/usage/)

[Link to Redlines](https://pages.github.ibm.com/cdai-design/pal/components/card/style/)

**Contributors**
Austin Edwards
Kathryn Gallagher
Alexander Meyer
Ceci Moralles
JP Pollard

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

Not sure who to invite as design maintainer
