### ISSUE TITLE
Codesandbox examples of components should include a carbon theme selector

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#514]
Would be useful, as there are often issues relating to themes and correct display. Popping in this issue to capture the thought. @lee-chase fyi.

**Comment by lee-chase** [comment]
It would need to be something that did not interfere with the layout of full width/height components.

**Comment by andrea-gm** [comment]
@AlexanderMelox is this something you can own?

**Comment by andrea-gm** [comment]
#867

**Comment by matthewgallo** [comment]
I've added theme switching capabilities to most sandboxes now. There were a few issues in a couple components that I will address but overall most components switched between themes without any problems.

https://user-images.githubusercontent.com/10215203/133136084-71a0c4f2-2c83-4afe-984f-269d03951f92.mov
