### ISSUE TITLE
Design review #1

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#522]

**Comment by andrea-gm** [comment]
@sydrosa are you needing another design review?

**Comment by sydrosa** [comment]
@andrea-gm not yet -- rn I am just addressing some of the concerns that you made last week such as:

1. Caret/icon in `Dropdown` component is not in view
2. Weird 1 pixel border-bottom on the button set in the modal
3. `NumberInput` component buttons are strange.

Addressing these with the Carbon team before I start overriding!

**Comment by sydrosa** [comment]
@andrea-gm would love another review -- addressed the above.
