### ISSUE TITLE
Align tearsheet to latest design

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#546]
## What will this achieve?

Alignment with design

## How will success be measured?

Design review

## Additional information

- Design - https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/usage

Specifically noticed the footer section and button type are inconsistent.

**Comment by dcwarwick** [comment]
The buttons need to be put in a ButtonSet rather than a plain div. This will be done via our new ActionSet component when we have made that.

**Comment by dcwarwick** [comment]
The ActionSet also needs to replicate the 'full bleed' styling, which Carbon only applies if a ButtonSet is included into a modal footer.

Also, the refreshed designs call for the ability to include actions into the header area -- consider adding a prop to enable that.
