### ISSUE TITLE
Add documentation for feature flag usage with config file

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#550]
## What will this achieve?
This will give users of our component library documentation on how to enable components via feature flags. There have been people asking about how to enable this and we should be able to point them to documentation on this.

## How will success be measured?
When there is docs on github where we can send people to when they are using components that have not been released.

[Current best synopsis](https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1615398124022000) thanks @dcwarwick

**Comment by andrea-gm** [comment]
@matthewgallo any update on this?

**Comment by matthewgallo** [comment]
Yes, I forgot to close this. @AlexanderMelox added some docs in this.
