### ISSUE TITLE
Review findings for Notifications

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#574]
## What will this achieve?

To complete readiness for release:

- [x] Change the component name to NotificationsPanel.
- [x] Change `setOpen` to be a simple event call `onClickOutside`.
- [x] Change `xxxLabel` to `xxxText` when they are bits of text to assemble, and make them functions whenever there are numbers etc to be substituted in.
- [x] See if you can use a copy of carbon ClickListener instead of useClickOutside.js.
- [x] Add a `settingsIconDescription`, `viewAllLabel` (as func), `dismissSingleNotificationIconDescription`, to ensure translateability.
- [x] Ensure that a passed ref is assigned into `notificationsPanelRef`.
- [x] Double-check the notification bottom padding 1.125rem why it's not a carbon token, and change the divider line width from `calc(100% - 2rem)` to `calc(100% - 2 * $spacing-05)`
- [x] Ensure tests achieve 100% coverage, and add a test for labels and text functions, and add a test for the onHandlers.
- [x] Update storybook doc to remove/suppress the empty state (just show it as code), and add some text to tell the user to look in the header bar at the top of the page. Also kind of nice if the dismiss actions work in the story.

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/584

**Comment by matthewgallo** [comment]
This is now complete, as NotificationsPanel has been released
