### ISSUE TITLE
Add a theme switcher utility component for Codesandbox

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#575]
# Theme switcher

## Brief description

Adds a theme switcher utility component for our code sandbox. The design will be based on [this prototype](https://github.ibm.com/Alexander-Melo/carbon-theme-switcher).

### Links to other materials

Prototype: https://github.ibm.com/Alexander-Melo/carbon-theme-switcher

**Comment by andrea-gm** [comment]
related to #514 ?

**Comment by AlexanderMelox** [comment]
@dcwarwick
