### ISSUE TITLE
Outdated canary instructions in placeholder component

### ISSUE THREAD

**Issue by ConradSchmidt** [carbon-design-system/ibm-cloud-cognitive#578]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Canary instruction in placeholder component is out dated - its missing the `/es/settings` part:

https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/06812edd22cf44753a844c49ce3a322d7adcc2ad/packages/cloud-cognitive/src/components/_Canary/Canary.js#L31

![image](https://user-images.githubusercontent.com/3808948/114076602-1e491b00-98a7-11eb-9d74-c8a51e1fb575.png)

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

https://github.com/carbon-design-system/ibm-cloud-cognitive#enabling-canary-components
```
import { pkg } from '@carbon/ibm-cloud-cognitive/es/settings';
```

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-cloud-cognitive packge are you using?

0.34.11

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

-

## Steps to reproduce the issue

1. Import canary component
2. get canary instruction

**Comment by ConradSchmidt** [comment]
Additionally I get an error when using the `noneJustYet`
```
Uncaught TypeError: Cannot set property 'noneJustYet' of undefined
```

**Comment by matthewgallo** [comment]
This looks to have been fixed. But I also am getting an error when trying the `noneJustYet` flag. @lee-chase is this an outdated flag now?
