### ISSUE TITLE
Multistep confirmation

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#58]
Catalog # 15

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/wip/multistep-confirmation/)

**Comment by lee-chase** [comment]
Marked as blocked as @carrenelloyd marked this as 'status: refining'

**Comment by vikkidpaterson** [comment]
Worth following up with Sichao about this one.  It originated from API Connect requiring it but wasn't ever progressed so either needs to be picked up or closed off.
