### ISSUE TITLE
Persistent banner

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#60]
Catalog # 17

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/wip/persistent-banner/)

**Comment by lee-chase** [comment]
Blocked as to the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by vikkidpaterson** [comment]
@carrenelloyd what was the reason behind the refining status tag - do you have a link to anything around the refinements underway?  I think there were a couple of teams that talked about picking this up.  It originated from Event Streams but wasn't ever progressed as not needed by that team.

**Comment by SimonFinney** [comment]
@lee-chase / @vikkidpaterson As far as I remember, the 'status: refining' label signifies a work item that is not ready to be picked up by development, as it's missing information such as links to design specifications and optionally existing code, as well as having a maintaining designer assigned to it.

**Comment by vikkipaterson** [comment]
I seem to have become a ghost in my above comment!
