### ISSUE TITLE
Pageheader title should have a loading state

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#611]
## What will this achieve?

In our designs, some of the pageheader titles are dynamic and come from an api. We want to utilize skeletons until it loads but currently the Pageheader title prop is of string.

## How will success be measured?

If we can somehow pass a node OR a string to the title prop. Or indicated a prop if the title is loading.

**Comment by andrea-gm** [comment]
I wonder if @cameroncalder has any thoughts about the loading/skeleton state for PageHeader, and how we can best go about building this into the component for consistency.

**Comment by lee-chase** [comment]
Closed by #761 @cameroncalder reviewed the addition of skeleton and approved of the change.
