### ISSUE TITLE
Reordering

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#62]
Catalog # 19

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/wip/reordering/)

**Comment by lee-chase** [comment]
Marked as blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by vikkidpaterson** [comment]
@carrenelloyd what was the reason behind the refining status tag - do you have a link to anything around the refinements underway?
