### ISSUE TITLE
Make breadcrumb with overflow collapse to <-- arrow on small

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#627]
Assuming the title still floats up next to the arrow, so just replaces the `../`

> * Action bar items currently collapse to a comboButton. The design indicates an overflow, this might clash with ActionBarItems when in Breadcrumb/ActionBarItem row. Check with @cameroncalder

Yup, agree comboButton would be the better example to show

> * Breadcrumb should become back arrow on very narrow screens. Should overflow of breadcrumb be shown at this point? Check with @cameroncalder

For mobile, think we'll be ok with just the back arrow

> * Should ActionBar and PageActions combine to a single overflow when space is tight? Check with @cameroncalder

We should keep this separate since the ActionBar & PageActions will most likely be unrelated. Here's an example of how we could consider handling the ActionBar (3 max icons shown. If more, then overflow)

![320 breakpoint example copy](https://user-images.githubusercontent.com/50155706/111086454-3026e080-84ea-11eb-8467-9d93aec674ce.png)

_Originally posted by @cameroncalder in https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/368#issuecomment-798991704_

**Comment by lee-chase** [comment]
Closing with #672 tracking the remaining task.

**Comment by matthewgallo** [comment]
This is complete
