### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#63]
Catalog # 20

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/patterns/saving/usage/) 

[Working code](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-api-key-generation-component--with-core-configuration)

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by vikkidpaterson** [comment]
@carrenelloyd what was the reason behind the refining status tag - do you have a link to anything around the refinements underway?
