### ISSUE TITLE
[PageHeader]: Toggle collapse overlaps with action bar items

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#630]
## Description

When hovering over `toggle expansion/collapse` it overlaps with the action bar items.

Storybook link: https://ibm-cloud-cognitive.netlify.app/?path=/docs/cloud-cognitive-canary-pageheader--all-attributes-set#page-header-with-ba[…]actions-toolbar-only

![Screen Shot 2021-04-20 at 12 49 56 PM](https://user-images.githubusercontent.com/12755042/115442898-8cafa680-a1e0-11eb-8cc7-2d437782a5f1.png)

![Screen Shot 2021-04-20 at 12 50 30 PM](https://user-images.githubusercontent.com/12755042/115443039-bc5eae80-a1e0-11eb-941d-1e99fc92f268.png)

## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

> Is this issue related to a specific component?

PageHeader component

> What browser are you working in?

Google chrome

**Comment by lee-chase** [comment]
Does this only happen on the docs page @AlexanderMelox ? Not able to see it in storybook.

**Comment by AlexanderMelox** [comment]
@lee-chase it happens when the content on the page doesn't scroll

**Comment by AlexanderMelox** [comment]
https://user-images.githubusercontent.com/12755042/116457945-07f10800-a832-11eb-96c9-db819484c348.mov

**Comment by AlexanderMelox** [comment]
Only works if the content on the page is scrollable. Also see a problem on this if we want to use a fullscreen page with them collapse, we don't want to see the collapse row. Should this be a boolean to hide it?
https://user-images.githubusercontent.com/12755042/116458060-2951f400-a832-11eb-903a-efe774905b2d.mov

**Comment by cameroncalder** [comment]
Hey @lee-chase the inclusion of the collapse button was to provide a means to manually collapse the page header for a specific team's use case. I don't think we should display the collapse button "on" as the default. It's a good option for teams to have available and for them to choose if it's valid for their use cases, but it's not necessary for most page headers. Not displaying it by default but providing it as an optional control should address the issues above, yeah?

**Comment by lee-chase** [comment]
@cameroncalder the header scrolling off mechanic only works when there is sufficient content to scroll onto the screen. The collapse button assumes that is the case and tries to automate scroll. This would still be the case even if the collapse button availability is specified by the user. While the consumer is in a better position to know if there is scrollable content, it is non-trivial.

It is also non-trivial to switch between a scroll implementation and a non-scroll one in the page header. That said I think it could be done switching between a scroll and margin-top mechanic, but I'm not how smooth it will look.

Leave it with me, I'll add a property to make the collapse button available only when requested.

**Comment by lee-chase** [comment]
Agreed with @cameroncalder that the target mechanic is scroll and that the consumer should specify whether or not the button is needed.
