### ISSUE TITLE
Tearsheet main body is taking 20% margin from right side

### ISSUE THREAD

**Issue by jainshravan123** [carbon-design-system/ibm-cloud-cognitive#637]
20% margin is appearing from right side of main body under tearsheet. 

<img width="1680" alt="Screenshot 2021-04-21 at 3 20 25 PM" src="https://user-images.githubusercontent.com/6860473/115534165-234d9780-a2b5-11eb-9401-41cdce51b642.png">

We are using the latest version(0.35.3  as of now) of `@carbon/ibm-cloud-cognitive ` and consuming the tearsheet in the following way.

Importing the following in .scss file.
```
@import '~@carbon/ibm-cloud-cognitive/scss/index';
```

and 

```
import { Tearsheet } from '@carbon/ibm-cloud-cognitive'
```

Can someone please look into this issue asap?

**Comment by lee-chase** [comment]
@dcwarwick FYI

**Comment by jainshravan123** [comment]
@dcwarwick 
Thanks for looking into this issue. 
1. Yes we are using the carbon.  
    ```
      "carbon-components": "^10.32.1",
      "carbon-components-react": "^7.32.1",
      "carbon-icons": "^7.0.7",
    ```
2. It'll be available in our demo. I'll send you the URL once it'll reach there in demo environment.

**Comment by jainshravan123** [comment]
@dcwarwick

We fixed this by overriding css in our own component. I'm closing this issue as it's not happening now. 
Thanks for your help.
