### ISSUE TITLE
Slide-over panel

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#65]
Catalog # 22

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/components/slide-over-panel/usage/)

[Working code](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/stories-of-ide-slide-over-panel--small)

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by vikkidpaterson** [comment]
@carrenelloyd what was the reason behind the refining status tag - do you have a link to anything around the refinements underway?
