### ISSUE TITLE
Page Header design review

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/ibm-cloud-cognitive#657]
Related to #488 

- [x] The default for every page header should have the page header background set to `True`

- [x] It appears that even if the page header doesn't have a defined toolbar, it still uses the space for the breadcrumb bar. The desired intention is to have a 4px `$spacer-02` spacer between the actual breadcrumb & the page title. (This keeps the page title in the same position whether it has a breadcrumb or not) Can this be achieved?
![Component bug - breadcrumb + title spacing 2](https://user-images.githubusercontent.com/50155706/116138726-cb3ed880-a69a-11eb-90dd-63054c6108eb.png)
![Component bug - breadcrumb + title spacing](https://user-images.githubusercontent.com/50155706/116138111-08ef3180-a69a-11eb-9add-e685db26aaa4.jpg)

- [x] The collapse function should be an optional control, set to off by default
![Component bug - Collapse option](https://user-images.githubusercontent.com/50155706/116138115-0987c800-a69a-11eb-8696-e159ce7376af.jpg)

- [ ] If there is an icon with the page title, position it vertically aligned with the text
![Component bug - icon with page title](https://user-images.githubusercontent.com/50155706/116138119-0987c800-a69a-11eb-876b-a7cfb0887437.jpg)

- [x] If the breadcrumb/actionbar is present, please update the spacing between the bar and the page title to `$spacing-05`
![Component bug - Page title spacing under toolbar](https://user-images.githubusercontent.com/50155706/116138120-0987c800-a69a-11eb-8583-9d8e72b99576.jpg)

- [x] Apply the same line length logic to the subtitle as we did to the page title. Believe it was 60%?
![Component bug - subtitle truncation](https://user-images.githubusercontent.com/50155706/116138124-0ab8f500-a69a-11eb-942c-55b1c4990345.jpg)

- [x] Change the summary section type to `$body-long-01`
![Component bug - Summary section](https://user-images.githubusercontent.com/50155706/116138126-0b518b80-a69a-11eb-9590-24ba4af32a13.jpg)

- [x] If there are tabs & tags, the tags should be vertically aligned with the tabs. `$spacer-02` top/bottom
![Component bug - Tabs + tags on right side](https://user-images.githubusercontent.com/50155706/116138128-0b518b80-a69a-11eb-93b6-ef50cc1724f9.jpg)

- [x] Tabs should start 16px from the edge of the stage
![Component bug - Tabs starting alignment](https://user-images.githubusercontent.com/50155706/116138129-0bea2200-a69a-11eb-93cb-200ade02b2f0.jpg)

- [x] If only tags are present, spacing between the page title and tags should be `$spacing-05`
![Component bug - Tags only](https://user-images.githubusercontent.com/50155706/116138130-0bea2200-a69a-11eb-8ab5-b137fe189078.jpg)

- [x] If a status+label is present, spacing below the status should be `$spacing-05`
- [x] The label text style should be `label-01`
![Component bug - Title status](https://user-images.githubusercontent.com/50155706/116138131-0c82b880-a69a-11eb-84eb-f92b994760fe.jpg)

- [x] Update collapse icon tooltip to say "Collapse" or "Expand"
![Component bug - Toggle label](https://user-images.githubusercontent.com/50155706/116140467-fc200d00-a69c-11eb-8fb8-8ae01148c988.jpg)

- [x] Icon buttons should shift to the left to accommodate the Collapse icon button
![Component bug - toolbar icons w collapse](https://user-images.githubusercontent.com/50155706/116138135-0d1b4f00-a69a-11eb-88db-5ba2b6a24921.jpg)

- [x] Change the long page title to "A very long page title that is going to exceed 60% of the stage width and get truncated"
![Component bug - Very long page title](https://user-images.githubusercontent.com/50155706/116138138-0d1b4f00-a69a-11eb-9646-ec2920488b25.jpg)

- [x] Page header should extend the full width of the stage and start directly under the global header
![Component bug - w Carbon header](https://user-images.githubusercontent.com/50155706/116138139-0db3e580-a69a-11eb-9c59-7696871e6c52.jpg)

- [x] If there is only a page title, positioning under the page title should be `$spacing-07`
![Component bug - Without Background Breadcrumbitems Title](https://user-images.githubusercontent.com/50155706/116138140-0db3e580-a69a-11eb-96ca-541545f88c08.jpg)

**Comment by lee-chase** [comment]
Hi @cameroncalder 
1. Currently the presence of background - forced on by property or based on scroll if we have a breadcrumb, action bar, tags or navigation. Are you saying we should switch to forced off by a property then back on through scroll?
2. In the current implementtion the spacing above the title is; default: 02, under action bar 06, without breadcrumb, page actions or action bar 07. Might need to do this live to refine.
3. Done optional collapse header button
4. The icon is sat on the same base line, are you suggesting middle? 
![image](https://user-images.githubusercontent.com/15086604/118524311-ecdd2e00-b735-11eb-97d5-2c094cca7aec.png)
![image](https://user-images.githubusercontent.com/15086604/118524562-3168c980-b736-11eb-9952-9cb7440786d2.png)
5. Understood 05 under breadcrumb.
6. Done subtitle see long values and many items.
7. The available space is sized by Carbon to body-long-02 as part of its css reset. We can
- a. Set everything inside to default to body-long-02
- b. Set certain child types <p><ul><li><a><span><div> etc to body-long-02
- c. Set everything except some child types <h1><h2><h3><h4><h5> to body-long-02
- d. Restrict to text only, currently anything is allowed.
8. Understood tags spacing top/bottom 02 when no nav.
9. Understood tabs offset -16px at left
10. Between Tags and Title spacing is 05, however 02 is also provided by tag padding. Page actions can also add an additional 4px. Should we account for both cases making the title space 04 without pageActions and 03 with?
11. Status is rendered as content in additional info and changing it would affect all additional content. 
12. Understood on collapse label.
13. Done - Icon buttons shifted left.
14.  Suggest 'A very long page title that is going to exceed 60% of the stage width and get truncated on large screens'
15. Done, although this is not something we can control if the consumer places us in a bx--content or adds thier own style.
16. Understood space below title only.

NOTE: All content that can appear below the title can be affected  by page Actions adding 4px height. We could add a negative margin below pageActions on the assumption nothing will get close to it. Removing it on small widths where page action wraps.
