### ISSUE TITLE
Tearsheet: Adjust subtitle width to 60%

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#659]
## What will this achieve?

Improved visuals

## How will success be measured?

Design review with long enough subtitle string.

## Additional information

To align with the PageHeader component, the subtitle for tearsheet should span 60% of the width allowing to wrap to one additional line before truncating.

This comes from a conversation with Andrew Smith, Mitchell Bernstein, and @cameroncalder

**Comment by dcwarwick** [comment]
A few clarifications @andrea-gm @cameroncalder 
 * Just checking that the 60% specification is right (for example, modals restrict the width to 80%). I couldn't spot the 60% width specification in the Page Header design, and we should make sure Page Header and Tearsheet align as intended.
 * What is the desired responsive behaviour? Modals restrict the width to 80% for medium breakpoint and above, so smaller viewports can use the full width. I'd envisage applying the same principle here unless something different is required.
 * What exactly is meant by "subtitle"? The tearsheet has a title, a context label (which sits above the title), and a description (which sits below the title). See https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/usage/#1.%20Header%20zone. Is the 60% width to be applied to the description? The title? both? and the label? All three?
 * The note above also says "allowing to wrap to one additional line before truncating" -- this seems to introduce a line clamp. What is the designed truncation behaviour? Should overflowing text be hidden/discarded, and should an ellipsis be shown? Or a fade-out? Or scroll behaviour? Or a "show more" link? If this is already described for the Page Header design, just give me a link to the appropriate part and I can follow the same spec.

**Comment by dcwarwick** [comment]
@lee-chase let's discuss to compare this with what you did in PageHeader

**Comment by dcwarwick** [comment]
To be consistent with the PageHeader, I have interpreted this issue as applying to the *description* of the tearsheet, applying a 60% width at medium breakpoint and above (using full width on smaller viewports), and applying a line-clamp of two lines with an ellipsis in the case of overflow.
