### ISSUE TITLE
State

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#66]
Catalog # 24

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/wip/state/)

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by Levinson1** [comment]
The State pattern will be incorporated into the new Notification pattern extension currently being worked on by Maui Francis.
