### ISSUE TITLE
Ensure compatibility with react and react dom 17

### ISSUE THREAD

**Issue by joker23** [carbon-design-system/ibm-cloud-cognitive#674]
## What will this achieve?
Enhancement to make sure components are compatible with the latest react version.

## How will success be measured?

Components should work with teams that are on `react @17.x.x` and additionally `react@^17.0.0` should be added as a valid peer dependency

**Comment by lee-chase** [comment]
Not sure how we would "Ensure compatibility" given that we are currently developing against React 16.

If there is a specific issue you are having perhaps you could raise it.

We probably should do as the core Carbon team did and change the peer dependency config.

See https://github.com/carbon-design-system/carbon/pull/7131/files

**Comment by lee-chase** [comment]
Probably also worth someone reading the following link. It suggests there are "potential breaking changes" with the event system and "other breaking changes" which are rare.

https://reactjs.org/blog/2020/10/20/react-v17.html

**Comment by andrea-gm** [comment]
Will be addressed by https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/832

**Comment by dcwarwick** [comment]
We should make the same peer dependency declaration as carbon-components-react, and this is addressed for ibm-cloud-cognitive and cdai by PR #869. We will test against react 17 as soon as feasible as part of #832 creating example use packages.
