### ISSUE TITLE
File Uploader

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#68]
Catalog # 26

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/components/file-uploader/usage/)

[Link to Code](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-api-key-generation-component--with-core-configuration)

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

**Comment by vikkidpaterson** [comment]
I think @lee-chase and Chloe have been discussing this.  @carrenelloyd what was the reason behind the refining status tag - do you have a link to anything around the refinements underway?
