### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#71]
Catalog # 29

[Link to Design ](https://pages.github.ibm.com/cdai-design/pal/components/widget/usage/)

**Contributors**
Arn Hyndman
Nancy Ching
Kala Nenkova
Holman Sze
Jeff Ng
Virginia Nicholson
Denise Heebner
Courtney Bittner

[Link to Code](https://test.cloud.ibm.com/login?redirect=%2Fdocs%2Fdeveloping%2Fget-coding%2Fconsole-sdk%3Ftopic%3Donboarding-step1-build#step1-build)

**Comment by lee-chase** [comment]
Blocked as the status of the design it was set to 'status: refining' by @carrenelloyd

Not sure who to invite as a maintainer
