### ISSUE TITLE
IdeFilter Component multiple issues | CDAI

### ISSUE THREAD

**Issue by lukababu** [carbon-design-system/ibm-cloud-cognitive#713]
## What package(s) are you using?
- [ ] @carbon/ibm-cloud-cognitive-cdai: "^1.1.8"
- [ ] @carbon/charts: "^0.40.11"
- [ ] @carbon/charts-react: "^0.40.11"
- [ ] @carbon/ibm-cloud-cognitive: "^0.35.13"
- [ ] @waiops/common-ui-components: "^1.0.15"
- [ ] react: "^16.14.0"
- [ ] react-dom: "^16.12.0"

## Detailed description

The first issue I encountered was getting the IdeFilter component to work, just importing the CDAI node_module and deconstructing IdeFilter was not enough, I had to manually dig up the component and import it that way (see step 3).

Next, the styles were off once the component was declared, so without documentation, I dug up where the styles for IdeFilter were and imported that one (see step 2).

Upon importing the styles I encountered an error as follows:

> ERROR in ./node_modules/@carbon/ibm-cloud-cognitive-cdai/scss/components/IdeFilter/_IdeFilter.scss
> Module build failed (from ./node_modules/css-loader/index.js):
> ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Can't find stylesheet to import.
>    ╷
> 11 │ @import '~@carbon/grid/scss/grid';
>     │         ^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
> 

Durring our team troubleshooting we figured out to remove line 11 `@import '~@carbon/grid/scss/grid';` from `node_modules/@carbon/ibm-cloud-cognitive-cdai/scss/globals/scss/_carbon-settings.scss`, this compiled our code and almost properly rendered our IdeFilter component.

The last issue that remains is a double `x` displayed when entering a search term. (see screenshot in additional information)

## Steps to reproduce the issue

1. Install with `npm install -S @carbon/ibm-cloud-cognitive-cdai`
2. import style with `import '@carbon/ibm-cloud-cognitive-cdai/scss/components/IdeFilter/_IdeFilter.scss'`
3. Import module with `import { IdeFilter } from '@carbon/ibm-cloud-cognitive-cdai/lib/components/IdeFilter'`
4. Declare component `<IdeFilter light />`

## Additional information
![Double X with IdeFilter](https://user-images.githubusercontent.com/9942961/117320042-dd1e3980-ae59-11eb-9235-b8de232949af.png)

**Comment by Georgegriff** [comment]
This is a regression, i'll take a look if what changes have come in here since previous versions, or if there has been some dependency change breaking this

**Comment by lukababu** [comment]
A follow up to the merges.

I have updated our packages and currently running

@carbon/ibm-cloud-cognitive: "^0.35.31",
@carbon/ibm-cloud-cognitive-cdai: "^1.2.2",

Everything renders well, but we still face compile issues like before with 

`   ╷
11 │ @import '~@carbon/grid/scss/grid';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@carbon/ibm-cloud-cognitive-cdai/scss/globals/scss/_carbon-settings.scss 11:9   @import
`

The temporary solution is to comment out line 11 in `node_modules/@carbon/ibm-cloud-cognitive-cdai/scss/globals/scss/_carbon-settings.scss`, which does not help with passing Travis build.

**Comment by lukababu** [comment]
`npm install @carbon/grid` fixed it

Thank you George!
