### ISSUE TITLE
Tooltip on the PageHeader-TagSet-Tag component does not close when clicked on the right of it

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#715]
Using a PageHeader with a list of tags, when they collapse becase too many and opening the Tooltip on the Tag component does not close when clicked on the right of it (appear also to be on the right of the main Grid container).

Is this issue related to a specific component?
PageHeader (carbon/ibm-cloud-cognitive": "^0.31.0), Grid, Tag,

What did you expect to happen? What happened instead? What would you like to
see changed?
When clicked outside of it the tooltip close. Maybe even when clicked again the tag that open it.

What browser are you working in?
Chrome Version 90.0.4430.93 (Official Build) (64-bit)

What version of the Carbon Design System are you using?
10.25

Steps to reproduce the issue
Open the tooltip and close it in the 4 directions. On the right should not do anything.

Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/shy-sun-0e2ww

**Comment by lee-chase** [comment]
@ninjasun I am unable to reproduce this can you reproduce? 

P.S. The codesandbox did not work for me.

![May-13-2021 11-11-07](https://user-images.githubusercontent.com/15086604/118112005-55e24000-b3dc-11eb-9621-192a9b7da2a6.gif)

**Comment by lee-chase** [comment]
Not able to reproduce @andrea-gm recommend close.
