### ISSUE TITLE
PageHeader on scrolling with sticky, the tooltip-tagset stay on top

### ISSUE THREAD

**Issue by ninjasun** [carbon-design-system/ibm-cloud-cognitive#716]
PageHeader on scrolling with sticky, the tooltip-tagset stay on top and does not scroll or close
## What package(s) are you using?

- [ X] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
On scroll down the tooltip overlaps the header/tags

> Is this issue related to a specific component?
PageHeader, TagSet, Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
Scroll the tooltip or close it but do not overlaps the tag set

> What browser are you working in?
chrome 90.0.4430.93 (Official Build) (64-bit)

> What version of the @carbon/ibm-cloud-cognitive packge are you using?
0.31
> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/shy-sun-0e2ww?file=/src/Header.js

![tooltip-overlaps-tags](https://user-images.githubusercontent.com/7422984/117421572-efae7680-af1e-11eb-8a59-41ad0d78597f.png)

**Comment by lee-chase** [comment]
Fixed
