### ISSUE TITLE
Styles doesn't load when trying to use SCSS instead of CSS file

### ISSUE THREAD

**Issue by MikeyZat** [carbon-design-system/ibm-cloud-cognitive#739]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

I'm trying to use the ibm-cloud-cognitive library for the first time. Although React components work fine, I'm struggling with importing the styles. On the `quick start page` I can find only how too import css:

![image](https://user-images.githubusercontent.com/41756225/118267323-29055a00-b4bc-11eb-9e7c-2ec9fad12099.png)

But since we use **scss** in our project, I'd like to import the scss index file. What I found is `@carbon/ibm-cloud-cognitive/scss/index.scss` so i try  to import it like:

`@import '~@carbon/ibm-cloud-cognitive/scss/index.scss';`

in my main scss file:

```scss
$feature-flags: (
  grid-columns-16: true,
  enable-css-custom-properties: true
);

@import '~@carbon/themes/scss/index.scss';
$carbon--theme: $carbon--theme--g10;
@include carbon--theme();

@import '~carbon-components/scss/globals/scss/styles.scss';
@import '~@carbon/ibm-cloud-cognitive/scss/index.scss';
```

This results in following error:
```
ERROR in ./src/stories/_carbon-styles.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/stories/_carbon-styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

@import 'carbon-components/scss/globals/scss/vars';
^
      File to import not found or unreadable: carbon-components/scss/globals/scss/vars.
      in C:\Users\MikolajZatorski\Documents\projects\wkc-shared-ui\node_modules\@carbon\ibm-cloud-cognitive\scss\global\styles\_carbon-settings.scss (line 11, column 1)
 @ ./src/stories/_carbon-styles.scss (./node_modules/style-loader!./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/stories/_carbon-styles.scss) 2:14-133 21:1-42:3 22:19-138
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

In my other project, I get following error:
```
Fatal error: Error: Can't find stylesheet to import.
  ╷
8 │ @import '@carbon/import-once/scss/import-once';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@carbon\ibm-cloud-cognitive\scss\index.scss 8:9  @import
  src\styles\common\_common.scss 11:9                           @import
  src\styles\common-light.scss 12:9                             root stylesheet
```

Both are strictly carbon import related. Maybe I should import the scss in different way?

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to

Probably I do something wrong (it's not documented in any way) or there is a bug. I'd expect to have a way to import scss styles instead of css.

> What version of the @carbon/ibm-cloud-cognitive packge are you using?
```
"@carbon/ibm-cloud-cognitive": "^0.36.21",
"carbon-components": "10.32.1",
"carbon-components-react": "7.32.1",
  ```

**Comment by MikeyZat** [comment]
I managed to resolve the second error
```
Fatal error: Error: Can't find stylesheet to import.
  ╷
8 │ @import '@carbon/import-once/scss/import-once';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@carbon\ibm-cloud-cognitive\scss\index.scss 8:9  @import
  src\styles\common\_common.scss 11:9                           @import
  src\styles\common-light.scss 12:9                             root stylesheet
  ```
  by chaning my sass-loader rules not to follow this old `~` import pattern. So this was not related to any issues on the `ibm-cloud-cognitive` side.
  
  However, the first issue still occurs, it might also be that the `node-sass` loader doesn't work correctly with this code, needs further investigation.

**Comment by dcwarwick** [comment]
Importing `@carbon/ibm-cloud-cognitive/scss/index` is right, and should work. However, to compile the scss your sass will need to be able to resolve all the dependencies, and that seems to be where it's falling over. `carbon-components/scss/globals/scss/vars` is probably the first external import it hits, so it looks like your sass is not looking in the right places for this. You might need to add your node_modules dir to an include path list or something like that.

I'm not aware of any specific reason that node-sass shouldn't work with our SCSS, but note that node-sass has now been deprecated for over six months and is getting maintenance updates only. We use sass (Dart Sass) for our own builds, and there may gradually be differences that draw these apart. We found the changeover quite straightforward -- I don't think there was anything we had to change other than the command line invocation (which became a lot simpler as it happens!).

**Comment by MikeyZat** [comment]
I was able to fix the issue and I confirm it was on **our side**.

For people struggling with similar cases, I updated all the `storybook` dependencies and changes the `sass-loader` from `node-sass` to latest `sass` (Dart sass) version. 

Nonetheless, the correct way to import scss styles could be mentioned in your docs/readme/storybook, I think it will be helpful.

Thank you!
