### ISSUE TITLE
Remove ComboButton component

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#749]
## What will this achieve?

A new ButtonMenu component has been added which more closely aligns with the current button menu design pattern. The ComboButton is a legacy component contributed from the security package and can now be removed in favour of ButtonMenu. This will also enable us to simplify the package structure as we can remove the 'security' package from the dependency network.

**Comment by dcwarwick** [comment]
There is some button pattern work about to be kicked off by Laura Marshall, so we should hold this until the outcome of that, as there may be a combo button pattern that this component can continue to provide or be integrated into the ButtonMenu component (which does not currently directly support the combo button presentation).

**Comment by dcwarwick** [comment]
stale bot can go boil its head

**Comment by lee-chase** [comment]
Combo button is now part of new button pattern.
