### ISSUE TITLE
Add option to proxy carbon-react

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#755]
## What will this achieve?

Satisfy teams' requirement to have a single way to install both carbon-react and ibm-cloud-cognitive.

## How will success be measured?

Internal testing, as well as production team confirmation/test.

## Additional information

Contacts for Security and Cloud PAL who have achieved this in their libraries are @SimonFinney and Timea Stein, respectively. We should be in sync.

Goal for this is by end of Q2.

**Comment by SimonFinney** [comment]
A convenience proxy is possible via something like `export * from 'carbon-components-react'`, but I can't recommend pursuing this much further than this as while the concept was beneficial for Security in scaling Carbon adoption initially, it added additional maintenance and support overhead, coupled the packages closer than they needed to be, and warped consumer mental model of the Carbon ecosystem.

**Comment by lee-chase** [comment]
Agree with Simons comment regarding the appropriateness of doing this. 

What we have done instead is establish a release pattern that keeps versions in sync so that multiple packages can be easily combined.
