### ISSUE TITLE
Tearsheet alignment to design guidelines

### ISSUE THREAD

**Issue by mitchellbernstein** [carbon-design-system/ibm-cloud-cognitive#773]
## Detailed description
Updates to tearsheet component are required to ensure consistency between the design guidelines and the implementation with code. There are a number of instances where things differ (probably due to my lack of specific guidance here and there). This issue will list as many as can be found.

## Issues

- [x] 1. Clicking on background overlay for large and narrow transactional/danger tearsheets should not close dialog.
- [x] 2. Navigation buttons should be always right aligned even when a right-hand-side-panel is present.
- [x] 3. Navigation buttons should use a max width of 232px for wide tearsheets, 50% for narrow tearsheets.
- [x] 4. Wide tearsheet with no side panels should give the Cancel button an extra 16px of padding to the left.
- [ ] 5. Tearsheet grid should be adjusted to fit new DSAG guidance.

---------

### Issue 1
Clicking on background overlay for large and narrow transactional/danger tearsheets should not close dialog.

#### Description
This will help prevent user errs from occurring if users are editing sensitive information and accidentally click off. We should use this to encourage users to click an action instead of an ambiguous area - they wouldn't know if the data is saved, erased, or applied if they click the background. It is noted as `preventCloseOnClickOutside` but should only apply as mandatory as false to transactional tearsheets and mandatory as true for passive tearsheets.

#### Reproduce
1. Open a tearsheet component.
2. Click on the background overlay
3. Tearsheet closes

#### Expected behavior
Expected to not allow for interactions if transactional tearsheet is open (i.e has action buttons). 

#### Image
_No image required_

---------

### Issue 2
Navigation buttons should be always right aligned even when a right-hand-side-panel is present.

#### Description
Side panels on the left influence how the navigation buttons align. The cancel button get's inside by the width of the side panel. However, on the right side, this behavior should not occur. The Primary and secondary buttons are required to sit "outside" of the content body area to acknowledge they operate the entire tearsheet not just a portion of it.

#### Expected behavior
Influencer panels on the left influence navigation button placement. Influencer panels on the right should sit above the navigation buttons.

#### Image

Current:
![image](https://user-images.githubusercontent.com/748263/119047528-a7ae3b80-b983-11eb-8422-e7d6c12eedbc.png)
Expected:
![image](https://user-images.githubusercontent.com/748263/119047358-6d449e80-b983-11eb-9b2f-5696fb180106.png)

---------

### Issue 3
Navigation buttons should use a max width of 232px for wide tearsheets, 50% for narrow tearsheets.

#### Description
Buttons can extend based on percentages due to the width of the tearsheet according to the viewport. However, buttons should only stretch until 232px as their max width.

#### Expected behavior
Navigation buttons stop stretching when they hit a max-width of 232px for wide tearsheets. Narrow tearsheets may continue to use percentage of width.

#### Image

Current:
![image](https://user-images.githubusercontent.com/748263/119047560-aed54980-b983-11eb-9e56-dfc1365707e9.png)

Expected:
![image](https://user-images.githubusercontent.com/748263/119047607-c280b000-b983-11eb-8865-a5e226fb1f1a.png)

---------

### Issue 4
Wide tearsheet with no side panels should give the Cancel button an extra 16px of padding to the left

#### Description
Cancel button text should align to the text of the area it is within/below. This applies only to wide tearsheets.
- If the tearsheet has no influencer side panel on the left and the cancel button is left aligned to the edge, it should have an additional 16px padding.
- If the tearsheet has an influencer side panel on the left it, again should sit with an additional 16px padding.

#### Expected behavior
Cancel button should include 16px extra padding on the left to allow it to align to content text / grid.

#### Image

Current:
![image](https://user-images.githubusercontent.com/748263/119047994-3b800780-b984-11eb-8592-6c2a53966c9e.png)

Expected:
![image](https://user-images.githubusercontent.com/748263/119047963-31f69f80-b984-11eb-831f-acf992540639.png)

---------

### Issue 5
Tearsheet grid should be adjusted to fit new DSAG guidance.

#### Description
Follow new tearsheet guidance for wide tearsheet and narrow tearsheet grid and behaviors for responsive sizes/media queries. Link: https://pages.github.ibm.com/cdai-design/pal/components/grid-behaviors

#### Expected behavior
_Follow guidelines by Kacie Eberhart._

#### Image
_No image required._

**Comment by dcwarwick** [comment]
Thanks @mitchellbernstein! A few questions:

**Issue 1**

To confirm, you'd like the `preventCloseOnClickOutside` prop removing and instead the behavior will be automatic, preventing close on click outside when the tearsheet is transactional (has action buttons) and allowing it when the tearsheet is passive (no buttons).

**Question**: should we do the same thing for `hasCloseIcon`? _i.e._ remove this prop as well, and make it automatic, with no close icon for transactional tearsheets and showing a close icon for passive tearsheets? Or is this an option individual cases may wish to make individual decisions on?

**Issue 2**

If the buttons are to remain at the right edge of the tearsheet, they will need to extend UNDER the right-aligned influencer -- is that what you intend?

**Question**: should they similarly extend UNDER a left-aligned influencer? or will the two alignments of influencer be different in this regard?

**Question**: when the buttons extend under an influencer, should each button continue to be sized to 25% of the content area width, which is what the design currently calls for? Or should they now be 25% of the whole tearsheet width?

**Comment by mitchellbernstein** [comment]
@dcwarwick 

> To confirm, you'd like the preventCloseOnClickOutside prop removing and instead the behavior will be automatic, preventing close on click outside when the tearsheet is transactional (has action buttons) and allowing it when the tearsheet is passive (no buttons).

Yep!

>Question: should we do the same thing for hasCloseIcon? i.e. remove this prop as well, and make it automatic, with no close icon for transactional tearsheets and showing a close icon for passive tearsheets? Or is this an option individual cases may wish to make individual decisions on?

I don't know the answer per say to this one. My expectation based on the logic set forth by carbon (who doesn't follow this but is now aware of it) that if the modal is passive (i.e uses a close icon and no buttons in the bottom of the tearsheet) then it it can use background overlay click to close it. If the component includes no close icon and does include buttons, it should not allow for clicking off the tearsheet to close.

> To confirm, the buttons will extend UNDER a right-aligned influencer, but will NOT extend under a left-aligned influencer.

Yep!

> when the buttons extend under a right-aligned influencer, should each button continue to be sized to 25% of the content area width (i.e. the width of the tearsheet minus the width of the influencer), which I think is what the design currently calls for? Or should they in this case be 25% of the whole tearsheet width?

Great question. The buttons should only react to the width of their available space (i.e a full width tearsheet with no left panel influencer or with a left panel influencer tearsheet) which is the content area. Weird I know.. but to answer your question, the buttons have a max-width of 232px but use 50% until they reach that width.

**Comment by dcwarwick** [comment]
Thank you @mitchellbernstein. I have this item assigned and am working on it now, and hope to have the code changes checked in this week (or the first day or two of next week at the latest) -- I'll let you know when they are live to check.

**Comment by dcwarwick** [comment]
@mitchellbernstein issues 1-4 are complete now I believe.

For issue 5 (grid), I have worked through the page you linked to, but it is not clear how much of it can or should be applied to a tearsheet.
 * The page talks about a "large tearsheet" grid, and I don't know what this means -- perhaps it means a wide tearsheet? It suggests that the width of the tearsheet should become full-screen at sm and md breakpoints, so I have implemented that by making wide tearsheets snap to full-screen width for sm/md viewports.
Beyond that, if there are principles which should apply to the tearsheet, I think if would help to update the tearsheet pattern documentation so that it's clear to designers and implementers how to put these into practice. For example, the page suggests that at small viewports (when the tearsheet is a full screen width) the influencer should become a slide-out, but it doesn't provide any details of how that should happen, what behaviour it should have, what affordances the user would use to cause the panel to slide out or back, etc. If there are specific mismatches between design and implementation you can see, or if the design is updated to reflect grid behaviour and these need to be implemented, please open issues to highlight those and we'll action them as promptly as we can.

@andrea-gm fyi
