### ISSUE TITLE
Release TagSet 

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#801]
New production dependencies
If a PR introduces new dependencies in package.json, paste the following checklist into the PR as a comment and check the items off before approving.

Tip You should be able to copy and paste the section below directly into a GitHub comment, then check where criteria passed, strike out where not applicable.

## Review of dependencies

- [ ] Verify the dependency has previously been pedigree reviewed
- [ ] Verify the dependency doesn't contain any vulnerabilities
- [ ] Verify the dependency bundle size is acceptable
- [ ] Verify the dependency is actively maintained
- [ ] Verify license conditions are met e.g. forwarding of copyright if necessary.

Component reviews for readiness
Reviews will be carried out by one or more members of the core contribution team. They will include as a minimum the following checks, which establish the "definition of done" for a component.

Paste the following checklist into the epic or issue under which the component is being made ready, then check where criteria passed, and add notes to clarify how an item is complete or what remains to be done: for anything more than minor/simple items, open issues to track them.

Tip You should be able to copy and paste the section below directly into a GitHub comment, then check where criteria passed, strike out where not applicable, and add notes to each item where applicable.

Once one or more components have been reviewed for readiness, the following steps are needed:

the flags for the components in package-settings.js should be changed to true.
the component SCSS should be included in /src/components/_index-released-only.scss.
run the tests, recreating snapshots (using -u), and check in the updated public CSS snapshot. NB it is sufficient to run yarn jest styles -u to complete the snapshot updates.
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [x] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [ ] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [x] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by sydrosa** [comment]
Release review feedback:

- [ ] Are you able to update the `children.propTypes` to specify that all children should be a Tag component from carbon. -- See example in EmptyState
- [ ] add `isRequired` to overFlowAlign prop
- [ ] We saw the availability to rightAlign the Tags in the tagset container. is there a reason there is no center
- [ ] showAllModalHeading change to showAllModalTitle

**Comment by lee-chase** [comment]
**STOP!!! These comments are a work in progress.**

> Release review feedback:
> 
> * [ ]  Are you able to update the `children.propTypes` to specify that all children should be a Tag component from carbon. -- See example in EmptyState
> * [ ]  add `isRequired` to overFlowAlign prop

Why make overflowAlign required when it has a default of 'center'?

> * [ ]  We saw the availability to rightAlign the Tags in the tagset container. is there a reason there is no center

Neither right alignment or center were called for in the design, but right alignment used in the PageHeader design. Carbon only uses 'center' for tooltip, 'right' for radio label position, 'align' with values 'start', 'end' for accordion chevron position. None of these really work here, but we could change to a more flexible 'align' with values of 'left', 'right' with left the default.

> * [ ]  `showAllModalHeading` change to `showAllModalTitle` for consistency then add required

Changed to showAllModalTitle, but why make required when there is a default?

> * [ ]  `showAllSearchLabel` to be required for screen readers/accesibility

Why when it has a default?

> * [ ]  `showAllTagsLabel` to be required

Why when it has a default?

> * [ ]  remove _all_ defaultProps -- devs should be encouraged to add the props themselves so that the alignment on the page is correct. You can add the defaultProps to your storybook instead

This makes it more cumbersome to use in it's default configuration.

> * [ ]  replace use of `heading` prop in TagSet, TagSetOverflow and TagSetModal to `title`

With reservations as this is a misuse of a standard HTML attribute. 

> * [ ]  on line 72 of TagSetOverflow, is there a particular reason for the use of `React.cloneElement`?

It overrides the 'filter' attribute to false, as per the design request.

> * [ ]  The "+" sign on line 60 of TagSetOverflow is hardcoded -- will this be translatable across other languages? Do other languages use an icon other than "+" to signify "more"?

I don't know, the question asked here.https://ibm-casdesign.slack.com/archives/C036P1CTN/p1623765536312600

> * [ ]  in the Search modal, if you search "Label" with an uppercase 'L', none of the results will show

Good catch.

> * [ ]  Line 77 in TagSetOverflow -- we probably shouldn't use the Link component with no href -- since this triggers a modal, we should use a button instead that is styled like a link.

Added role="button" rather than overriding button styles.

> * [ ]  in TagSet overflow, change blockClass on line 17 to `$pkg.prefix}--tag-set__overflow`

Strictly speaking, it should be `${pkg.prefix}--tag-set-overflow`

> * [ ]  Line 76 ih TagSetModal, we can get rid of `show-all-tags-modal-body-2`

Removed the -2, but otherwise made use of class in preference to Carbon class.

> * [ ]  Add TagSet component to src/compoonents/index.js file
> * [ ]  In the box-shadow property in your scss file, can you replace 2px with `$spacing-01`
> * [ ]  In line 81 of your scss file, you can remove the hashtag '#' since you're not interpolating the variable anymore
> * [ ]  In line 65, you have a max-height on the modal which should only be included in a breakpoint of medium or higher.
> 
> ```
> @include carbon--breakpoint(md) { max-height: 450px, height: 90% }
> ```
> 
> * [ ]  In all files under TagSet, go ahead and update the copy write header to include 2020, 2021 (except TagSet.js and TagSetOverflow.js -- those are already updated!)
> * [ ]  Include copy write header in TagSet.test.js (it's currently missing)
> * [ ]  We need to get to 100% test coverage on TagSetOverflow.js and TagSet.js -- see screenshot below
> * [ ]  With the new required props, there may be a drop in your test coverage or updates to your testing needed.
> * [ ]  Include a markdown file with relevant information for documentation
> * [ ]  Create a CodeSandbox for this component
> 
> ![Screen Shot 2021-06-14 at 3 26 14 PM](https://user-images.githubusercontent.com/47571589/121958967-ceb12080-cd29-11eb-87c6-bc7ba2a7f31b.png)

**Comment by lee-chase** [comment]
@sydrosa addressed all issues with the inclusion of #913 except the codesandbox. Will add a codesandbox after this PR is merged.

**Comment by matthewgallo** [comment]
Feedback from updates:
1. Yes that's fine to leave as a default, since we discussed earlier that only translatable string props should not have defaults.
2. If this wasn't called for in the design, we can make this an enhancement if the need for this arises.
3. ✅ 
4. ✅ 
5. I agree, however, probably best so that we can have consistency across our components.
6. ✅ 
7. Looks like there is approval via the a11y slack channel ✅ 
8. ✅ 
9. ✅ 
10. We noticed that this class was not used anywhere in your styles for this component, that's why we recommended to just remove it entirely.

**Comment by lee-chase** [comment]
2. It would make sense to change it to 'start', 'center' and 'end' now so as not to introduce a breaking change later. The default would be 'start' as per standard HTML flow.
5. Did it, but with reservations.
10. It was not but I was relying on Carbon classes. I removed the Carbon class usage and the number off the end of the class.

**Comment by lee-chase** [comment]
https://codesandbox.io/s/tagset-85crr
