### ISSUE TITLE
SidePanel (enhancement): mobile responsiveness of panels

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#852]
## What will this achieve?

When the panels hit a certain viewport width, they should become full width (similar to Carbon's modal). Will discuss with Kacie to confirm this is the intended behavior.

**Comment by jagathgj** [comment]
@matthewgallo Could you help me connect with designer? I would need to know more about the behaviour. Perhaps a design in Invision may help.

**Comment by matthewgallo** [comment]
Complete 🎉
