### ISSUE TITLE
LoadingBar items to address for release review

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#874]
- [ ] get design review and approval. Some design feedback: (1) If the loading bar is used eg across the top of a panel as per the design examples then the percentage indicator will be aligned at the extreme right of the panel -- is this correct/intended, or should it change, or should the design specify not to use a percentage indicator in this case? (2) What is the design recommendation for the percentage indicator to show when the loading bar is indeterminate? (3) PS the loading spinners are a bit distracting/confusing in the design picture and could perhaps be removed/clarified.
- [ ] Replace the `active` prop with a `status` prop, values `[ 'inactive', 'indeterminate', 'active' ]` (consistent with Carbon loading components), and replace the undefined percentage with an 'indeterminate' status.
- [ ] Clamp the range for percentage to be 0-100, using 0 as the default value.
- [ ] Add a default for the rendering of the `percentageIndicatorText` prop NOT using defaultProps but building a suitable value at render time something like `Loading ${percentage}%`, or 'Loading' when indeterminate, and blank when inactive.
- [ ] Add a suitable default for the rendering of `ariaLabel` as for `percentageIndicatorText`, something like `Loading indicator at ${percentage}%`, or 'Loading indicator' when indeterminate, and blank when inactive.
- [ ] Set `aria-hidden="true"` when the status is inactive, and set aria-valuemin/aria-valuemax/aria-valuenow appropriately.
- [ ] Remove `id` prop, as this is not needed, and remove `aria-labelledby` from the top level div. NB if the user provides an id it will be passed through with ...rest.
- [ ] Fix behaviour of `small="true"` so that the gray container also becomes 4px high, the percentage label (if shown) should remain 16px below.
- [ ] Change the percentage indicator text colour to $text-02 per design.
- [ ] Change the story-wrapper width to something like `calc(100vw - 4rem)` so that a full responsive range can be seen.
- [ ] Fix use of BEM -- element names and modifiers: 'small', 'linear-stop' and 'indefinite-stop' should be modifiers for example.

**Comment by lee-chase** [comment]
Loading bar is now in Carbon
