### ISSUE TITLE
[SidePanel]: When subtitle is not provided, scrolling behavior fails

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#887]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When a SidePanel is created with no subtitle, or even an empty string as a subtitle, the scrolling behavior breaks. You can see this most clearly with the variant with the action toolbar. It throws the error in the console `Cannot read property 'offsetHeight' of null`. I attached a video of the behavior, or you can see it in the storybook here. This doesn't seem to happen if a SidePanel is created with a subtitle and then dynamically changed to blank, however

Seen in Chrome and Firefox. Using the latest version of @carbon/ibm-cloud-cognitive.

I'm on the SOAR Playbooks team. We're looking into using the SidePanel to replace our panels currently in the product. (btw, any time estimate on when it'll come out of Canary?)

## Steps to reproduce the issue

1. Create a SidePanel without setting the subtitle prop or setting it to ""
or to see it in the storybook, use this link: https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-sidepanel--with-action-toolbar&args=subtitle:

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/codesandbox

^ The embedded browser is giving an error: DependencyNotFoundError
Could not find dependency: 'prop-types' relative to '/node_modules/@carbon/ibm-cloud-cognitive/es/components/_Canary/Canary.js'

## Additional information

https://user-images.githubusercontent.com/3118961/121606638-87bae680-ca1c-11eb-8ee6-66af85fd81ec.mov

**Comment by matthewgallo** [comment]
Thanks for opening this issue @lily-peng, I will take a look at this and get it fixed asap. In terms of when this component is going to be released (move out of canary), we are waiting on some final design approvals. After that, it shouldn't be long as we've already completed the engineering release review.

**Comment by matthewgallo** [comment]
Will be fixed with this PR https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/889

**Comment by matthewgallo** [comment]
This is fixed in [`v0.42.9`](https://github.com/carbon-design-system/ibm-cloud-cognitive/releases/tag/%40carbon%2Fibm-cloud-cognitive%400.42.9). Feel free to reopen if you notice this issue again @lily-peng!
