### ISSUE TITLE
Page Header Design Review

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#897]
## Design review guidelines
https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/.github/DESIGN_REVIEW_GUIDELINES.md

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern maintainer
- [x] The component’s motion matches the specifications set by the pattern maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can be used
- [x] Changing props in the Storybook updates the component

**Comment by cameroncalder** [comment]
LGTM! 🚀
