### ISSUE TITLE
Refine labels so we can see at a glance what state Issues are in

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#90]
The ibm-cloud-paks issue list, project and labels do not give a clear picture as to the project state.

It is unclear as to how the label states work, for example “status: refining” but by whom?

Perhaps we should borrow the labels from Carbon which are split into categories for “browser, component, impact, package, role,  status, type and version”.

**Comment by SimonFinney** [comment]
@lee-chase Can this be closed?
