### ISSUE TITLE
Discussion, design and development in the open

### ISSUE THREAD

**Issue by matthew-chirgwin** [carbon-design-system/ibm-cloud-cognitive#91]
I have noted in a number of issues raised for development of new components that a number of resources (designs, slack converstations etc) are only available 'inside the IBM firewall'. This is fine if you are an IBMer, but if you are not, and would like to contribute, you will not be able to get the context (or potential history) required to make such a contribution.

In my opinion, if the code is open source, the context, discussion and history of that code also needs to be in the open. Thus I would like to suggest that all discussion occurs in public (via GitHub issues, public slack etc), and that any/all resources (design files, development utilities and so on) that support the repo are contributed here also.

I am raising this issue to discuss the idea, and action any outcome.

**Comment by lee-chase** [comment]
In terms of Carbon teams public outputs that are relevant to us they produce:

- Styles in a core package
- React components in a package
- React component storybook
- React component codesandboxes
- Sketch design kits
- A public website carbondesignsystem.com detailing the design. Our PAL site equivalent. This is also in the same github organization.

As far as I am aware ALL design decisions are documented in github.

They do have internal slack channels as well as regular "insider" meetings.

The Carbon Angular team (also Carbon Charts) has a quarterly community call which I believe is open to the public.

**Comment by lee-chase** [comment]
I believe our PAL site should be external.

**Comment by rodet** [comment]
Agree... Would be good to have that culture change happening and everything in the open. Follow the Carbon way of working first and then adjust for what doesn't work for us.

**Comment by andrea-gm** [comment]
I raised this recently with the DSIT and was met with some resistance. Mostly, I believe, because of the amount of work it would be to transfer over the internal repo's issues and the PAL site. We will need to plan, size the effort and make a proposal to get their support.

**Comment by SimonFinney** [comment]
It's a nice-to-have but for now, I think it's sufficient to have close collaboration with design and development within this repo

**Comment by andrea-gm** [comment]
Closing this issue for now. We can revisit in the future if needed.
