### ISSUE TITLE
NotificationsPanel - No way to set default "Do Not Disturb" Toggle value

### ISSUE THREAD

**Issue by rwibm** [carbon-design-system/ibm-cloud-cognitive#950]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When using the NotificationsPanel component there doesn't seem to be a way to set the default value for the "Do Not Disturb" toggle switch meaning it always defaults to "Off" whenever the component re-renders, and as there is no way of disabling the Toggle entirely its making this whole component not suitable for use without resetting the user's preference every time.

Is this a design choice, or is it a bug? I'd really rather not have to build my own notifications panel so if this is something that classes as a fixable bug then great! :) 

Related PR: https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/254

**Comment by matthewgallo** [comment]
Hey @rwibm, thanks for bringing this to our attention. We can definitely fix this. I'll reach back out when there is a PR

**Comment by matthewgallo** [comment]
Should be fixed with https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/956

**Comment by matthewgallo** [comment]
@rwibm what specific product are you working on? There is a global header that most teams have been using and we just want to make sure you're using the right thing

**Comment by matthewgallo** [comment]
This should be fixed here `@carbon/ibm-cloud-cognitive@0.50.5`.

**Comment by rwibm** [comment]
Perfect, thanks a lot! The quick turn around is very much appreciated :)
