### ISSUE TITLE
[SidePanel]: Strange focus behavior when an outside element is focused

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-cloud-cognitive#955]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

In the **SidePanel** component, I've noticed this bug: 

When an element is focused in the SidePanel (such as the panel's close button which is focused by default when the panel opens), if the user focuses on an outside element (such as the "Close side panel" button), the last focusable element in the panel receives focus (and if applicable, the panel scrolls to its position). This is either the last input field in the panel, or the last action button provided. The outside element also immediately loses focus, which is most apparent when it is an input field that the user cannot edit due to it constantly losing focus.

This behavior seems to only occur when there is no overlay rendered, and when using slideOver rather than slideIn.

In the C&CS Storybook, you can see this behavior under the stories:

- With Action Toolbar
- Specify Element to Have Initial Focus
- With Minimal Content

In the SOAR Playbook Designer where I am using this component, I notice this behavior happening when any button outside the panel is clicked, which makes the focus behavior more apparent since the panel does not close immediate afterwards.

In the provided CodeSandbox link, you can see this behavior with an outside input field continually losing focus.

Seen in Chrome & Firefox.

## Steps to reproduce the issue

1. Create a SidePanel with no overlay and as slide over
2. Populate SidePanel with focusable elements, like inputs or provide action button(s)
3. Open the SidePanel and make sure something inside is receiving focus
3. Focus/Click on an element outside the panel, like an input field or button
4. Notice the outside element immediately loses focus, while the last focusable element in the SidePanel receives focus

Created CodeSandbox:
https://codesandbox.io/s/ibm-cloud-cognitive-sidepanel-forked-kzlky?file=/src/App.tsx
1. Click the "Test side panel" button
2. The SidePanel's close button should automatically be focused, or you can click inside the panel's input field
3. Click inside the outside input field that says "focus here when focus is active in panel input"
4. Observe the outside input field immediately losing focus on click, while the last action button of the panel gains focus

## Additional information

https://user-images.githubusercontent.com/3118961/123992696-d7e0f500-d999-11eb-8585-36aadfdf9809.mov

**Comment by matthewgallo** [comment]
Hey @lily-peng, the side has a focus trap where the focus is intentionally kept within the panel (if it is a slide over panel). There is a section about this in the [CDAI Pal site](https://pages.github.ibm.com/cdai-design/pal/components/side-panel/usage/#focus). The `slideIn` version does not have the focus trap. If you have further questions, I'd be happy to help.

**Comment by lily-peng** [comment]
Hi @matthewgallo, thanks for the clarification! Reviewing the site, it looks like we actually need to use `slideIn` instead of `slideOver`. Thank you for your time
