### ISSUE TITLE
ButtonSetWithOverflow release review findings

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#976]
- [x] Custom component usage in `pageActions` prop? Currently, you have to pass an array of objects that get turned into buttons, what if I want to use my own custom component?
- [x] Add some comments how the hidden button set is measuring whatever it is measuring
- [x] `pageActionsLabel` remove default string prop, mark as required, and pass this prop instead.
- [x] Do we need to add the rest props to this component, since it is internal?
- [x] When would this component use `children` vs the `buttons` prop? Specifically we were looking at line 93 in `ButtonSetWithOverflow.js` and wondering when we'll ever be inside of that `else` statement.
- [x] Add tests to check that `size` and `rightAlign` props function as expected,

**Comment by lee-chase** [comment]
- The design does not currently support pageActions that are not buttons
- Rest not needed on internal components.
- The children prop is deprecated and should be removed when convenient to do so. I'll submit this as a PR by itself.
- Removed size as not used internally
- Added rightAlign test

**Comment by lee-chase** [comment]
@matthewgallo 989 addresses most issues, children will be moved in a PR dependant on this one.

**Comment by dcwarwick** [comment]
issues fixed in PRs above
