### ISSUE TITLE
Review findings for PageHeader

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#996]
Items found during release review of PageHeader:

- [x] #1008
- [x] Rename `actionBarOverflowLabel` to `actionBarOverflowAriaLabel`, `breadcrumbOverflowLabel` to `breadcrumbOverflowAriaLabel`, and rename `collapseHeaderLabel` to `collapseHeaderIconDescription` and `expandHeaderLabel` to `expandHeaderIconDescription`.
- [x] Is the prop `availableSpace` actually required? Could we not pass children of the PageHeader through to this area? The children of PageHeader doesn't currently seem to be used for anything.
- [x] Rename `background` to `hasBackground` and `collapseHeaderToggleWanted` to `hasCollapseHeaderToggle`.
- [x] Prop `breadcrumbItems` takes element rather than array of shape, while all the others (page actions, actions, tags, etc) take array of shape. Is this how it needs to be?
- [x] The assignment to attribute `data-collapse` in line 670 -- is that actually used?
- [x] The commentary for prop `pageHeaderOffset` is really unclear. When it says "page header", should that actually be "global header"? And how would you actually use this? Do you also need to force a top margin? Also, could this value not be detected automatically by the PageHeader on mounting by querying its own bounding box?
- [x] Rename `preCollapseTitleRow` to `collapseTitle`.
- [x] Rename `preventBreadcrumbScroll` to `disableBreadcrumbScroll`.
- [x] Remove defaults for `collapseHeaderIconDescription` and `expandHeaderIconDescription` and make them required (if `hasCollapseHeaderToggle` is true). Remove unnecessary defaults for `className`, `preventBreadcrumbScroll` and `preCollapseTitleRow`.
- [x] Add props for TagSet `allTagsModalTitle`, `allTagsModalSearchLabel`, `allTagsModalSearchPlaceholderText` and `showAllTagsLabel`.
- [x] When the title goes into the breadcrumb, its BreadcrumbItem has `href="#"`. This should be removed: it causes the breadcrumb item to reload the page on click. Or, if it really needs to be left in, the breadcrumb item produced should not trigger a page reload on click.
- [x] Ensure that all stories pass keys to action bar items so that warnings about missing keys and missing required fields are not produced in the storybook console.
- [x] Merge PageHeaderDemo.stories.js into PageHeader.stories.js in order to eliminate the duplicate title warnings in storybook
![image](https://user-images.githubusercontent.com/6385315/125715164-3cb01f2f-e6b7-429d-a032-ca19d34eaf8e.png)
- [x] Deprecated `availableSpace` prop not working because of this typo (omitted '=')
![image](https://user-images.githubusercontent.com/6385315/126335423-fed0b470-7f11-4adc-a051-56b7fa02996a.png)
- [x] Test for deprecated props doesn't actually test that the props *work*, just that they emit deprecation warnings. See bullet above!
- [ ] #1066
- [x] Copyright headers need updating to say "2020, 2021", and a copyright header needs adding to the PageHeaderUtils.js.
- [x] We couldn't spot a test for `collapseHeader`, `disableBreadcrumbScroll`, `expandHeaderIconDescription`, `pageActionsOverflowLabel`, and `pageHeaderOffset`.
- [x] Note that some of the tests are slightly overkill :-) e.g. `expect(screen.getByText(subtitle).textContent).toEqual(subtitle)` could equally well just be `screen.getByText(subtitle)`
- [x] Test coverage is very nearly 100% in all measures, but not quite :-)
- [x] There are quite a lot of stories -- maybe thin the list down a little to the key combinations, and set custom names on the stories so that they are a bit more readable.
- [x] Storybook previews in the docs page are all not loading -- probably a URL problem.

**Comment by lee-chase** [comment]
@dcwarwick @matthewgallo w.r.t. breadcrumbItems, if we don't use Carbon components here then I suspect we never use Carbon components except in free form areas. I think it's a Monday question.

**Comment by lee-chase** [comment]
w.r.t. title
https://github.com/carbon-design-system/carbon/issues/9224

I will wrap with span

**Comment by dcwarwick** [comment]
Above PRs close this issue, ready for release
