### ISSUE TITLE
Carbon colour tokens in storybook-styles files do not seem to compile with css variable substitution enabled

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-cloud-cognitive#999]
For example, the dummy-content blocks in PageHeader stories are fixed grey instead of dynamically using $ui-01 as the theme changes.

![image](https://user-images.githubusercontent.com/6385315/125657790-761ae196-e915-4a07-a973-59b53e74974b.png)

**Comment by dcwarwick** [comment]
@lee-chase FYI

**Comment by matthewgallo** [comment]
This seems to be fixed, all of the colors update to their corresponding token when switching themes now.
